import ScottDomains.Dyadic
-- `⌊·⌋₊` on `ℚ`. `addr` reads the dyadic block address of a point off the floor
-- of `s · 2ⁿ`; `FloorRing ℚ` is the instance that supplies `Nat.floor` there.
import Mathlib.Data.Rat.Floor

/-!
# Theorem 27 with its Boolean-algebra hypothesis discharged

Gunter & Scott, *Semantic Domains*, §7.3, quoted from the source PDF:

> If we adjoin the emptyset, say `B = U₀ ∪ {∅}`, then we get a Boolean algebra.
> (Note that the complement of a finite union of intervals is again one such —
> unless it is empty.) In particular, any interval contains a proper
> sub-interval so, as a Boolean algebra, `B` is atomless. But `B` is countable,
> and — up to isomorphism — the only countable atomless Boolean algebra is the
> free one on countably many generators. But this Boolean algebra has the
> property that every countable Boolean algebra is isomorphic to a subalgebra.
> Now, suppose `A` is a countable bounded complete poset. Let `B'` be the boolean
> algebra of subsets of `A` generated by those subsets of the form
> `↑x = {y ∈ A | x ⊑ y}` and order this collection by superset so that `∅` will
> be its largest element. The map `i : x ↦ ↑x` is a monotone injection which
> preserves existing least upper bounds. Moreover, a subset `u ⊆ A` is bounded
> just in case `⋂_{x ∈ u} ↑x` is non-empty. Now, if `j : B' → B` maps `B'`
> isomorphically onto a subalgebra of `B`, then the composition `j ∘ i` cuts down
> to an isomorphism between `A` and a normal subposet `A' ◁ U₀`.

`Dyadic.thm27_of_isNormallyRepresented` is everything after that paragraph,
already Lean-checked. This module supplies the paragraph itself, as
`Atomless.isNormallyRepresented`, and hence `Atomless.thm27` with no hypothesis.

## The route taken here is not the paper's

The paper reaches the embedding `B' ↪ B` from **Vaught's theorem**: the countable
atomless Boolean algebra is unique up to isomorphism, and the free algebra on
countably many generators has every countable Boolean algebra as a subalgebra.
Mathlib v4.32.2 has no atomless Boolean algebras at all — `IsAtomless` has zero
occurrences in `Mathlib/` — so that route costs a back-and-forth argument over
finite partial isomorphisms of Boolean algebras, and then still leaves the
paper's final clause ("cuts down to an isomorphism between `A` and a normal
subposet") unproved, since the paper asserts it without argument.

What is proved here instead is the conclusion directly, by an explicit
construction, and it never mentions a Boolean algebra. The three facts about the
map `ψ : A → U₀` that Theorem 27 actually consumes are

1. `a ≤ b ↔ ψ b ⊆ ψ a` — an order embedding into the superset order;
2. `ψ ⊥ = S`, the whole of `[0, 1)`;
3. `ψ a ∩ ψ b` is empty when `{a, b}` is unbounded in `A`, and is `ψ (a ⊔ b)`
   when it is bounded.

Property 3 is what makes `range ψ` a **normal** subposet: two members of
`range ψ` above a common `X ∈ U₀` have non-empty intersection, hence a join in
`A`, whose image is again above `X`. So 1–3 give the paragraph's conclusion, and
the Boolean-algebra language is a way of arriving at them rather than something
Theorem 27 needs.

## The construction

Read a point `s ∈ S` as an infinite sequence of binary digits: at level `n` it
lies in exactly one of the `2ⁿ` blocks `[j/2ⁿ, (j+1)/2ⁿ)`, and `addr n s` is that
block's index `j = ⌊s · 2ⁿ⌋`. Passing from level `n` to level `n + 1` splits each
block in two, so `addr (n+1) s / 2 = addr n s`: the address grows one binary
digit at a time and the digits of `s` are the choices made along a branch of the
infinite binary tree.

Fix an enumeration `enum : ℕ → A`. Label each node of that tree with an element
of `A` — `st A n j` is the label of the level-`n` node addressed by `j` — by

* `st A 0 j = ⊥`;
* `st A (n+1) j = st A n (j/2) ⊔ enum n` if the last digit `j % 2` is `1` **and**
  the step is *legal*, and `st A n (j/2)` otherwise.

A step is legal (`Legal`) when `{st A n (j/2), enum n}` is bounded **and**
adjoining `enum n` drags in no `enum i` with `i < n` that the branch does not
already carry. That second condition is the whole trick. Without it the set of
branches that have `a` on board is open but not closed, so `ψ a` would not be a
finite union of intervals; with it, whether a branch carries `enum i` is settled
at level `i + 1` and never revisited (`br_stable`). So

    ψ a = {s ∈ S | a ≤ st A (idx a + 1) (addr (idx a + 1) s)}

depends on the first `idx a + 1` binary digits of `s` alone, which is exactly to
say it is a finite union of dyadic half-open intervals (`isBasic_block`).

The legality side condition is also what the paper's atom-splitting does: in the
Boolean-algebra proof one refuses to place a new generator inside an atom of the
finite subalgebra built so far unless the atom can be split, and the refusal is
recorded permanently. Here the refusal is the `else` branch of `step`.

## Statements

* `Atomless.psi` — the map `ψ : A → U₀`, for any countable poset `A` with a least
  element in which bounded pairs have least upper bounds (`CountableBC`).
* `Atomless.isNormalIn_range_psi` — `range ψ ◁ U₀`.
* `Atomless.isNormallyRepresented` — `Dyadic.IsNormallyRepresented A`.
* `Atomless.thm27` — **Theorem 27, unconditionally**: for every bounded complete
  domain `D` there is an embedding–projection pair `D ⇄ U`, hence a projection
  `p : U → D`.
-/

namespace ScottDomains.Atomless

open ScottDomains.Dyadic

/-! ### Dyadic blocks and addresses

The level-`n` blocks are the `2ⁿ` intervals `[j/2ⁿ, (j+1)/2ⁿ)`. Every point of
`S` lies in exactly one of them, and the address function `addr` names it. -/

theorem two_pow_pos (n : ℕ) : (0 : ℚ) < 2 ^ n := pow_pos (by norm_num) n

theorem two_pow_ne_zero (n : ℕ) : ((2 : ℚ) ^ n) ≠ 0 := ne_of_gt (two_pow_pos n)

/-- The left endpoint of the `j`-th block of level `n`. -/
def blockLeft (n j : ℕ) : ℚ := (j : ℚ) / 2 ^ n

/-- The right endpoint of the `j`-th block of level `n`. -/
def blockRight (n j : ℕ) : ℚ := ((j : ℚ) + 1) / 2 ^ n

/-- Halving the denominator: `2k / 2ⁿ⁺¹ = k / 2ⁿ`. Used to exhibit every block
endpoint with the *positive* exponent `E` and `S` require. -/
theorem cast_div_two_pow_succ (k n : ℕ) :
    ((2 * k : ℕ) : ℚ) / 2 ^ (n + 1) = (k : ℚ) / 2 ^ n := by
  have h : ((2 : ℚ) ^ n) ≠ 0 := two_pow_ne_zero n
  push_cast
  rw [pow_succ]
  field_simp

/-- Every `k / 2ⁿ` with `k ≤ 2ⁿ` is an admissible interval endpoint. -/
theorem div_two_pow_mem_E {k n : ℕ} (h : k ≤ 2 ^ n) : ((k : ℚ) / 2 ^ n) ∈ E := by
  refine ⟨2 * k, n + 1, Nat.succ_pos n, ?_, (cast_div_two_pow_succ k n).symm⟩
  have h2 : 2 * k ≤ 2 * 2 ^ n := Nat.mul_le_mul_left 2 h
  calc 2 * k ≤ 2 * 2 ^ n := h2
    _ = 2 ^ (n + 1) := by rw [pow_succ]; ring

/-- Every `k / 2ⁿ` with `k < 2ⁿ` is a dyadic point of `[0, 1)`. -/
theorem div_two_pow_mem_S {k n : ℕ} (h : k < 2 ^ n) : ((k : ℚ) / 2 ^ n) ∈ S := by
  refine ⟨2 * k, n + 1, Nat.succ_pos n, ?_, (cast_div_two_pow_succ k n).symm⟩
  have h2 : 2 * k < 2 * 2 ^ n := by omega
  calc 2 * k < 2 * 2 ^ n := h2
    _ = 2 ^ (n + 1) := by rw [pow_succ]; ring

/-- **The level-`n` address of a dyadic point**: the index of the unique block
`[j/2ⁿ, (j+1)/2ⁿ)` containing it. -/
def addr (n : ℕ) (s : ℚ) : ℕ := ⌊s * 2 ^ n⌋₊

theorem mul_two_pow_nonneg {s : ℚ} (hs : s ∈ S) (n : ℕ) : 0 ≤ s * 2 ^ n :=
  mul_nonneg (mem_Ico_of_mem_S hs).1 (two_pow_pos n).le

theorem addr_lt {s : ℚ} (hs : s ∈ S) (n : ℕ) : addr n s < 2 ^ n := by
  rw [addr, Nat.floor_lt (mul_two_pow_nonneg hs n)]
  have h1 : s * 2 ^ n < 1 * 2 ^ n :=
    mul_lt_mul_of_pos_right (mem_Ico_of_mem_S hs).2 (two_pow_pos n)
  calc s * 2 ^ n < 1 * 2 ^ n := h1
    _ = ((2 ^ n : ℕ) : ℚ) := by push_cast; ring

/-- A point of `S` lies in the `j`-th block of level `n` exactly when its
level-`n` address is `j`. -/
theorem mem_Ivl_block {s : ℚ} (hs : s ∈ S) (n j : ℕ) :
    s ∈ Ivl (blockLeft n j) (blockRight n j) ↔ addr n s = j := by
  have h2 : (0 : ℚ) < 2 ^ n := two_pow_pos n
  rw [mem_Ivl, addr, Nat.floor_eq_iff (mul_two_pow_nonneg hs n), blockLeft, blockRight,
    div_le_iff₀ h2, lt_div_iff₀ h2]
  exact ⟨fun h => ⟨h.2.1, h.2.2⟩, fun h => ⟨hs, h.1, h.2⟩⟩

theorem blockLeft_mem_S {n j : ℕ} (h : j < 2 ^ n) : blockLeft n j ∈ S :=
  div_two_pow_mem_S h

theorem addr_blockLeft (n j : ℕ) : addr n (blockLeft n j) = j := by
  rw [addr, blockLeft, div_mul_cancel₀ _ (two_pow_ne_zero n), Nat.floor_natCast]

/-- **Blocks refine by halving.** Level `n + 1` splits each level-`n` block in
two, so an address at level `n + 1` carries one more binary digit than the same
point's address at level `n`. -/
theorem addr_succ_div_two {s : ℚ} (hs : s ∈ S) (n : ℕ) : addr (n + 1) s / 2 = addr n s := by
  have hx : 0 ≤ s * 2 ^ n := mul_two_pow_nonneg hs n
  have hx' : 0 ≤ s * 2 ^ (n + 1) := mul_two_pow_nonneg hs (n + 1)
  have hmul : s * 2 ^ (n + 1) = 2 * (s * 2 ^ n) := by rw [pow_succ]; ring
  have h1 : ((addr n s : ℕ) : ℚ) ≤ s * 2 ^ n := Nat.floor_le hx
  have h2 : s * 2 ^ n < (addr n s : ℕ) + 1 := Nat.lt_floor_add_one _
  have hlo : 2 * addr n s ≤ addr (n + 1) s := by
    refine Nat.le_floor ?_
    push_cast
    rw [hmul]
    linarith
  have hhi : addr (n + 1) s < 2 * addr n s + 2 := by
    refine (Nat.floor_lt hx').mpr ?_
    push_cast
    rw [hmul]
    linarith
  omega

/-- **A set of points cut out by a condition on level-`n` addresses is a finite
union of dyadic intervals** — namely the union of the blocks whose index
satisfies the condition. -/
theorem eq_unionOf_block (n : ℕ) (P : ℕ → Prop) [DecidablePred P] :
    {s : ℚ | s ∈ S ∧ P (addr n s)} =
      unionOf (((Finset.range (2 ^ n)).filter P).image
        fun j => (blockLeft n j, blockRight n j)) := by
  ext s
  simp only [Set.mem_setOf_eq, mem_unionOf, Finset.mem_image, Finset.mem_filter,
    Finset.mem_range]
  constructor
  · rintro ⟨hs, hP⟩
    exact ⟨(blockLeft n (addr n s), blockRight n (addr n s)),
      ⟨addr n s, ⟨addr_lt hs n, hP⟩, rfl⟩, (mem_Ivl_block hs n _).mpr rfl⟩
  · rintro ⟨p, ⟨j, ⟨-, hPj⟩, rfl⟩, hsp⟩
    have hs : s ∈ S := hsp.1
    rw [(mem_Ivl_block hs n j).mp hsp]
    exact ⟨hs, hPj⟩

/-- The same set, as a basis element of `U₀`, once it is known non-empty. -/
theorem isBasic_block (n : ℕ) (P : ℕ → Prop)
    (hne : {s : ℚ | s ∈ S ∧ P (addr n s)}.Nonempty) :
    IsBasic {s : ℚ | s ∈ S ∧ P (addr n s)} := by
  classical
  refine ⟨hne, _, ?_, eq_unionOf_block n P⟩
  intro p hp
  rw [Finset.mem_image] at hp
  obtain ⟨j, hj, rfl⟩ := hp
  rw [Finset.mem_filter, Finset.mem_range] at hj
  refine ⟨div_two_pow_mem_E (le_of_lt hj.1), ?_⟩
  have hcast : ((j : ℚ) + 1) = ((j + 1 : ℕ) : ℚ) := by push_cast; ring
  rw [blockRight, hcast]
  exact div_two_pow_mem_E hj.1

/-! ### A countable bounded complete poset -/

/-- **The paper's "countable bounded complete poset"**, as a class: `A` is
countable and every bounded pair has a least upper bound. The second condition is
the only consequence of bounded completeness the construction consumes, and it is
the same hypothesis `U₀.exists_isLUB_pair` supplies for `U₀` itself. -/
class CountableBC (A : Type*) [PartialOrder A] [OrderBot A] : Prop where
  /-- `A` is countable. -/
  countable : Countable A
  /-- Bounded pairs have least upper bounds. -/
  exists_isLUB_pair : ∀ a b : A, BddAbove ({a, b} : Set A) → ∃ c, IsLUB ({a, b} : Set A) c

section Poset

variable {A : Type*} [PartialOrder A] [OrderBot A] [CountableBC A]

theorem exists_enum (A : Type*) [PartialOrder A] [OrderBot A] [CountableBC A] :
    ∃ f : ℕ → A, Function.Surjective f :=
  @exists_surjective_nat A ⟨(⊥ : A)⟩ CountableBC.countable

/-- A fixed enumeration of `A`. -/
noncomputable def enum (A : Type*) [PartialOrder A] [OrderBot A] [CountableBC A] : ℕ → A :=
  (exists_enum A).choose

theorem enum_surjective (A : Type*) [PartialOrder A] [OrderBot A] [CountableBC A] :
    Function.Surjective (enum A) := (exists_enum A).choose_spec

/-- An index naming `a` in the enumeration. -/
noncomputable def idx (a : A) : ℕ := (enum_surjective A a).choose

@[simp] theorem enum_idx (a : A) : enum A (idx a) = a := (enum_surjective A a).choose_spec

open Classical in
/-- The least upper bound of a bounded pair, made a total function so it can be
used in a definition by recursion. The `else` branch is never reached. -/
noncomputable def jn (a b : A) : A :=
  if h : BddAbove ({a, b} : Set A) then (CountableBC.exists_isLUB_pair a b h).choose else a

theorem isLUB_jn {a b : A} (h : BddAbove ({a, b} : Set A)) :
    IsLUB ({a, b} : Set A) (jn a b) := by
  classical
  rw [jn, dif_pos h]
  exact (CountableBC.exists_isLUB_pair a b h).choose_spec

theorem le_jn_left {a b : A} (h : BddAbove ({a, b} : Set A)) : a ≤ jn a b :=
  (isLUB_jn h).1 (Set.mem_insert _ _)

theorem le_jn_right {a b : A} (h : BddAbove ({a, b} : Set A)) : b ≤ jn a b :=
  (isLUB_jn h).1 (Set.mem_insert_of_mem _ rfl)

theorem jn_le {a b c : A} (h : BddAbove ({a, b} : Set A)) (ha : a ≤ c) (hb : b ≤ c) :
    jn a b ≤ c :=
  (isLUB_jn h).2 (by rintro x (rfl | rfl) <;> assumption)

/-! ### The labelled binary tree -/

/-- **The side condition on a step.** Taking `enum n` on board is legal when the
pair is bounded and when the resulting join carries no `enum i`, `i < n`, that
the current state does not already carry. The second conjunct is what makes each
`ψ a` depend on finitely many binary digits: it forbids a branch from acquiring
an old element of the enumeration at an arbitrarily late level. -/
def Legal (n : ℕ) (z : A) : Prop :=
  BddAbove ({z, enum A n} : Set A) ∧ ∀ i < n, enum A i ≤ jn z (enum A n) → enum A i ≤ z

open Classical in
/-- One step of the labelling: the last binary digit `j % 2` asks for `enum n`,
and the step grants it exactly when that is legal. -/
noncomputable def step (n : ℕ) (z : A) (j : ℕ) : A :=
  if j % 2 = 1 ∧ Legal n z then jn z (enum A n) else z

theorem le_step (n : ℕ) (z : A) (j : ℕ) : z ≤ step n z j := by
  classical
  by_cases hc : j % 2 = 1 ∧ Legal n z
  · rw [step, if_pos hc]
    exact le_jn_left hc.2.1
  · rw [step, if_neg hc]

/-- **The step never acquires an old element.** This is `Legal`'s second
conjunct, read off the definition of `step`. -/
theorem step_stable {n : ℕ} {z : A} {j i : ℕ} (hi : i < n) (h : enum A i ≤ step n z j) :
    enum A i ≤ z := by
  classical
  by_cases hc : j % 2 = 1 ∧ Legal n z
  · rw [step, if_pos hc] at h
    exact hc.2.2 i hi h
  · rwa [step, if_neg hc] at h

/-- `st A n j` — the label of the level-`n` node addressed by the block index
`j`. Its parent is the node addressed by `j / 2`, and the last binary digit
`j % 2` decides whether the step is taken. -/
noncomputable def st (A : Type*) [PartialOrder A] [OrderBot A] [CountableBC A] : ℕ → ℕ → A
  | 0, _ => ⊥
  | n + 1, j => step n (st A n (j / 2)) j

@[simp] theorem st_zero (j : ℕ) : st A 0 j = (⊥ : A) := rfl

@[simp] theorem st_succ (n j : ℕ) : st A (n + 1) j = step n (st A n (j / 2)) j := rfl

/-- The label at level `n` of the branch whose binary digits are those of the
dyadic point `s`. -/
noncomputable def br (A : Type*) [PartialOrder A] [OrderBot A] [CountableBC A]
    (s : ℚ) (n : ℕ) : A := st A n (addr n s)

theorem br_succ {s : ℚ} (hs : s ∈ S) (n : ℕ) :
    br A s (n + 1) = step n (br A s n) (addr (n + 1) s) := by
  rw [br, st_succ, addr_succ_div_two hs, br]

theorem br_le_succ {s : ℚ} (hs : s ∈ S) (n : ℕ) : br A s n ≤ br A s (n + 1) := by
  rw [br_succ hs]
  exact le_step _ _ _

theorem br_mono {s : ℚ} (hs : s ∈ S) : Monotone (br A s) :=
  monotone_nat_of_le_succ (br_le_succ hs)

/-- **Membership is settled early and never revisited.** If `enum A i` is carried
by the branch at some level `n ≥ m > i`, it is already carried at level `m`. -/
theorem br_stable {s : ℚ} (hs : s ∈ S) {i m : ℕ} (him : i < m) :
    ∀ {n : ℕ}, m ≤ n → enum A i ≤ br A s n → enum A i ≤ br A s m := by
  intro n hmn
  induction n, hmn using Nat.le_induction with
  | base => exact id
  | succ n hmn ih =>
      intro h
      rw [br_succ hs] at h
      exact ih (step_stable (lt_of_lt_of_le him hmn) h)

/-! ### `ψ : A → U₀` -/

/-- **`ψ a`, as a set of dyadic points**: those whose branch has `a` on board by
level `idx a + 1`. -/
def psiSet (a : A) : Set ℚ :=
  {s : ℚ | s ∈ S ∧ a ≤ st A (idx a + 1) (addr (idx a + 1) s)}

theorem psiSet_subset_S (a : A) : psiSet a ⊆ S := fun _ h => h.1

/-- The level at which `ψ a` is decided is `idx a + 1`, but membership is
equivalent to the branch carrying `a` at *some* level — that is `br_stable`. -/
theorem mem_psiSet_iff {a : A} {s : ℚ} (hs : s ∈ S) :
    s ∈ psiSet a ↔ ∃ n, a ≤ br A s n := by
  constructor
  · rintro ⟨-, h⟩
    exact ⟨idx a + 1, h⟩
  · rintro ⟨n, hn⟩
    refine ⟨hs, ?_⟩
    have hle : a ≤ br A s (max n (idx a + 1)) :=
      hn.trans (br_mono hs (le_max_left _ _))
    have := br_stable hs (i := idx a) (m := idx a + 1) (Nat.lt_succ_self _)
      (le_max_right n (idx a + 1)) (by rwa [enum_idx])
    rwa [enum_idx] at this

theorem mem_psiSet_of_le {a : A} {s : ℚ} (hs : s ∈ S) {n : ℕ} (h : a ≤ br A s n) :
    s ∈ psiSet a := (mem_psiSet_iff hs).mpr ⟨n, h⟩

/-- `ψ ⊥` is the whole of `[0, 1)`, the least element of `U₀`. -/
theorem psiSet_bot : psiSet (⊥ : A) = S := by
  ext s
  exact ⟨fun h => h.1, fun h => ⟨h, bot_le⟩⟩

/-- `ψ` is order-reversing into `⊆`: a larger element of `A` names a smaller set
of points, which is *more* information in `U₀`'s superset order. -/
theorem psiSet_subset_of_le {a b : A} (h : a ≤ b) : psiSet b ⊆ psiSet a := by
  intro s hs
  obtain ⟨n, hn⟩ := (mem_psiSet_iff hs.1).mp hs
  exact mem_psiSet_of_le hs.1 (h.trans hn)

/-- **A common point forces boundedness.** If a branch carries both `a` and `b`,
its label bounds them, so `{a, b}` is bounded in `A`. This is the paper's
"`u ⊆ A` is bounded just in case `⋂_{x ∈ u} ↑x` is non-empty". -/
theorem bddAbove_of_psiSet_inter_nonempty {a b : A}
    (h : (psiSet a ∩ psiSet b).Nonempty) : BddAbove ({a, b} : Set A) := by
  obtain ⟨s, hsa, hsb⟩ := h
  have hs : s ∈ S := hsa.1
  obtain ⟨n, hn⟩ := (mem_psiSet_iff hs).mp hsa
  obtain ⟨m, hm⟩ := (mem_psiSet_iff hs).mp hsb
  refine ⟨br A s (max n m), ?_⟩
  rintro x (rfl | rfl)
  · exact hn.trans (br_mono hs (le_max_left _ _))
  · exact hm.trans (br_mono hs (le_max_right _ _))

/-- **`ψ` turns joins into intersections.** -/
theorem psiSet_inter {a b : A} (h : BddAbove ({a, b} : Set A)) :
    psiSet a ∩ psiSet b = psiSet (jn a b) := by
  ext s
  constructor
  · rintro ⟨hsa, hsb⟩
    have hs : s ∈ S := hsa.1
    obtain ⟨n, hn⟩ := (mem_psiSet_iff hs).mp hsa
    obtain ⟨m, hm⟩ := (mem_psiSet_iff hs).mp hsb
    refine mem_psiSet_of_le hs (n := max n m) (jn_le h ?_ ?_)
    · exact hn.trans (br_mono hs (le_max_left _ _))
    · exact hm.trans (br_mono hs (le_max_right _ _))
  · intro hsc
    exact ⟨psiSet_subset_of_le (le_jn_left h) hsc, psiSet_subset_of_le (le_jn_right h) hsc⟩

/-! ### The branch that stays below a given element -/

open Classical in
/-- The block address, at each level, of the branch that takes `enum n` on board
exactly when `enum n ≤ b`. -/
noncomputable def digits (b : A) : ℕ → ℕ
  | 0 => 0
  | n + 1 => 2 * digits b n + (if enum A n ≤ b then 1 else 0)

theorem digits_lt (b : A) : ∀ n : ℕ, digits b n < 2 ^ n
  | 0 => by simp [digits]
  | n + 1 => by
      have ih := digits_lt b n
      have h : digits b (n + 1) ≤ 2 * digits b n + 1 := by
        classical
        rw [digits]
        split <;> omega
      have h2 : (2 : ℕ) ^ (n + 1) = 2 * 2 ^ n := by rw [pow_succ]; ring
      omega

theorem digits_div_two (b : A) (n : ℕ) : digits b (n + 1) / 2 = digits b n := by
  classical
  rw [digits]
  split <;> omega

theorem digits_mod_two (b : A) {n : ℕ} (h : enum A n ≤ b) : digits b (n + 1) % 2 = 1 := by
  classical
  rw [digits, if_pos h]
  omega

theorem digits_mod_two' (b : A) {n : ℕ} (h : ¬ enum A n ≤ b) : digits b (n + 1) % 2 = 0 := by
  classical
  rw [digits, if_neg h]
  omega

/-- **The branch of `digits b` stays below `b` and reaches every element of the
enumeration that is below `b`.** Both halves are needed at once: the second is
what makes `ψ b` non-empty, and the first is what makes `ψ` reflect the order. -/
theorem digits_spec (b : A) :
    ∀ n : ℕ, st A n (digits b n) ≤ b ∧
      ∀ i < n, enum A i ≤ b → enum A i ≤ st A n (digits b n)
  | 0 => ⟨bot_le, fun i hi => absurd hi (Nat.not_lt_zero i)⟩
  | n + 1 => by
      classical
      obtain ⟨hle, hreach⟩ := digits_spec b n
      have hpar : st A (n + 1) (digits b (n + 1))
          = step n (st A n (digits b n)) (digits b (n + 1)) := by
        rw [st_succ, digits_div_two]
      by_cases hb : enum A n ≤ b
      · have hbdd : BddAbove ({st A n (digits b n), enum A n} : Set A) := by
          refine ⟨b, ?_⟩
          rintro x (rfl | rfl)
          · exact hle
          · exact hb
        have hlegal : Legal n (st A n (digits b n)) := by
          refine ⟨hbdd, fun i hi hij => hreach i hi ?_⟩
          exact hij.trans (jn_le hbdd hle hb)
        have hstep : st A (n + 1) (digits b (n + 1))
            = jn (st A n (digits b n)) (enum A n) := by
          rw [hpar, step, if_pos ⟨digits_mod_two b hb, hlegal⟩]
        refine ⟨?_, ?_⟩
        · rw [hstep]; exact jn_le hbdd hle hb
        · intro i hi hib
          rw [hstep]
          rcases Nat.lt_succ_iff_lt_or_eq.mp hi with hi' | rfl
          · exact (hreach i hi' hib).trans (le_jn_left hbdd)
          · exact le_jn_right hbdd
      · have hstep : st A (n + 1) (digits b (n + 1)) = st A n (digits b n) := by
          rw [hpar, step, if_neg]
          rintro ⟨hodd, -⟩
          rw [digits_mod_two' b hb] at hodd
          exact absurd hodd (by norm_num)
        refine ⟨by rw [hstep]; exact hle, ?_⟩
        intro i hi hib
        rw [hstep]
        rcases Nat.lt_succ_iff_lt_or_eq.mp hi with hi' | rfl
        · exact hreach i hi' hib
        · exact absurd hib hb

theorem st_digits_le (b : A) (n : ℕ) : st A n (digits b n) ≤ b := (digits_spec b n).1

theorem le_st_digits (b : A) : b ≤ st A (idx b + 1) (digits b (idx b + 1)) := by
  have := (digits_spec b (idx b + 1)).2 (idx b) (Nat.lt_succ_self _) (by rw [enum_idx])
  rwa [enum_idx] at this

/-- A dyadic point whose first `N` binary digits are those of the branch of
`digits b`. -/
noncomputable def pt (b : A) (N : ℕ) : ℚ := blockLeft N (digits b N)

theorem pt_mem_S (b : A) (N : ℕ) : pt b N ∈ S := blockLeft_mem_S (digits_lt b N)

theorem addr_pt (b : A) (N : ℕ) : ∀ n ≤ N, addr n (pt b N) = digits b n := by
  intro n hn
  obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_le hn
  clear hn
  induction d generalizing n with
  | zero => simpa [pt] using addr_blockLeft n (digits b n)
  | succ d ih =>
      have hswap : n + (d + 1) = (n + 1) + d := by omega
      rw [hswap]
      have h1 : addr (n + 1) (pt b (n + 1 + d)) = digits b (n + 1) := ih (n + 1)
      have h2 := addr_succ_div_two (pt_mem_S b (n + 1 + d)) n
      rw [h1] at h2
      rw [← h2, digits_div_two]

/-- `pt b N` is a point of `ψ b`, once `N` is deep enough to have decided `b`. -/
theorem pt_mem_psiSet (b : A) {N : ℕ} (h : idx b + 1 ≤ N) : pt b N ∈ psiSet b := by
  refine ⟨pt_mem_S b N, ?_⟩
  rw [addr_pt b N (idx b + 1) h]
  exact le_st_digits b

theorem psiSet_nonempty (a : A) : (psiSet a).Nonempty :=
  ⟨pt a (idx a + 1), pt_mem_psiSet a le_rfl⟩

/-- **`ψ` reflects the order.** If every point of `ψ b` lies in `ψ a`, then the
branch of `digits b` — which lies in `ψ b` and whose labels never rise above `b`
— forces `a ≤ b`. -/
theorem le_of_psiSet_subset {a b : A} (h : psiSet b ⊆ psiSet a) : a ≤ b := by
  set N := max (idx a + 1) (idx b + 1) with hN
  have hmem : pt b N ∈ psiSet a := h (pt_mem_psiSet b (le_max_right _ _))
  have hidx : addr (idx a + 1) (pt b N) = digits b (idx a + 1) :=
    addr_pt b N (idx a + 1) (le_max_left _ _)
  have := hmem.2
  rw [hidx] at this
  exact this.trans (st_digits_le b (idx a + 1))

/-! ### `ψ` as a map into `U₀` -/

theorem isBasic_psiSet (a : A) : IsBasic (psiSet a) :=
  isBasic_block (idx a + 1) (fun j => a ≤ st A (idx a + 1) j) (psiSet_nonempty a)

/-- **The map `ψ : A → U₀`** of §7.3's proof paragraph. -/
noncomputable def psi (a : A) : U₀ := U₀.mk (psiSet a) (isBasic_psiSet a)

@[simp] theorem toSet_psi (a : A) : U₀.toSet (psi a) = psiSet a := rfl

/-- `ψ` is an order embedding: `U₀` is ordered by superset, and `ψ` is inclusion
reversing in both directions. -/
@[simp] theorem psi_le_psi {a b : A} : psi a ≤ psi b ↔ a ≤ b :=
  ⟨fun h => le_of_psiSet_subset h, fun h => psiSet_subset_of_le h⟩

theorem psi_injective : Function.Injective (psi : A → U₀) := fun _ _ h =>
  le_antisymm (psi_le_psi.mp h.le) (psi_le_psi.mp h.ge)

@[simp] theorem psi_bot : psi (⊥ : A) = ⊥ := U₀.ext (by rw [toSet_psi, psiSet_bot, U₀.toSet_bot])

/-- **`range ψ` is a normal subposet of `U₀`.** Non-emptiness is `ψ ⊥ = [0, 1)`.
Directedness is `psiSet_inter`: two members of `range ψ` above a common `X` have
a common point, so their preimages are bounded in `A`, and the image of the join
is again above `X`. -/
theorem isNormalIn_range_psi :
    IsNormalIn (Set.range (psi : A → U₀)) (Set.univ : Set U₀) := by
  refine ⟨Set.subset_univ _, fun X _ => ⟨⟨psi (⊥ : A), ⟨⊥, rfl⟩, ?_⟩, ?_⟩⟩
  · rw [psi_bot]
    exact Set.mem_Iic.mpr bot_le
  · rintro _ ⟨⟨a, rfl⟩, hXa⟩ _ ⟨⟨b, rfl⟩, hXb⟩
    have hsa : U₀.toSet X ⊆ psiSet a := U₀.le_iff.mp hXa
    have hsb : U₀.toSet X ⊆ psiSet b := U₀.le_iff.mp hXb
    obtain ⟨t, ht⟩ := X.toSet_nonempty
    have hbdd : BddAbove ({a, b} : Set A) :=
      bddAbove_of_psiSet_inter_nonempty ⟨t, hsa ht, hsb ht⟩
    refine ⟨psi (jn a b), ⟨⟨jn a b, rfl⟩, ?_⟩, ?_, ?_⟩
    · refine U₀.le_iff.mpr ?_
      rw [toSet_psi, ← psiSet_inter hbdd]
      exact Set.subset_inter hsa hsb
    · exact psi_le_psi.mpr (le_jn_left hbdd)
    · exact psi_le_psi.mpr (le_jn_right hbdd)

/-- `ψ` as an order isomorphism onto its range. -/
noncomputable def psiOrderIso : A ≃o ↥(Set.range (psi : A → U₀)) where
  toEquiv := Equiv.ofInjective psi psi_injective
  map_rel_iff' := psi_le_psi

/-- **The paper's proof paragraph, proved.** Every countable poset with a least
element in which bounded pairs have least upper bounds is order-isomorphic to a
normal subposet of `U₀`. -/
theorem isNormallyRepresented (A : Type*) [PartialOrder A] [OrderBot A] [CountableBC A] :
    Dyadic.IsNormallyRepresented A :=
  ⟨Set.range (psi : A → U₀), isNormalIn_range_psi, ⟨psiOrderIso⟩⟩

end Poset

/-! ### Theorem 27 -/

section Thm27

universe u

variable {D : Type u} [CompletePartialOrder D]

/-- `K(D)` is a countable bounded complete poset when `D` is a bounded complete
domain: countability is the paper's definition of *domain*, and the least upper
bound of a bounded pair of compacts is compact by
`isCompactElement_of_isLUB_pair`. -/
instance instCountableBCCompacts [Domain D] [BoundedComplete D] :
    CountableBC ↥(compacts D) where
  countable := inferInstance
  exists_isLUB_pair a b h := by
    obtain ⟨u, hu⟩ := h
    have hbdd : BddAbove ({(a : D), (b : D)} : Set D) := by
      refine ⟨(u : D), ?_⟩
      rintro x (rfl | rfl)
      · exact hu (Set.mem_insert _ _)
      · exact hu (Set.mem_insert_of_mem _ rfl)
    have hlub : IsLUB ({(a : D), (b : D)} : Set D) (sSup ({(a : D), (b : D)} : Set D)) :=
      isLUB_sSup_of_bddAbove hbdd
    refine ⟨⟨sSup ({(a : D), (b : D)} : Set D),
      isCompactElement_of_isLUB_pair a.2 b.2 hlub⟩, ?_, ?_⟩
    · rintro x (rfl | rfl)
      · exact hlub.1 (Set.mem_insert _ _)
      · exact hlub.1 (Set.mem_insert_of_mem _ rfl)
    · intro c hc
      refine hlub.2 ?_
      rintro x (rfl | rfl)
      · exact hc (Set.mem_insert _ _)
      · exact hc (Set.mem_insert_of_mem _ rfl)

/-- **`IsNormallyRepresented ↥(compacts D)`** — the hypothesis of
`Dyadic.thm27_of_isNormallyRepresented`, discharged. -/
theorem isNormallyRepresented_compacts (D : Type u) [CompletePartialOrder D] [Domain D]
    [BoundedComplete D] : Dyadic.IsNormallyRepresented ↥(compacts D) :=
  isNormallyRepresented ↥(compacts D)

/-- **Theorem 27, with no hypothesis.** *For any bounded complete domain `D`
there is a projection `p : U → D`.* -/
theorem thm27 (D : Type u) [CompletePartialOrder D] [Domain D] [BoundedComplete D] :
    ∃ (e : ScottHom D Dyadic.U) (p : ScottHom Dyadic.U D),
      ScottHom.IsEmbeddingProjectionPair e p :=
  Dyadic.thm27_of_isNormallyRepresented D (isNormallyRepresented_compacts D)

end Thm27

end ScottDomains.Atomless
