import ScottDomains.Powerdomain.Hoare
import ScottDomains.Powerdomain.Smyth
import ScottDomains.Powerdomain.Plotkin
import ScottDomains.Product
import Mathlib.Data.Finset.Lattice.Fold

/-!
# Theorem 12: the powerdomains are free continuous algebras

Gunter & Scott, *Semantic Domains* (Handbook of Theoretical Computer Science
Vol. B, 1990), §5.3, quoted from the source PDF rather than paraphrased:

> **Definition:** A continuous algebra (of signature `(2)`) is a cpo `E` together
> with a continuous binary function `⋓ : E × E → E`. We refer to the following
> collection of axioms on `⋓` as theory `T♮`:
>
> 1. associativity: `(r ⋓ s) ⋓ t = r ⋓ (s ⋓ t)`
> 2. commutativity: `r ⋓ s = s ⋓ r`
> 3. idempotence: `s ⋓ s = s`.
>
> (These are the well-known semi-lattice axioms.) A homomorphism between
> continuous algebras `D` and `E` is a continuous function `f : D → E` such that
> `f (s ⋓ t) = f (s) ⋓ f (t)` for all `s, t ∈ D`.

> It is easy to check that, for any domain `D`, each of the algebras `D♮`, `D♯`
> and `D♭` satisfies `T♮`. However, `D♮` is the "free" continuous algebra over
> `D` which satisfies `T♮`:

> **Theorem 12** Let `D` be a domain. Suppose `⟨E, ⋓⟩` is a continuous algebra
> which satisfies `T♮`. For any continuous `f : D → E`, there is a unique
> homomorphism `ext(f) : D♮ → E` which completes the following diagram:
> [`{|·|} : D → D♮` down the left, `f : D → E` on the diagonal,
> `ext(f) : D♮ → E` along the bottom.]

> **Proof:** (Hint) If `u = {x₁, …, xₙ} ∈ s ∈ D♮`, and `û` is the principal
> ideal generated by `u`, then define `ext(f)(û) = f(x₁) ⋓ ⋯ ⋓ f(xₙ)`. This
> function has a unique continuous extension to all of `D♮` given by
> `ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}`.

> Now, consider the following axiom:
>
> `4♯. s ⋓ t ⊑ s.`
>
> Let `T♯` be the set of axioms obtained by adding axiom `4♯` to the axioms in
> `T♮`. Similarly, let `T♭` be obtained by adding the axiom
>
> `4♭. s ⊑ s ⋓ t`
>
> to the axioms in `T♮`. The point is this: Theorem 12 still holds when `D♮` and
> `T♮` are replaced by `D♯` and `T♯` respectively, or by `D♭` and `T♭`
> respectively.

## Two notational points about the source

The paper's own glyph for the algebra operation does not survive text extraction
from the PDF: `pdftotext` drops it, with and without `-layout`, in every one of
the six places it occurs on page 28. In §5.3, where the operation is exhibited on
a powerdomain, the paper writes a decorated `∪`. It is written `⋓` throughout
this file — `⊕`, which r0031's report and the r0032 plan use for the same
operation, is Lean core's notation for `Sum`, and declaring a second parse of it
makes every axiom of `T♮` an overload-resolution failure.

The base theory is the paper's `T♮` — *natural*, matching the convex powerdomain
`D♮` — not an undecorated `T`. `docs/PaperInventory.md` and the r0032 plan both
write `T`; the three musical accidentals are `♮` convex (Plotkin), `♯` upper
(Smyth), `♭` lower (Hoare). Otherwise r0031's reading is confirmed verbatim:
`T♯` adds `s ⋓ t ⊑ s` and `T♭` adds `s ⊑ s ⋓ t`.

## What each class corresponds to

| this file | the paper |
| --------- | --------- |
| `Binop E` | *a continuous algebra of signature `(2)`* — the cpo `E` with `⋓` |
| `IsSemilattice E` | theory `T♮`, axioms 1–3 |
| `IsUpper E` | theory `T♯` = `T♮` + `4♯` |
| `IsLower E` | theory `T♭` = `T♮` + `4♭` |
| `IsHom f` | *homomorphism between continuous algebras* |

## The algebraic order, and why the fold is built on it

`ext(f)(û) = f(x₁) ⋓ ⋯ ⋓ f(xₙ)` is a fold of `⋓` over a finite **non-empty** set,
and it must not depend on the enumeration. Axioms 1–3 say exactly that `⋓` is a
semilattice operation, so `E` carries a *second* partial order — the algebraic one,
`a ≼ b ↔ a ⋓ b = b` — under which `⋓` is `⊔`. `AlgOrder E` is that order as a type
synonym, and `fold` is Mathlib's `Finset.sup'` taken there. This buys
`Finset.sup'_singleton`, `sup'_union`, `sup'_image` and `sup'_cons` for free, and
the enumeration-independence is Mathlib's rather than a fresh induction.

The algebraic order `≼` is **not** the domain order `⊑` and the two are related
only under the strengthened theories: `T♭` makes `⋓` the binary join for `⊑`, and
`T♯` makes it the binary meet. Under `T♮` alone they are unrelated, which is why
the convex case of `fold_le_fold_of_convex` is the one that needs real work.
-/

namespace ScottDomains.ContinuousAlgebra

universe u

/-! ## 1. Continuous algebras and the three theories -/

/-- A **continuous algebra of signature `(2)`**: a cpo `E` together with a
continuous binary function `⋓ : E × E → E`.

Continuity is *joint* — Scott continuity of the single map `E × E → E` on the
product cpo of `Product.lean` — which is the paper's literal reading, and is what
`isLUB_op_image` below spends. -/
class Binop (E : Type u) [CompletePartialOrder E] where
  /-- The binary operation `⋓`. -/
  op : E → E → E
  /-- `⋓` is Scott continuous as a function of the pair. -/
  scottContinuous_op : ScottContinuous fun p : E × E => op p.1 p.2

@[inherit_doc Binop.op]
scoped infixl:65 " ⋓ " => Binop.op

section Binop

variable {E : Type u} [CompletePartialOrder E] [Binop E]

theorem scottContinuous_op : ScottContinuous fun p : E × E => p.1 ⋓ p.2 :=
  Binop.scottContinuous_op

/-- `⋓` is monotone in both arguments at once, by `ScottContinuous.monotone` on
the product order. -/
theorem op_mono {a b c d : E} (h₁ : a ≤ b) (h₂ : c ≤ d) : a ⋓ c ≤ b ⋓ d :=
  scottContinuous_op.monotone (show (a, c) ≤ (b, d) from ⟨h₁, h₂⟩)

theorem op_mono_left {a b c : E} (h : a ≤ b) : a ⋓ c ≤ b ⋓ c := op_mono h le_rfl

theorem op_mono_right {a b c : E} (h : b ≤ c) : a ⋓ b ≤ a ⋓ c := op_mono le_rfl h

/-- Joint continuity of `⋓` in the form the homomorphism proof needs: the
operation carries a pair of least upper bounds to the least upper bound of the
pairwise operation. -/
theorem isLUB_op_image {X Y : Set E} (hX : X.Nonempty) (hY : Y.Nonempty)
    (hdX : DirectedOn (· ≤ ·) X) (hdY : DirectedOn (· ≤ ·) Y) {a b : E}
    (ha : IsLUB X a) (hb : IsLUB Y b) :
    IsLUB ((fun p : E × E => p.1 ⋓ p.2) '' (X ×ˢ Y)) (a ⋓ b) := by
  have hne : (X ×ˢ Y).Nonempty :=
    ⟨(hX.choose, hY.choose), hX.choose_spec, hY.choose_spec⟩
  have hd : DirectedOn (· ≤ ·) (X ×ˢ Y) := by
    rintro ⟨x₁, y₁⟩ ⟨hx₁, hy₁⟩ ⟨x₂, y₂⟩ ⟨hx₂, hy₂⟩
    obtain ⟨x₃, hx₃, h₁, h₂⟩ := hdX x₁ hx₁ x₂ hx₂
    obtain ⟨y₃, hy₃, k₁, k₂⟩ := hdY y₁ hy₁ y₂ hy₂
    exact ⟨(x₃, y₃), ⟨hx₃, hy₃⟩, ⟨h₁, k₁⟩, ⟨h₂, k₂⟩⟩
  have hlub : IsLUB (X ×ˢ Y) (a, b) := by
    refine ⟨fun p hp => ⟨ha.1 hp.1, hb.1 hp.2⟩, fun q hq => ⟨?_, ?_⟩⟩
    · refine ha.2 fun x hx => ?_
      exact (hq (show (x, hY.choose) ∈ X ×ˢ Y from ⟨hx, hY.choose_spec⟩)).1
    · refine hb.2 fun y hy => ?_
      exact (hq (show (hX.choose, y) ∈ X ×ˢ Y from ⟨hX.choose_spec, hy⟩)).2
  exact scottContinuous_op (E := E) hne hd hlub

end Binop

/-- Theory **`T♮`**: the semi-lattice axioms 1–3 of the paper's definition. -/
class IsSemilattice (E : Type u) [CompletePartialOrder E] [Binop E] : Prop where
  /-- Axiom 1, associativity. -/
  op_assoc : ∀ r s t : E, (r ⋓ s) ⋓ t = r ⋓ (s ⋓ t)
  /-- Axiom 2, commutativity. -/
  op_comm : ∀ s t : E, s ⋓ t = t ⋓ s
  /-- Axiom 3, idempotence. -/
  op_idem : ∀ s : E, s ⋓ s = s

/-- Theory **`T♯`**: `T♮` together with the paper's axiom `4♯`, `s ⋓ t ⊑ s`. -/
class IsUpper (E : Type u) [CompletePartialOrder E] [Binop E] : Prop
    extends IsSemilattice E where
  /-- Axiom `4♯`. -/
  op_le_left : ∀ s t : E, s ⋓ t ≤ s

/-- Theory **`T♭`**: `T♮` together with the paper's axiom `4♭`, `s ⊑ s ⋓ t`. -/
class IsLower (E : Type u) [CompletePartialOrder E] [Binop E] : Prop
    extends IsSemilattice E where
  /-- Axiom `4♭`. -/
  left_le_op : ∀ s t : E, s ≤ s ⋓ t

export IsSemilattice (op_assoc op_comm op_idem)
export IsUpper (op_le_left)
export IsLower (left_le_op)

/-- A **homomorphism between continuous algebras**: a continuous function
carrying `⋓` to `⋓`. The paper's own sentence, with `D` renamed to avoid the
clash with the domain `D` of Theorem 12. -/
structure IsHom {F E : Type u} [CompletePartialOrder F] [CompletePartialOrder E]
    [Binop F] [Binop E] (f : F → E) : Prop where
  /-- A homomorphism of continuous algebras is a continuous function. -/
  scottContinuous : ScottContinuous f
  /-- `f (s ⋓ t) = f s ⋓ f t`. -/
  map_op : ∀ s t : F, f (s ⋓ t) = f s ⋓ f t

section Consequences

variable {E : Type u} [CompletePartialOrder E] [Binop E]

/-- Under `T♯`, `⋓` is the binary **meet** for the domain order: `4♯` and
commutativity make `s ⋓ t` a lower bound, and idempotence makes it the greatest
one. -/
theorem op_le_right [IsUpper E] (s t : E) : s ⋓ t ≤ t := by
  rw [op_comm]; exact op_le_left t s

theorem le_op [IsUpper E] {e s t : E} (h₁ : e ≤ s) (h₂ : e ≤ t) : e ≤ s ⋓ t := by
  calc e = e ⋓ e := (op_idem e).symm
    _ ≤ s ⋓ t := op_mono h₁ h₂

/-- Under `T♭`, `⋓` is the binary **join** for the domain order. -/
theorem right_le_op [IsLower E] (s t : E) : t ≤ s ⋓ t := by
  rw [op_comm]; exact left_le_op t s

theorem op_le [IsLower E] {e s t : E} (h₁ : s ≤ e) (h₂ : t ≤ e) : s ⋓ t ≤ e := by
  calc s ⋓ t ≤ e ⋓ e := op_mono h₁ h₂
    _ = e := op_idem e

end Consequences

/-! ## 2. The algebraic order, and the fold `f x₁ ⋓ ⋯ ⋓ f xₙ` -/

/-- `E` re-ordered by the **algebraic order of `⋓`**: `a ≼ b` iff `a ⋓ b = b`.
Under the axioms of `T♮` this is a partial order with `⋓` as its join, which is
what makes `Finset.sup'` available as the fold. A type synonym, because `≼` is a
different relation from the domain order `⊑` already on `E`. -/
def AlgOrder (E : Type u) : Type u := E

/-- `E → AlgOrder E`, the identity read into the algebraic order. -/
def toAlg {E : Type u} (e : E) : AlgOrder E := e

/-- `AlgOrder E → E`, the identity read back. -/
def ofAlg {E : Type u} (a : AlgOrder E) : E := a

@[simp] theorem ofAlg_toAlg {E : Type u} (e : E) : ofAlg (toAlg e) = e := rfl

@[simp] theorem toAlg_ofAlg {E : Type u} (a : AlgOrder E) : toAlg (ofAlg a) = a := rfl

section AlgOrder

variable {E : Type u} [CompletePartialOrder E] [Binop E] [IsSemilattice E]

/-- Reflexivity is idempotence; transitivity is associativity. -/
instance instPreorderAlgOrder : Preorder (AlgOrder E) where
  le a b := ofAlg a ⋓ ofAlg b = ofAlg b
  le_refl a := op_idem (ofAlg a)
  le_trans a b c hab hbc := by
    show ofAlg a ⋓ ofAlg c = ofAlg c
    rw [← hbc, ← op_assoc, hab]

theorem algOrder_le_def {a b : AlgOrder E} : a ≤ b ↔ ofAlg a ⋓ ofAlg b = ofAlg b := Iff.rfl

/-- Antisymmetry: `a = b ⋓ a = a ⋓ b = b`. -/
instance instPartialOrderAlgOrder : PartialOrder (AlgOrder E) where
  le_antisymm a b hab hba := by
    show ofAlg a = ofAlg b
    rw [← hba, op_comm, hab]

/-- The algebraic order's join **is** `⋓`. All three obligations are one
application each of associativity, commutativity and idempotence. -/
instance instSemilatticeSupAlgOrder : SemilatticeSup (AlgOrder E) where
  sup a b := toAlg (ofAlg a ⋓ ofAlg b)
  le_sup_left a b := by
    show ofAlg a ⋓ (ofAlg a ⋓ ofAlg b) = ofAlg a ⋓ ofAlg b
    rw [← op_assoc, op_idem]
  le_sup_right a b := by
    show ofAlg b ⋓ (ofAlg a ⋓ ofAlg b) = ofAlg a ⋓ ofAlg b
    rw [op_comm (ofAlg a), ← op_assoc, op_idem]
  sup_le a b c hac hbc := by
    show (ofAlg a ⋓ ofAlg b) ⋓ ofAlg c = ofAlg c
    rw [op_assoc, hbc, hac]

@[simp] theorem ofAlg_sup (a b : AlgOrder E) : ofAlg (a ⊔ b) = ofAlg a ⋓ ofAlg b := rfl

end AlgOrder

section Fold

variable {K : Type u} {E : Type u} [CompletePartialOrder E] [Binop E]

section Semilattice

variable [IsSemilattice E]

/-- **The paper's `f(x₁) ⋓ ⋯ ⋓ f(xₙ)`**, over a finite non-empty set `u`.

Independence of the enumeration is Mathlib's `Finset.sup'` in the algebraic
order, not a fresh induction. `fold` does not depend on the proof `hu` — the
`Finset.Nonempty` argument is a `Prop`, so proof irrelevance makes two calls with
different proofs definitionally equal (`fold_proof_irrel`). -/
def fold (u : Finset K) (hu : u.Nonempty) (f : K → E) : E :=
  ofAlg (u.sup' hu fun k => toAlg (f k))

theorem fold_proof_irrel {u : Finset K} (h h' : u.Nonempty) (f : K → E) :
    fold u h f = fold u h' f := rfl

/-- Transport the fold along an equality of finite sets. The `Finset.Nonempty`
argument is dependent on the set, so `rw` on the set alone produces an ill-typed
motive; this lemma is what the convex case rewrites with instead. -/
theorem fold_congr {u v : Finset K} (h : u = v) (hu : u.Nonempty) (hv : v.Nonempty)
    (f : K → E) : fold u hu f = fold v hv f := by subst h; rfl

@[simp] theorem fold_singleton (k : K) (f : K → E) :
    fold {k} (Finset.singleton_nonempty k) f = f k := rfl

/-- The fold turns union into `⋓`; this is `Finset.sup'_union` read back through
`ofAlg`, and it is the equation the homomorphism property of `ext(f)` runs on. -/
theorem fold_union [DecidableEq K] {u v : Finset K} (hu : u.Nonempty) (hv : v.Nonempty)
    (f : K → E) :
    fold (u ∪ v) (hu.mono Finset.subset_union_left) f = fold u hu f ⋓ fold v hv f := by
  show ofAlg ((u ∪ v).sup' _ _) = _
  rw [Finset.sup'_union hu hv]
  rfl

/-- The fold over an image is the fold of the composite — `Finset.sup'_image`. -/
theorem fold_image [DecidableEq K] {u : Finset K} (hu : u.Nonempty) (φ : K → K)
    (f : K → E) :
    fold (u.image φ) (hu.image φ) f = fold u hu (f ∘ φ) := by
  show ofAlg ((u.image φ).sup' _ _) = _
  rw [Finset.sup'_image]
  rfl

/-- **The fold is monotone in its function argument, for the domain order `⊑`.**
This is not a `Finset.sup'` lemma — `sup'` knows only the algebraic order — so it
is an induction over the non-empty finite set, with `op_mono` at the step. -/
theorem fold_le_fold {u : Finset K} (hu : u.Nonempty) {f g : K → E}
    (h : ∀ k ∈ u, f k ≤ g k) : fold u hu f ≤ fold u hu g := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton k => exact h k (Finset.mem_singleton_self k)
  | cons k s hks hs ih =>
      have hstep : fold (Finset.cons k s hks) (Finset.cons_nonempty hks) f
          = f k ⋓ fold s hs f := by
        show ofAlg ((Finset.cons k s hks).sup' _ _) = _
        rw [Finset.sup'_cons (H := hs)]
        rfl
      have hstep' : fold (Finset.cons k s hks) (Finset.cons_nonempty hks) g
          = g k ⋓ fold s hs g := by
        show ofAlg ((Finset.cons k s hks).sup' _ _) = _
        rw [Finset.sup'_cons (H := hs)]
        rfl
      rw [hstep, hstep']
      exact op_mono (h k (Finset.mem_cons_self k s))
        (ih fun a ha => h a (Finset.mem_cons_of_mem ha))

/-- The step equation of the induction above, isolated for reuse. -/
theorem fold_cons {k : K} {s : Finset K} (hks : k ∉ s) (hs : s.Nonempty) (f : K → E) :
    fold (Finset.cons k s hks) (Finset.cons_nonempty hks) f = f k ⋓ fold s hs f := by
  show ofAlg ((Finset.cons k s hks).sup' _ _) = _
  rw [Finset.sup'_cons (H := hs)]
  rfl

/-! ### The fold under the strengthened theories

Under `T♭` the fold is the **least upper bound** of `f '' u` in the domain order,
and under `T♯` it is the **greatest lower bound**. Under `T♮` it is neither, which
is the whole difficulty of the convex case. -/

end Semilattice

variable {u : Finset K} {f : K → E}

section Lower

variable [IsLower E]

theorem le_fold_of_mem {k : K} (hk : k ∈ u) (hu : u.Nonempty) :
    f k ≤ fold u hu f := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton a => rw [Finset.mem_singleton] at hk; subst hk; exact le_rfl
  | cons a s has hs ih =>
      rw [fold_cons has hs]
      rcases Finset.mem_cons.mp hk with rfl | hk'
      · exact left_le_op _ _
      · exact le_trans (ih hk') (right_le_op _ _)

theorem fold_le_of_forall (hu : u.Nonempty) {e : E} (h : ∀ k ∈ u, f k ≤ e) :
    fold u hu f ≤ e := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton a => exact h a (Finset.mem_singleton_self a)
  | cons a s has hs ih =>
      rw [fold_cons has hs]
      exact op_le (h a (Finset.mem_cons_self a s))
        (ih fun b hb => h b (Finset.mem_cons_of_mem hb))

end Lower

section Upper

variable [IsUpper E]

theorem fold_le_of_mem {k : K} (hk : k ∈ u) (hu : u.Nonempty) :
    fold u hu f ≤ f k := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton a => rw [Finset.mem_singleton] at hk; subst hk; exact le_rfl
  | cons a s has hs ih =>
      rw [fold_cons has hs]
      rcases Finset.mem_cons.mp hk with rfl | hk'
      · exact op_le_left _ _
      · exact le_trans (op_le_right _ _) (ih hk')

theorem le_fold_of_forall (hu : u.Nonempty) {e : E} (h : ∀ k ∈ u, e ≤ f k) :
    e ≤ fold u hu f := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton a => exact h a (Finset.mem_singleton_self a)
  | cons a s has hs ih =>
      rw [fold_cons has hs]
      exact le_op (h a (Finset.mem_cons_self a s))
        (ih fun b hb => h b (Finset.mem_cons_of_mem hb))

end Upper

end Fold

/-! ## 3. The fold is monotone for each of the three pre-orders

The three orderings of §5.2, on finite non-empty sets of compacts, are

* `u ⊑♭ v` — the **Hoare** conjunct, `∀ a ∈ u, ∃ b ∈ v, a ⊑ b`;
* `u ⊑♯ v` — the **Smyth** conjunct, `∀ b ∈ v, ∃ a ∈ u, a ⊑ b`;
* `u ⊑♮ v` — **Egli–Milner**, both conjuncts.

Each of the three statements below is what makes the fold descend to the ideal
completion of that pre-order. The theory needed goes up as the ordering gets
weaker: `T♭` for one conjunct, `T♯` for the other, and `T♮` alone once both are
present. -/

section FoldMono

variable {K : Type u} [Preorder K] {E : Type u} [CompletePartialOrder E] [Binop E]
variable {u v : Finset K} {f : K → E}

section Hoare

variable [IsLower E]

/-- **Hoare.** One conjunct, and `T♭`: the fold is the join, so it is below
`fold v` as soon as every `f a` is, and each `f a` is below some `f b ≤ fold v`. -/
theorem fold_le_fold_of_hoare (hu : u.Nonempty) (hv : v.Nonempty)
    (hf : Monotone f) (h : ∀ a ∈ u, ∃ b ∈ v, a ≤ b) :
    fold u hu f ≤ fold v hv f := by
  refine fold_le_of_forall hu fun a ha => ?_
  obtain ⟨b, hb, hab⟩ := h a ha
  exact le_trans (hf hab) (le_fold_of_mem hb hv)

end Hoare

section Smyth

variable [IsUpper E]

/-- **Smyth.** The other conjunct, and `T♯`: the fold is the meet, so it suffices
that it lies below each `f b`, and `fold u ≤ f a ≤ f b` for the witness `a`. -/
theorem fold_le_fold_of_smyth (hu : u.Nonempty) (hv : v.Nonempty)
    (hf : Monotone f) (h : ∀ b ∈ v, ∃ a ∈ u, a ≤ b) :
    fold u hu f ≤ fold v hv f := by
  refine le_fold_of_forall hv fun b hb => ?_
  obtain ⟨a, ha, hab⟩ := h b hb
  exact le_trans (fold_le_of_mem ha hu) (hf hab)

end Smyth

section Convex

variable [IsSemilattice E]

/-- **Egli–Milner, under `T♮` alone.** Neither of the two arguments above is
available: without `4♯` or `4♭` the operation `⋓` has no relation at all to the
domain order beyond monotonicity. The proof is instead the following chain, in
which `φ` is a choice of Hoare witness and `ψ` a choice of Smyth witness:

    fold u f = fold u f ⋓ fold (ψ '' v) f       (ψ '' v ⊆ u, so the union is u)
             = fold u f ⋓ fold v (f ∘ ψ)        (fold over an image)
             ⊑ fold u (f ∘ φ) ⋓ fold v f        (f a ⊑ f (φ a), f (ψ b) ⊑ f b)
             = fold (φ '' u) f ⋓ fold v f
             = fold v f                         (φ '' u ⊆ v, so the union is v)

Idempotence is spent twice, in the two `union_eq` steps; associativity and
commutativity are spent inside `fold_union`; and monotonicity of `⋓` is spent in
the middle step. -/
theorem fold_le_fold_of_convex (hu : u.Nonempty) (hv : v.Nonempty)
    (hf : Monotone f) (h₁ : ∀ a ∈ u, ∃ b ∈ v, a ≤ b) (h₂ : ∀ b ∈ v, ∃ a ∈ u, a ≤ b) :
    fold u hu f ≤ fold v hv f := by
  classical
  haveI : Nonempty K := ⟨hu.choose⟩
  choose! φ hφmem hφle using h₁
  choose! ψ hψmem hψle using h₂
  -- `ψ '' v ⊆ u` and `φ '' u ⊆ v`, so the two unions collapse.
  have hψsub : v.image ψ ⊆ u := Finset.image_subset_iff.mpr hψmem
  have hφsub : u.image φ ⊆ v := Finset.image_subset_iff.mpr hφmem
  have hune : u ∪ v.image ψ = u := Finset.union_eq_left.mpr hψsub
  have hvne : u.image φ ∪ v = v := Finset.union_eq_right.mpr hφsub
  -- `fold u f = fold u f ⋓ fold v (f ∘ ψ)`, because `u ∪ ψ '' v = u`.
  have hleft : fold u hu f = fold u hu f ⋓ fold v hv (f ∘ ψ) := by
    rw [← fold_image hv ψ f, ← fold_union hu (hv.image ψ) f]
    exact (fold_congr hune _ hu f).symm
  -- `fold v f = fold u (f ∘ φ) ⋓ fold v f`, because `φ '' u ∪ v = v`.
  have hright : fold u hu (f ∘ φ) ⋓ fold v hv f = fold v hv f := by
    rw [← fold_image hu φ f, ← fold_union (hu.image φ) hv f]
    exact fold_congr hvne _ hv f
  rw [hleft, ← hright]
  refine op_mono ?_ ?_
  · exact fold_le_fold hu fun a ha => hf (hφle a ha)
  · exact fold_le_fold hv fun b hb => hf (hψle b hb)

end Convex

end FoldMono

/-! ## 4. The universal property of the ideal completion

The paper's *"This function has a unique continuous extension to all of `D♮`
given by `ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}"* is a statement about ideal
completions and nothing else: it mentions neither `⋓` nor the axioms. It is
proved here in that generality, for an arbitrary pre-order `A` with a least
element and an arbitrary cpo `E`.

`idealExtend g I = ⨆ (g '' I)` is the unique Scott-continuous map
`IdealCompletion A → E` sending each principal ideal `↓a` to `g a`, for any
monotone `g : A → E`. Theorem 12 then reduces to producing the right `g` — the
fold — and checking that it is a homomorphism. -/

section IdealExtension

open IdealCompletion

variable {A : Type u} [Preorder A] {E : Type u} [CompletePartialOrder E]
variable {g : A → E}

/-- The principal ideals of the members of `I` form a directed family. -/
theorem directedOn_principal_image (I : IdealCompletion A) :
    DirectedOn (· ≤ ·) ((principal : A → IdealCompletion A) '' (I : Set A)) := by
  rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
  obtain ⟨c, hc, hac, hbc⟩ := I.directed a ha b hb
  exact ⟨principal c, Set.mem_image_of_mem _ hc, principal_mono hac, principal_mono hbc⟩

/-- **Every ideal is the least upper bound of its principal ideals.** This is the
sentence "`ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}`" reading in the other direction, and
it is what forces uniqueness. -/
theorem isLUB_principal_image (I : IdealCompletion A) :
    IsLUB ((principal : A → IdealCompletion A) '' (I : Set A)) I := by
  refine ⟨?_, fun J hJ a ha => ?_⟩
  · rintro _ ⟨a, ha, rfl⟩
    exact principal_le_iff.mpr ha
  · exact principal_le_iff.mp (hJ (Set.mem_image_of_mem _ ha))

theorem directedOn_image_of_monotone (hg : Monotone g) (I : IdealCompletion A) :
    DirectedOn (· ≤ ·) (g '' (I : Set A)) := by
  rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
  obtain ⟨c, hc, hac, hbc⟩ := I.directed a ha b hb
  exact ⟨g c, Set.mem_image_of_mem _ hc, hg hac, hg hbc⟩

/-- **The extension of the paper's hint**: `ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}`. -/
noncomputable def idealExtend (g : A → E) (I : IdealCompletion A) : E :=
  sSup (g '' (I : Set A))

theorem isLUB_idealExtend (hg : Monotone g) (I : IdealCompletion A) :
    IsLUB (g '' (I : Set A)) (idealExtend g I) :=
  (directedOn_image_of_monotone hg I).isLUB_sSup

/-- The extension **agrees with `g` on the principal ideals** — the paper's
`ext(f)(û) = f(x₁) ⋓ ⋯ ⋓ f(xₙ)`. -/
@[simp] theorem idealExtend_principal (hg : Monotone g) (a : A) :
    idealExtend g (principal a) = g a :=
  (isLUB_idealExtend hg (principal a)).unique
    ⟨by rintro _ ⟨b, hb, rfl⟩; exact hg hb, fun e he => he ⟨a, mem_principal_self a, rfl⟩⟩

theorem monotone_idealExtend (hg : Monotone g) : Monotone (idealExtend g) := by
  intro I J hIJ
  exact (isLUB_idealExtend hg I).2 fun _ ⟨a, ha, hae⟩ =>
    hae ▸ (isLUB_idealExtend hg J).1 ⟨a, hIJ ha, rfl⟩

variable [OrderBot A]

/-- **The extension is continuous.** The only fact used about a directed family of
ideals is that its least upper bound has the union as its underlying set, which is
`IdealCompletion.mem_sSup_iff`. -/
theorem scottContinuous_idealExtend (hg : Monotone g) :
    ScottContinuous (idealExtend g) := by
  intro S hne hd I hI
  have hIS : I = sSup S := hI.unique hd.isLUB_sSup
  refine ⟨?_, fun e he => (isLUB_idealExtend hg I).2 ?_⟩
  · rintro _ ⟨J, hJ, rfl⟩
    exact monotone_idealExtend hg (hI.1 hJ)
  · rintro _ ⟨a, ha, rfl⟩
    rw [hIS] at ha
    obtain ⟨J, hJ, haJ⟩ := (mem_sSup_iff hne hd).mp ha
    exact le_trans ((isLUB_idealExtend hg J).1 ⟨a, haJ, rfl⟩) (he ⟨J, hJ, rfl⟩)

omit [OrderBot A] in
/-- **Uniqueness.** A continuous map agreeing with `g` on every principal ideal is
`idealExtend g`: apply continuity to the directed family `{↓a | a ∈ I}`, whose
least upper bound is `I`. -/
theorem eq_idealExtend (hg : Monotone g) {h : IdealCompletion A → E}
    (hc : ScottContinuous h) (hp : ∀ a : A, h (principal a) = g a) :
    h = idealExtend g := by
  funext I
  have himg : h '' ((principal : A → IdealCompletion A) '' (I : Set A)) = g '' (I : Set A) := by
    ext e
    constructor
    · rintro ⟨_, ⟨a, ha, rfl⟩, rfl⟩
      exact ⟨a, ha, (hp a).symm⟩
    · rintro ⟨a, ha, rfl⟩
      exact ⟨principal a, ⟨a, ha, rfl⟩, hp a⟩
  have := hc (I.nonempty.image _) (directedOn_principal_image I) (isLUB_principal_image I)
  rw [himg] at this
  exact this.unique (isLUB_idealExtend hg I)

end IdealExtension

/-! ## 5. The operation `⋓` on a powerdomain

§5.3 opens by defining, for `s, t ∈ D♮`,

    s ⋓ t = {w | u ∪ v ⊢♮ w for some u ∈ s and v ∈ t}

and by saying "*Similar facts apply when `⋓` is defined in this way for `D♯` and
`D♭`*". The definition mentions the pre-order only through `⊢` and the union of
finite sets, so it is given here once, over any carrier `A` that presents its
elements as finite non-empty sets of compacts and is closed under union.

`FinSets` is that presentation. Its three instances — `Hoare.Pf ↥(compacts D)`,
`Smyth.Basis D` and `Plotkin.FinCompacts D` — differ in their carriers (a
`Finset` subtype, a `structure`, a `Set` subtype) and in their orderings, and
agree on everything below. -/

section Operation

open IdealCompletion

/-- A pre-order `A` whose elements **are** the finite non-empty subsets of a
pre-order `K`, closed under union and containing the singletons. This is the
common shape of the three pre-orders `⟨Pf(K(D)), ⊢♭⟩`, `⟨Pf(K(D)), ⊢♯⟩` and
`⟨Pf(K(D)), ⊢♮⟩` of §5.2.

`union_mono` and `singleton_mono` are the only fields that mention the order, and
they are exactly what the three orderings have in common; everything else is
about the finite sets. Union is stated membership-wise rather than as an equation
of `Finset`s so that the class does not have to carry a `DecidableEq K`. -/
class FinSets (K : outParam (Type u)) (A : Type u) [Preorder K] [Preorder A] where
  /-- The finite set of compacts that an element of `A` denotes. -/
  toFinset : A → Finset K
  /-- An element of `A` is determined by the finite set it denotes. -/
  toFinset_injective : Function.Injective toFinset
  /-- The paper's `Pf` excludes the empty set. -/
  toFinset_nonempty : ∀ u : A, (toFinset u).Nonempty
  /-- Every finite non-empty set of compacts is denoted. -/
  ofFinset : ∀ w : Finset K, w.Nonempty → A
  /-- `ofFinset` is a section of `toFinset`. -/
  toFinset_ofFinset : ∀ (w : Finset K) (hw : w.Nonempty), toFinset (ofFinset w hw) = w
  /-- Union of finite sets, transported to `A`. -/
  union : A → A → A
  /-- `union` denotes the union. -/
  mem_toFinset_union : ∀ (u v : A) (a : K),
    a ∈ toFinset (union u v) ↔ a ∈ toFinset u ∨ a ∈ toFinset v
  /-- Union is monotone for the pre-order of `A` — true for each of the three
  orderings, and the only order-theoretic fact the construction needs. -/
  union_mono : ∀ {u u' v v' : A}, u ≤ u' → v ≤ v' → union u v ≤ union u' v'
  /-- The singleton `{k}`. -/
  singleton : K → A
  /-- `singleton` denotes the singleton. -/
  toFinset_singleton : ∀ k : K, toFinset (singleton k) = {k}
  /-- `singleton` is monotone. -/
  singleton_mono : Monotone singleton

export FinSets (toFinset toFinset_injective toFinset_nonempty ofFinset toFinset_ofFinset
  union mem_toFinset_union union_mono singleton toFinset_singleton singleton_mono)

variable {K A : Type u} [Preorder K] [Preorder A] [FinSets K A]

@[simp] theorem toFinset_union [DecidableEq K] (u v : A) :
    toFinset (union u v) = toFinset u ∪ toFinset v := by
  ext a; rw [mem_toFinset_union, Finset.mem_union]

/-- `union` is idempotent, commutative and associative **on the nose**, because
`toFinset` is injective and `∪` is. -/
theorem union_self (u : A) : union u u = u := by
  classical
  exact toFinset_injective (by simp)

theorem union_comm' (u v : A) : union u v = union v u := by
  classical
  exact toFinset_injective (by simp [Finset.union_comm])

theorem union_assoc' (u v w : A) : union (union u v) w = union u (union v w) := by
  classical
  exact toFinset_injective (by simp [Finset.union_assoc])

theorem ofFinset_toFinset (u : A) : ofFinset (toFinset u) (toFinset_nonempty u) = u :=
  toFinset_injective (toFinset_ofFinset _ _)

section Bot

variable [OrderBot A]

/-- The paper's `s ⋓ t = {w | u ∪ v ⊢ w for some u ∈ s and v ∈ t}`, as a set. -/
def opSet (s t : IdealCompletion A) : Set A :=
  {w | ∃ u ∈ s, ∃ v ∈ t, w ≤ union u v}

omit [OrderBot A] in
/-- `s ⋓ t` is an ideal. Downward closure is transitivity; non-emptiness is
non-emptiness of `s` and `t`; directedness spends directedness of `s` and of `t`
together with `union_mono`. -/
theorem isIdeal_opSet (s t : IdealCompletion A) : Order.IsIdeal (opSet s t) := by
  refine ⟨fun a b hba ⟨u, hu, v, hv, hab⟩ => ⟨u, hu, v, hv, le_trans hba hab⟩, ?_, ?_⟩
  · obtain ⟨u, hu⟩ := s.nonempty
    obtain ⟨v, hv⟩ := t.nonempty
    exact ⟨union u v, u, hu, v, hv, le_rfl⟩
  · rintro a ⟨u₁, hu₁, v₁, hv₁, ha⟩ b ⟨u₂, hu₂, v₂, hv₂, hb⟩
    obtain ⟨u₃, hu₃, h₁₃, h₂₃⟩ := s.directed u₁ hu₁ u₂ hu₂
    obtain ⟨v₃, hv₃, k₁₃, k₂₃⟩ := t.directed v₁ hv₁ v₂ hv₂
    exact ⟨union u₃ v₃, ⟨u₃, hu₃, v₃, hv₃, le_rfl⟩,
      le_trans ha (union_mono h₁₃ k₁₃), le_trans hb (union_mono h₂₃ k₂₃)⟩

/-- **The powerdomain is a continuous algebra.** The operation is the paper's;
joint continuity is the second field, proved from `mem_sSup_iff` in each
coordinate. -/
noncomputable instance instBinopIdealCompletion : Binop (IdealCompletion A) where
  op s t := ofIdeal (isIdeal_opSet s t).toIdeal
  scottContinuous_op := by
    intro S hne hd p hp
    obtain ⟨hS₁, hS₂⟩ := isLUB_prod.mp hp
    have hd₁ : DirectedOn (· ≤ ·) (Prod.fst '' S) := directedOn_fst_image hd
    have hd₂ : DirectedOn (· ≤ ·) (Prod.snd '' S) := directedOn_snd_image hd
    have hmono : ∀ q ∈ S, (fun r : IdealCompletion A × IdealCompletion A =>
        ofIdeal (isIdeal_opSet r.1 r.2).toIdeal) q ≤
          ofIdeal (isIdeal_opSet p.1 p.2).toIdeal := by
      rintro q hq w ⟨u, hu, v, hv, hw⟩
      exact ⟨u, hp.1 hq |>.1 hu, v, hp.1 hq |>.2 hv, hw⟩
    refine ⟨?_, fun J hJ w hw => ?_⟩
    · rintro _ ⟨q, hq, rfl⟩
      exact hmono q hq
    · obtain ⟨u, hu, v, hv, hle⟩ := hw
      have hu' : u ∈ sSup (Prod.fst '' S) := (hS₁.unique hd₁.isLUB_sSup) ▸ hu
      have hv' : v ∈ sSup (Prod.snd '' S) := (hS₂.unique hd₂.isLUB_sSup) ▸ hv
      obtain ⟨_, ⟨q₁, hq₁, rfl⟩, huq⟩ := (mem_sSup_iff (hne.image _) hd₁).mp hu'
      obtain ⟨_, ⟨q₂, hq₂, rfl⟩, hvq⟩ := (mem_sSup_iff (hne.image _) hd₂).mp hv'
      obtain ⟨q₃, hq₃, h₁₃, h₂₃⟩ := hd q₁ hq₁ q₂ hq₂
      exact hJ ⟨q₃, hq₃, rfl⟩ ⟨u, h₁₃.1 huq, v, h₂₃.2 hvq, hle⟩

@[simp] theorem mem_op {w : A} {s t : IdealCompletion A} :
    w ∈ (s ⋓ t) ↔ ∃ u ∈ s, ∃ v ∈ t, w ≤ union u v := Iff.rfl

/-- `↓u ⋓ ↓v = ↓(u ∪ v)`: the operation on principal ideals **is** union. -/
theorem principal_op_principal (u v : A) :
    (principal u ⋓ principal v : IdealCompletion A) = principal (union u v) := by
  ext w
  refine ⟨?_, fun hw => ⟨u, mem_principal_self u, v, mem_principal_self v, hw⟩⟩
  rintro ⟨u', hu', v', hv', hw⟩
  exact le_trans hw (union_mono hu' hv')

/-- **`D♭`, `D♯` and `D♮` each satisfy `T♮`** — the paper's "*It is easy to check
that, for any domain `D`, each of the algebras `D♮`, `D♯` and `D♭` satisfies
`T♮`*". Each axiom reduces to the corresponding fact about `union`, with
directedness of an ideal supplying the collapse in the idempotence case. -/
instance instIsSemilatticeIdealCompletion : IsSemilattice (IdealCompletion A) where
  op_comm s t := by
    ext w
    constructor
    · rintro ⟨u, hu, v, hv, hw⟩
      exact ⟨v, hv, u, hu, by rwa [union_comm']⟩
    · rintro ⟨u, hu, v, hv, hw⟩
      exact ⟨v, hv, u, hu, by rwa [union_comm']⟩
  op_assoc r s t := by
    ext w
    constructor
    · rintro ⟨x, ⟨u, hu, v, hv, hx⟩, y, hy, hw⟩
      refine ⟨u, hu, union v y, ⟨v, hv, y, hy, le_rfl⟩, ?_⟩
      exact le_trans hw (le_trans (union_mono hx le_rfl) (le_of_eq (union_assoc' u v y)))
    · rintro ⟨u, hu, x, ⟨v, hv, y, hy, hx⟩, hw⟩
      refine ⟨union u v, ⟨u, hu, v, hv, le_rfl⟩, y, hy, ?_⟩
      exact le_trans hw (le_trans (union_mono le_rfl hx)
        (le_of_eq (union_assoc' u v y).symm))
  op_idem s := by
    ext w
    constructor
    · rintro ⟨u, hu, v, hv, hw⟩
      obtain ⟨z, hz, huz, hvz⟩ := s.directed u hu v hv
      refine s.lower (le_trans hw ?_) hz
      exact le_trans (union_mono huz hvz) (le_of_eq (union_self z))
    · intro hw
      exact ⟨w, hw, w, hw, le_of_eq (union_self w).symm⟩

/-- **Axiom `4♯` holds as soon as union is a *lower* bound in the pre-order.**
For the Smyth ordering `union u v ⊑♯ u`, so every generator of `s ⋓ t` is below a
generator of `s`, and `s` is downward closed. -/
theorem isUpper_of_union_le (h : ∀ u v : A, union u v ≤ u) :
    IsUpper (IdealCompletion A) where
  __ := instIsSemilatticeIdealCompletion (A := A)
  op_le_left s _ w := by
    rintro ⟨u, hu, v, _, hw⟩
    exact s.lower (le_trans hw (h u v)) hu

/-- **Axiom `4♭` holds as soon as union is an *upper* bound in the pre-order.**
For the Hoare ordering `u ⊑♭ union u v`, so each `w ∈ s` is itself a generator of
`s ⋓ t`, using any member of `t`. -/
theorem isLower_of_le_union (h : ∀ u v : A, u ≤ union u v) :
    IsLower (IdealCompletion A) where
  __ := instIsSemilatticeIdealCompletion (A := A)
  left_le_op s t w hw := by
    obtain ⟨v, hv⟩ := t.nonempty
    exact ⟨w, hw, v, hv, h w v⟩

end Bot

end Operation

/-! ## 6. Theorem 12

The free algebra, generically in the carrier. The one hypothesis that is *not*
generic is `hmono` — that the fold `u ↦ f(x₁) ⋓ ⋯ ⋓ f(xₙ)` is monotone for the
pre-order of `A`. That is where the theory is spent, and it is exactly what
§3's three theorems supply: `fold_le_fold_of_hoare` under `T♭`,
`fold_le_fold_of_smyth` under `T♯`, `fold_le_fold_of_convex` under `T♮`. -/

section Theorem12

open IdealCompletion

variable {D : Type u} [CompletePartialOrder D] [IsAlgebraic D]
variable {A : Type u} [Preorder A] [OrderBot A] [FinSets ↥(compacts D) A]
variable {E : Type u} [CompletePartialOrder E] [Binop E] [IsSemilattice E]

/-! ### The unit `{|·|} : D → D♮` -/

/-- The paper's `{|x|} = {u ∈ Pf(K(D)) | {x'} ⊢ u for some compact x' ⊑ x}`, as a
set. -/
def unitSet (x : D) : Set A :=
  {u : A | ∃ k : ↥(compacts D), (k : D) ≤ x ∧ u ≤ singleton k}

/-- `{|x|}` is an ideal. Directedness is where algebraicity of `D` is spent: two
compact approximants of `x` have a common compact approximant above them. -/
theorem isIdeal_unitSet (x : D) : Order.IsIdeal (unitSet (A := A) x) := by
  refine ⟨fun a b hba ⟨k, hk, hb⟩ => ⟨k, hk, le_trans hba hb⟩,
    ⟨⊥, ⊥, bot_le, bot_le⟩, ?_⟩
  rintro a ⟨k₁, hk₁, ha⟩ b ⟨k₂, hk₂, hb⟩
  obtain ⟨k₃, ⟨hk₃c, hk₃x⟩, h₁₃, h₂₃⟩ :=
    IsAlgebraic.directedOn_compactsBelow x (k₁ : D) ⟨k₁.2, hk₁⟩ (k₂ : D) ⟨k₂.2, hk₂⟩
  refine ⟨singleton ⟨k₃, hk₃c⟩, ⟨⟨k₃, hk₃c⟩, hk₃x, le_rfl⟩, ?_, ?_⟩
  · exact le_trans ha (singleton_mono (show k₁ ≤ (⟨k₃, hk₃c⟩ : ↥(compacts D)) from h₁₃))
  · exact le_trans hb (singleton_mono (show k₂ ≤ (⟨k₃, hk₃c⟩ : ↥(compacts D)) from h₂₃))

/-- **`{|·|} : D → D♮`**, the left leg of the paper's diagram. -/
def unit (x : D) : IdealCompletion A := ofIdeal (isIdeal_unitSet x).toIdeal

@[simp] theorem mem_unit {x : D} {u : A} :
    u ∈ (unit x : IdealCompletion A) ↔ ∃ k : ↥(compacts D), (k : D) ≤ x ∧ u ≤ singleton k :=
  Iff.rfl

/-- On a **compact** `k`, the unit is the principal ideal of `{k}`. This is what
makes uniqueness through `{|·|}` as strong as uniqueness through the principal
ideals. -/
theorem unit_coe_compact (k : ↥(compacts D)) :
    (unit (k : D) : IdealCompletion A) = principal (singleton k) := by
  ext u
  refine ⟨?_, fun hu => ⟨k, le_rfl, hu⟩⟩
  rintro ⟨k', hk', hu⟩
  exact le_trans hu (singleton_mono (show k' ≤ k from hk'))

theorem monotone_unit : Monotone (unit : D → IdealCompletion A) := by
  rintro x y hxy u ⟨k, hk, hu⟩
  exact ⟨k, le_trans hk hxy, hu⟩

/-- **The unit is continuous.** Leastness is where compactness of the `k` in the
definition is spent: a compact below `⨆ s` is below some member of `s`. -/
theorem scottContinuous_unit : ScottContinuous (unit : D → IdealCompletion A) := by
  intro s hne hd x hx
  refine ⟨?_, fun J hJ u hu => ?_⟩
  · rintro _ ⟨y, hy, rfl⟩
    exact monotone_unit (hx.1 hy)
  · obtain ⟨k, hk, hule⟩ := hu
    obtain ⟨y, hy, hky⟩ := k.2 s x hne hd hx hk
    exact hJ ⟨y, hy, rfl⟩ ⟨k, hky, hule⟩

/-! ### `ext(f)` -/

/-- The paper's `ext(f)(û) = f(x₁) ⋓ ⋯ ⋓ f(xₙ)`, on the generator `u` of the
principal ideal `û`. -/
def foldGen (f : D → E) (u : A) : E :=
  fold (toFinset u) (toFinset_nonempty u) fun k : ↥(compacts D) => f (k : D)

omit [IsAlgebraic D] [OrderBot A] in
/-- `foldGen` turns `union` into `⋓` — `fold_union` transported along
`toFinset_union`. -/
theorem foldGen_union (f : D → E) (u v : A) :
    foldGen f (union u v) = foldGen (A := A) f u ⋓ foldGen (A := A) f v := by
  classical
  simp only [foldGen]
  rw [← fold_union (toFinset_nonempty u) (toFinset_nonempty v)]
  exact fold_congr (toFinset_union u v) _ _ _

omit [IsAlgebraic D] [OrderBot A] in
@[simp] theorem foldGen_singleton (f : D → E) (k : ↥(compacts D)) :
    foldGen (A := A) f (singleton k) = f (k : D) := by
  refine (fold_congr (toFinset_singleton k) _ (Finset.singleton_nonempty k) _).trans ?_
  exact fold_singleton k _

/-- **`ext(f)`**, the paper's `ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}`. -/
noncomputable def ext (f : D → E) : IdealCompletion A → E := idealExtend (foldGen f)

variable {f : D → E}

omit [IsAlgebraic D] [OrderBot A] in
theorem ext_principal (hmono : Monotone (foldGen (A := A) f)) (u : A) :
    ext (A := A) f (principal u) = foldGen (A := A) f u :=
  idealExtend_principal hmono u

omit [IsAlgebraic D] in
theorem scottContinuous_ext (hmono : Monotone (foldGen (A := A) f)) :
    ScottContinuous (ext (A := A) f) :=
  scottContinuous_idealExtend hmono

omit [IsAlgebraic D] in
/-- **`ext(f)` is a homomorphism.** Both directions run on
`foldGen f (union u v) = foldGen f u ⋓ foldGen f v` and on the fact that
`union u v` is itself a member of `s ⋓ t`. -/
theorem isHom_ext (hmono : Monotone (foldGen (A := A) f)) :
    IsHom (ext (A := A) f) := by
  refine ⟨scottContinuous_ext hmono, fun s t => ?_⟩
  have hs := isLUB_idealExtend hmono s
  have ht := isLUB_idealExtend hmono t
  have hst := isLUB_idealExtend hmono (s ⋓ t)
  refine hst.unique ⟨?_, fun e he => ?_⟩
  · rintro _ ⟨w, ⟨u, hu, v, hv, hw⟩, rfl⟩
    refine le_trans (hmono hw) ?_
    rw [foldGen_union]
    exact op_mono (hs.1 ⟨u, hu, rfl⟩) (ht.1 ⟨v, hv, rfl⟩)
  · refine (isLUB_op_image (s.nonempty.image _) (t.nonempty.image _)
      (directedOn_image_of_monotone hmono s) (directedOn_image_of_monotone hmono t)
      hs ht).2 ?_
    rintro _ ⟨⟨_, _⟩, ⟨⟨u, hu, rfl⟩, ⟨v, hv, rfl⟩⟩, rfl⟩
    show foldGen (A := A) f u ⋓ foldGen (A := A) f v ≤ e
    rw [← foldGen_union]
    exact he ⟨union u v, ⟨u, hu, v, hv, le_rfl⟩, rfl⟩

/-- **`ext(f)` completes the diagram**: `ext(f) ∘ {|·|} = f`. Algebraicity of `D`
enters here as well — `f x` is the least upper bound of `f '' K(D)↓x`, and the
generators of `{|x|}` are exactly the singletons of those compacts. -/
theorem ext_unit (hmono : Monotone (foldGen (A := A) f)) (hf : ScottContinuous f) (x : D) :
    ext (A := A) f (unit x) = f x := by
  refine (isLUB_idealExtend hmono (unit x)).unique ⟨?_, fun e he => ?_⟩
  · rintro _ ⟨u, ⟨k, hk, hu⟩, rfl⟩
    exact le_trans (hmono hu) (by rw [foldGen_singleton]; exact hf.monotone hk)
  · refine (hf (compactsBelow_nonempty x) (IsAlgebraic.directedOn_compactsBelow x)
      (IsAlgebraic.isLUB_compactsBelow x)).2 ?_
    rintro _ ⟨c, ⟨hc, hcx⟩, rfl⟩
    have : foldGen (A := A) f (singleton ⟨c, hc⟩) = f c := foldGen_singleton f ⟨c, hc⟩
    rw [← this]
    exact he ⟨singleton ⟨c, hc⟩, ⟨⟨c, hc⟩, hcx, le_rfl⟩, rfl⟩

/-! ### Uniqueness -/

/-- A homomorphism commutes with the fold. Induction over the finite non-empty
set, with `IsHom.map_op` at the step. -/
theorem IsHom.map_fold {F : Type u} [CompletePartialOrder F] [Binop F] [IsSemilattice F]
    {h : F → E} (hh : IsHom h) {w : Finset K} (hw : w.Nonempty) (v : K → F) :
    h (fold w hw v) = fold w hw (h ∘ v) := by
  induction hw using Finset.Nonempty.cons_induction with
  | singleton a => simp
  | cons a s has hs ih =>
      rw [fold_cons has hs, fold_cons has hs, hh.map_op, ih]
      rfl

/-- Every principal ideal is the fold of the units of its generators:
`↓u = {|x₁|} ⋓ ⋯ ⋓ {|xₙ|}`. This is the statement that `D` **generates** the
powerdomain, and it is what turns uniqueness through `{|·|}` into uniqueness
through the principal ideals. -/
theorem principal_eq_fold_unit (u : A) :
    (principal u : IdealCompletion A)
      = fold (toFinset u) (toFinset_nonempty u)
          fun k : ↥(compacts D) => (unit (k : D) : IdealCompletion A) := by
  have key : ∀ (w : Finset ↥(compacts D)) (hw : w.Nonempty),
      (principal (ofFinset w hw) : IdealCompletion A)
        = fold w hw fun k => (unit (k : D) : IdealCompletion A) := by
    intro w hw
    induction hw using Finset.Nonempty.cons_induction with
    | singleton a =>
        have : ofFinset (A := A) {a} (Finset.singleton_nonempty a) = singleton a :=
          toFinset_injective (by rw [toFinset_ofFinset, toFinset_singleton])
        rw [this, fold_singleton, unit_coe_compact]
    | cons a s has hs ih =>
        classical
        have hcons : ofFinset (A := A) (Finset.cons a s has) (Finset.cons_nonempty has)
            = union (singleton a) (ofFinset s hs) := by
          refine toFinset_injective ?_
          rw [toFinset_ofFinset, toFinset_union, toFinset_singleton, toFinset_ofFinset,
            Finset.cons_eq_insert, Finset.singleton_union]
        rw [hcons, ← principal_op_principal, ih, fold_cons has hs, unit_coe_compact]
  refine (congrArg principal (ofFinset_toFinset u)).symm.trans ?_
  exact key (toFinset u) (toFinset_nonempty u)

/-- **Theorem 12** (Gunter & Scott §5.3), for whichever of the three
powerdomains the hypothesis `hmono` is discharged at.

*Let `D` be a domain. Suppose `⟨E, ⋓⟩` is a continuous algebra which satisfies
`T`. For any continuous `f : D → E`, there is a unique homomorphism
`ext(f) : Dᴾ → E` which completes the diagram* — that is, a unique
`h : Dᴾ → E` that is a homomorphism of continuous algebras and satisfies
`h ∘ {|·|} = f`.

Both halves are stated: `∃!` carries existence *and* uniqueness, and the
predicate carries *both* that `h` is a homomorphism (hence continuous) and that
it factors `f`. Countability of `K(D)` — the last clause of "domain" — is not
used; `[IsAlgebraic D]` is the whole hypothesis on `D`. -/
theorem theorem_12 (hf : ScottContinuous f) (hmono : Monotone (foldGen (A := A) f)) :
    ∃! h : IdealCompletion A → E, IsHom h ∧ ∀ x : D, h (unit x) = f x := by
  refine ⟨ext f, ⟨isHom_ext hmono, ext_unit hmono hf⟩, ?_⟩
  rintro h ⟨hhom, hdiag⟩
  refine eq_idealExtend hmono hhom.scottContinuous fun u => ?_
  have hcomp : (h ∘ fun k : ↥(compacts D) => (unit (k : D) : IdealCompletion A))
      = fun k : ↥(compacts D) => f (k : D) := funext fun k => hdiag (k : D)
  rw [principal_eq_fold_unit, hhom.map_fold, hcomp]
  rfl

end Theorem12

/-! ## 7. The three powerdomains

The paper's assignment of theory to powerdomain, checked against §5.2 and §5.3
rather than assumed:

| # | theory | axiom added to `T♮` | free algebra | this file |
| - | ------ | ------------------- | ------------ | --------- |
| 1 | `T♮` | — | `D♮`, the **convex** (Plotkin) powerdomain | `theorem_12_plotkin` |
| 2 | `T♯` | `4♯`, `s ⋓ t ⊑ s` | `D♯`, the **upper** (Smyth) powerdomain | `theorem_12_smyth` |
| 3 | `T♭` | `4♭`, `s ⊑ s ⋓ t` | `D♭`, the **lower** (Hoare) powerdomain | `theorem_12_hoare` |

The correspondence is *not* inverted: §5.2 defines `⊢♯` by
`u ⊢♯ v ↔ (∀ x ∈ u)(∃ y ∈ v). x ⊒ y` and calls `D♯` the **upper** powerdomain,
and §5.3 attaches `4♯ : s ⋓ t ⊑ s` to it. Adding an element to a set makes it
*smaller* in the upper ordering, which is exactly what `4♯` says at the level of
the algebra; dually for `♭`. The three `hmono` discharges below are where that
matching is checked by the kernel: `fold_le_fold_of_smyth` needs `IsUpper` and
consumes the Smyth conjunct, and it is the Smyth conjunct that
`Smyth.Basis.le_def` supplies.

Each instance is `noncomputable` only because `union` needs a `DecidableEq` on
`K(D)`, supplied classically. -/

section Instances

open IdealCompletion

variable {D : Type u} [CompletePartialOrder D]

/-! ### `D♭`, the Hoare (lower) powerdomain -/

open Classical in
/-- `Pf(K(D))` under `⊢♭` presents the finite non-empty sets of compacts. -/
noncomputable instance instFinSetsHoare :
    FinSets ↥(compacts D) (Hoare.Pf ↥(compacts D)) where
  toFinset u := u.toFinset
  toFinset_injective _ _ h := Hoare.Pf.ext h
  toFinset_nonempty u := u.toFinset_nonempty
  ofFinset w hw := Hoare.Pf.ofFinset w hw
  toFinset_ofFinset w hw := rfl
  union u v := Hoare.Pf.ofFinset (u.toFinset ∪ v.toFinset)
    (u.toFinset_nonempty.mono Finset.subset_union_left)
  mem_toFinset_union u v a := Finset.mem_union
  union_mono {u u' v v'} huu hvv x hx := by
    rcases Finset.mem_union.mp hx with hx' | hx'
    · obtain ⟨y, hy, hxy⟩ := huu x hx'
      exact ⟨y, Finset.mem_union_left _ hy, hxy⟩
    · obtain ⟨y, hy, hxy⟩ := hvv x hx'
      exact ⟨y, Finset.mem_union_right _ hy, hxy⟩
  singleton k := Hoare.Pf.ofFinset {k} (Finset.singleton_nonempty k)
  toFinset_singleton _ := rfl
  singleton_mono {k k'} h x hx := by
    rw [Hoare.Pf.mem_def, Hoare.Pf.toFinset_ofFinset, Finset.mem_singleton] at hx
    exact ⟨k', Finset.mem_singleton_self k', hx ▸ h⟩

open Classical in
/-- **`D♭` satisfies `T♭`.** The free algebra for a theory must itself be a model
of that theory, or `theorem_12_hoare` would be initiality in the wrong category. Here
it is `u ⊑♭ u ∪ v`, which holds because each `x ∈ u` witnesses itself. -/
instance instIsLowerHoare : IsLower (Hoare.Powerdomain D) :=
  isLower_of_le_union fun _ _ x hx => ⟨x, Finset.mem_union_left _ hx, le_rfl⟩

/-- **Theorem 12 at `D♭`.** Under `T♭` the Hoare (lower) powerdomain is the free
continuous algebra over `D`: for every continuous `f : D → E` there is exactly
one homomorphism `D♭ → E` with `h ∘ {|·|} = f`.

The single fact that carries the instantiation is `fold_le_fold_of_hoare`, and it
consumes precisely the Hoare conjunct `∀ x ∈ u, ∃ y ∈ v, x ⊑ y` that
`Hoare.Pf.le_def` gives. -/
theorem theorem_12_hoare [IsAlgebraic D] {E : Type u} [CompletePartialOrder E] [Binop E]
    [IsLower E] {f : D → E} (hf : ScottContinuous f) :
    ∃! h : Hoare.Powerdomain D → E, IsHom h ∧ ∀ x : D, h (unit x) = f x := by
  refine theorem_12 hf fun u v huv => ?_
  exact fold_le_fold_of_hoare _ _ (fun _ _ h => hf.monotone h) fun a ha =>
    Hoare.Pf.le_def.mp huv a ha

/-! ### `D♯`, the Smyth (upper) powerdomain -/

open Classical in
/-- `Pf(K(D))` under `⊢♯`. -/
noncomputable instance instFinSetsSmyth : FinSets ↥(compacts D) (Smyth.Basis D) where
  toFinset u := u.toFinset
  toFinset_injective := Smyth.Basis.toFinset_injective
  toFinset_nonempty u := u.nonempty'
  ofFinset w hw := ⟨w, hw⟩
  toFinset_ofFinset _ _ := rfl
  union u v := ⟨u.toFinset ∪ v.toFinset,
    u.nonempty'.mono Finset.subset_union_left⟩
  mem_toFinset_union _ _ _ := Finset.mem_union
  union_mono {u u' v v'} huu hvv b hb := by
    rcases Finset.mem_union.mp hb with hb' | hb'
    · obtain ⟨a, ha, hab⟩ := huu b hb'
      exact ⟨a, Finset.mem_union_left _ ha, hab⟩
    · obtain ⟨a, ha, hab⟩ := hvv b hb'
      exact ⟨a, Finset.mem_union_right _ ha, hab⟩
  singleton := Smyth.Basis.singleton
  toFinset_singleton _ := rfl
  singleton_mono _ _ h := Smyth.Basis.singleton_le_singleton.mpr h

open Classical in
/-- **`D♯` satisfies `T♯`**, the counterpart of `instIsLowerHoare`: in the upper
ordering `u ∪ v ⊑♯ u`, because each `b ∈ u` is matched by itself in `u ∪ v`. Note
the direction — adding elements makes a set *smaller* for `⊑♯`, which is exactly
the content of axiom `4♯`. -/
instance instIsUpperSmyth : IsUpper (Smyth.Powerdomain D) :=
  isUpper_of_union_le fun _ _ b hb => ⟨b, Finset.mem_union_left _ hb, le_rfl⟩

/-- **Theorem 12 at `D♯`.** Under `T♯` the Smyth (upper) powerdomain is the free
continuous algebra over `D`. `fold_le_fold_of_smyth` consumes the Smyth conjunct
`∀ y ∈ v, ∃ x ∈ u, x ⊑ y` that `Smyth.Basis.le_def` gives, and needs `4♯`. -/
theorem theorem_12_smyth [IsAlgebraic D] {E : Type u} [CompletePartialOrder E] [Binop E]
    [IsUpper E] {f : D → E} (hf : ScottContinuous f) :
    ∃! h : Smyth.Powerdomain D → E, IsHom h ∧ ∀ x : D, h (unit x) = f x := by
  refine theorem_12 hf fun u v huv => ?_
  exact fold_le_fold_of_smyth _ _ (fun _ _ h => hf.monotone h) fun b hb =>
    Smyth.Basis.le_def.mp huv b hb

/-! ### `D♮`, the Plotkin (convex) powerdomain -/

open Classical in
/-- `Pf(K(D))` under Egli–Milner. The carrier is a subtype of `Set`, not of
`Finset`, so `toFinset` goes through `Set.Finite.toFinset`. -/
noncomputable instance instFinSetsPlotkin :
    FinSets ↥(compacts D) (Plotkin.FinCompacts D) where
  toFinset u := u.finite.toFinset
  toFinset_injective u v h := by
    have h1 : ((u.finite.toFinset : Finset ↥(compacts D)) : Set ↥(compacts D))
        = ((v.finite.toFinset : Finset ↥(compacts D)) : Set ↥(compacts D)) :=
      congrArg (fun w : Finset ↥(compacts D) => (w : Set ↥(compacts D))) h
    rw [Set.Finite.coe_toFinset, Set.Finite.coe_toFinset] at h1
    exact Subtype.ext h1
  toFinset_nonempty u := by
    obtain ⟨a, ha⟩ := u.nonempty
    exact ⟨a, Set.Finite.mem_toFinset _ |>.mpr ha⟩
  ofFinset w hw := ⟨(w : Set ↥(compacts D)), w.finite_toSet, by
    obtain ⟨a, ha⟩ := hw; exact ⟨a, ha⟩⟩
  toFinset_ofFinset w hw := by
    ext a
    rw [Set.Finite.mem_toFinset]
    exact Finset.mem_coe
  union u v := ⟨u.carrier ∪ v.carrier, u.finite.union v.finite,
    u.nonempty.mono Set.subset_union_left⟩
  mem_toFinset_union u v a := by
    rw [Set.Finite.mem_toFinset, Set.Finite.mem_toFinset, Set.Finite.mem_toFinset]
    exact Set.mem_union _ _ _
  union_mono {u u' v v'} huu hvv := by
    constructor
    · rintro a (ha | ha)
      · obtain ⟨b, hb, hab⟩ := huu.1 a ha
        exact ⟨b, Or.inl hb, hab⟩
      · obtain ⟨b, hb, hab⟩ := hvv.1 a ha
        exact ⟨b, Or.inr hb, hab⟩
    · rintro b (hb | hb)
      · obtain ⟨a, ha, hab⟩ := huu.2 b hb
        exact ⟨a, Or.inl ha, hab⟩
      · obtain ⟨a, ha, hab⟩ := hvv.2 b hb
        exact ⟨a, Or.inr ha, hab⟩
  singleton := Plotkin.FinCompacts.single
  toFinset_singleton k := by
    ext a
    rw [Set.Finite.mem_toFinset, Finset.mem_singleton]
    exact Plotkin.FinCompacts.mem_single
  singleton_mono {k k'} h :=
    ⟨fun a ha => ⟨k', rfl, (Plotkin.FinCompacts.mem_single.mp ha) ▸ h⟩,
     fun b hb => ⟨k, rfl, (Plotkin.FinCompacts.mem_single.mp hb) ▸ h⟩⟩

/-- **Theorem 12 at `D♮`, the paper's own statement.** Under `T♮` alone — the
three semi-lattice axioms and nothing more — the Plotkin (convex) powerdomain is
the free continuous algebra over `D`.

This is the case the paper states as Theorem 12 proper; `theorem_12_hoare` and
`theorem_12_smyth` are the two it adds in the paragraph after the proof. It is also
the case where `fold_le_fold_of_convex` must do real work, since under `T♮` the
operation `⋓` is unrelated to the domain order. -/
theorem theorem_12_plotkin [IsAlgebraic D] {E : Type u} [CompletePartialOrder E] [Binop E]
    [IsSemilattice E] {f : D → E} (hf : ScottContinuous f) :
    ∃! h : Plotkin.Powerdomain D → E, IsHom h ∧ ∀ x : D, h (unit x) = f x := by
  refine theorem_12 hf fun u v huv => ?_
  refine fold_le_fold_of_convex _ _ (fun _ _ h => hf.monotone h) ?_ ?_
  · intro a ha
    obtain ⟨b, hb, hab⟩ := huv.1 a ((Set.Finite.mem_toFinset _).mp ha)
    exact ⟨b, (Set.Finite.mem_toFinset _).mpr hb, hab⟩
  · intro b hb
    obtain ⟨a, ha, hab⟩ := huv.2 b ((Set.Finite.mem_toFinset _).mp hb)
    exact ⟨a, (Set.Finite.mem_toFinset _).mpr ha, hab⟩

end Instances

/-! ## 8. The three algebras resolve

An instance that is never demanded is never checked. These force typeclass
resolution to run the whole chain — the `FinSets` presentation, the `Binop`, and
the axioms — at each of the three carriers, over `Prop`, the cheapest domain in
the development. The first three lines are the paper's "*each of the algebras
`D♮`, `D♯` and `D♭` satisfies `T♮`*"; the last two are the model conditions that
make `theorem_12_smyth` and `theorem_12_hoare` initiality statements inside their own
varieties. -/

section Witnesses

example : IsSemilattice (Hoare.Powerdomain Prop) := inferInstance
example : IsSemilattice (Smyth.Powerdomain Prop) := inferInstance
example : IsSemilattice (Plotkin.Powerdomain Prop) := inferInstance

example : IsUpper (Smyth.Powerdomain Prop) := inferInstance
example : IsLower (Hoare.Powerdomain Prop) := inferInstance

end Witnesses

end ScottDomains.ContinuousAlgebra

/- Axiom audit, by `#print axioms` (run, then removed so the build emits no
`info` lines). Every declaration depends only on the three standard axioms; none
depends on `sorryAx`.

  ScottDomains.ContinuousAlgebra.theorem_12                       [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.theorem_12_hoare                 [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.theorem_12_smyth                 [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.theorem_12_plotkin               [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.isHom_ext                        [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.ext_unit                         [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.principal_eq_fold_unit           [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.eq_idealExtend                   [propext, Quot.sound]
  ScottDomains.ContinuousAlgebra.scottContinuous_idealExtend      [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.scottContinuous_unit             [propext, Quot.sound]
  ScottDomains.ContinuousAlgebra.fold_le_fold_of_hoare            [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.fold_le_fold_of_smyth            [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.fold_le_fold_of_convex           [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.instBinopIdealCompletion         [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.instIsSemilatticeIdealCompletion [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.instFinSetsHoare                 [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.instFinSetsSmyth                 [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.instFinSetsPlotkin               [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.instIsUpperSmyth                 [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.instIsLowerHoare                 [propext, Classical.choice, Quot.sound]
  ScottDomains.ContinuousAlgebra.instSemilatticeSupAlgOrder       (none)

`instSemilatticeSupAlgOrder` is the outlier and the informative one: the
algebraic order of `⋓` and the proof that `⋓` is its join are pure equational
reasoning from axioms 1–3, with no appeal to choice, propositional extensionality
or quotients. Everything downstream inherits `Classical.choice` from
`IdealCompletion`'s `idealSup` (a `dite` on the undecidable `Order.IsIdeal`),
from `Set.Countable`/`Finset` decidability, and — in the convex case only — from
the `choose!` that picks the Egli–Milner witnesses `φ` and `ψ`. `eq_idealExtend`
and `scottContinuous_unit` need none of it. -/
