import ScottDomains.Powerdomain.Hoare
import ScottDomains.Powerdomain.Smyth
import ScottDomains.Powerdomain.Plotkin
import ScottDomains.Product
import Mathlib.Data.Finset.Lattice.Fold

/-!
# Theorem 12: the powerdomains are free continuous algebras

Gunter & Scott, *Semantic Domains* (Handbook of Theoretical Computer Science
Vol. B, 1990), §5.3, quoted from the source PDF rather than paraphrased:

> **Definition:** A continuous algebra (of signature `(2)`) is a cpo `E` together
> with a continuous binary function `⋓ : E × E → E`. We refer to the following
> collection of axioms on `⋓` as theory `T♮`:
>
> 1. associativity: `(r ⋓ s) ⋓ t = r ⋓ (s ⋓ t)`
> 2. commutativity: `r ⋓ s = s ⋓ r`
> 3. idempotence: `s ⋓ s = s`.
>
> (These are the well-known semi-lattice axioms.) A homomorphism between
> continuous algebras `D` and `E` is a continuous function `f : D → E` such that
> `f (s ⋓ t) = f (s) ⋓ f (t)` for all `s, t ∈ D`.

> It is easy to check that, for any domain `D`, each of the algebras `D♮`, `D♯`
> and `D♭` satisfies `T♮`. However, `D♮` is the "free" continuous algebra over
> `D` which satisfies `T♮`:

> **Theorem 12** Let `D` be a domain. Suppose `⟨E, ⋓⟩` is a continuous algebra
> which satisfies `T♮`. For any continuous `f : D → E`, there is a unique
> homomorphism `ext(f) : D♮ → E` which completes the following diagram:
> [`{|·|} : D → D♮` down the left, `f : D → E` on the diagonal,
> `ext(f) : D♮ → E` along the bottom.]

> **Proof:** (Hint) If `u = {x₁, …, xₙ} ∈ s ∈ D♮`, and `û` is the principal
> ideal generated by `u`, then define `ext(f)(û) = f(x₁) ⋓ ⋯ ⋓ f(xₙ)`. This
> function has a unique continuous extension to all of `D♮` given by
> `ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}`.

> Now, consider the following axiom:
>
> `4♯. s ⋓ t ⊑ s.`
>
> Let `T♯` be the set of axioms obtained by adding axiom `4♯` to the axioms in
> `T♮`. Similarly, let `T♭` be obtained by adding the axiom
>
> `4♭. s ⊑ s ⋓ t`
>
> to the axioms in `T♮`. The point is this: Theorem 12 still holds when `D♮` and
> `T♮` are replaced by `D♯` and `T♯` respectively, or by `D♭` and `T♭`
> respectively.

## Two notational points about the source

The paper's own glyph for the algebra operation does not survive text extraction
from the PDF: `pdftotext` drops it, with and without `-layout`, in every one of
the six places it occurs on page 28. In §5.3, where the operation is exhibited on
a powerdomain, the paper writes a decorated `∪`. It is written `⋓` throughout
this file — `⊕`, which r0031's report and the r0032 plan use for the same
operation, is Lean core's notation for `Sum`, and declaring a second parse of it
makes every axiom of `T♮` an overload-resolution failure.

The base theory is the paper's `T♮` — *natural*, matching the convex powerdomain
`D♮` — not an undecorated `T`. `docs/PaperInventory.md` and the r0032 plan both
write `T`; the three musical accidentals are `♮` convex (Plotkin), `♯` upper
(Smyth), `♭` lower (Hoare). Otherwise r0031's reading is confirmed verbatim:
`T♯` adds `s ⋓ t ⊑ s` and `T♭` adds `s ⊑ s ⋓ t`.

## What each class corresponds to

| this file | the paper |
| --------- | --------- |
| `Binop E` | *a continuous algebra of signature `(2)`* — the cpo `E` with `⋓` |
| `IsSemilattice E` | theory `T♮`, axioms 1–3 |
| `IsUpper E` | theory `T♯` = `T♮` + `4♯` |
| `IsLower E` | theory `T♭` = `T♮` + `4♭` |
| `IsHom f` | *homomorphism between continuous algebras* |

## The algebraic order, and why the fold is built on it

`ext(f)(û) = f(x₁) ⋓ ⋯ ⋓ f(xₙ)` is a fold of `⋓` over a finite **non-empty** set,
and it must not depend on the enumeration. Axioms 1–3 say exactly that `⋓` is a
semilattice operation, so `E` carries a *second* partial order — the algebraic one,
`a ≼ b ↔ a ⋓ b = b` — under which `⋓` is `⊔`. `AlgOrder E` is that order as a type
synonym, and `fold` is Mathlib's `Finset.sup'` taken there. This buys
`Finset.sup'_singleton`, `sup'_union`, `sup'_image` and `sup'_cons` for free, and
the enumeration-independence is Mathlib's rather than a fresh induction.

The algebraic order `≼` is **not** the domain order `⊑` and the two are related
only under the strengthened theories: `T♭` makes `⋓` the binary join for `⊑`, and
`T♯` makes it the binary meet. Under `T♮` alone they are unrelated, which is why
the convex case of `fold_le_fold_of_convex` is the one that needs real work.
-/

namespace ScottDomains.ContinuousAlgebra

universe u

/-! ## 1. Continuous algebras and the three theories -/

/-- A **continuous algebra of signature `(2)`**: a cpo `E` together with a
continuous binary function `⋓ : E × E → E`.

Continuity is *joint* — Scott continuity of the single map `E × E → E` on the
product cpo of `Product.lean` — which is the paper's literal reading, and is what
`isLUB_op_image` below spends. -/
class Binop (E : Type u) [CompletePartialOrder E] where
  /-- The binary operation `⋓`. -/
  op : E → E → E
  /-- `⋓` is Scott continuous as a function of the pair. -/
  scottContinuous_op : ScottContinuous fun p : E × E => op p.1 p.2

@[inherit_doc Binop.op]
scoped infixl:65 " ⋓ " => Binop.op

section Binop

variable {E : Type u} [CompletePartialOrder E] [Binop E]

theorem scottContinuous_op : ScottContinuous fun p : E × E => p.1 ⋓ p.2 :=
  Binop.scottContinuous_op

/-- `⋓` is monotone in both arguments at once, by `ScottContinuous.monotone` on
the product order. -/
theorem op_mono {a b c d : E} (h₁ : a ≤ b) (h₂ : c ≤ d) : a ⋓ c ≤ b ⋓ d :=
  scottContinuous_op.monotone (show (a, c) ≤ (b, d) from ⟨h₁, h₂⟩)

theorem op_mono_left {a b c : E} (h : a ≤ b) : a ⋓ c ≤ b ⋓ c := op_mono h le_rfl

theorem op_mono_right {a b c : E} (h : b ≤ c) : a ⋓ b ≤ a ⋓ c := op_mono le_rfl h

end Binop

/-- Theory **`T♮`**: the semi-lattice axioms 1–3 of the paper's definition. -/
class IsSemilattice (E : Type u) [CompletePartialOrder E] [Binop E] : Prop where
  /-- Axiom 1, associativity. -/
  op_assoc : ∀ r s t : E, (r ⋓ s) ⋓ t = r ⋓ (s ⋓ t)
  /-- Axiom 2, commutativity. -/
  op_comm : ∀ s t : E, s ⋓ t = t ⋓ s
  /-- Axiom 3, idempotence. -/
  op_idem : ∀ s : E, s ⋓ s = s

/-- Theory **`T♯`**: `T♮` together with the paper's axiom `4♯`, `s ⋓ t ⊑ s`. -/
class IsUpper (E : Type u) [CompletePartialOrder E] [Binop E] : Prop
    extends IsSemilattice E where
  /-- Axiom `4♯`. -/
  op_le_left : ∀ s t : E, s ⋓ t ≤ s

/-- Theory **`T♭`**: `T♮` together with the paper's axiom `4♭`, `s ⊑ s ⋓ t`. -/
class IsLower (E : Type u) [CompletePartialOrder E] [Binop E] : Prop
    extends IsSemilattice E where
  /-- Axiom `4♭`. -/
  left_le_op : ∀ s t : E, s ≤ s ⋓ t

export IsSemilattice (op_assoc op_comm op_idem)
export IsUpper (op_le_left)
export IsLower (left_le_op)

/-- A **homomorphism between continuous algebras**: a continuous function
carrying `⋓` to `⋓`. The paper's own sentence, with `D` renamed to avoid the
clash with the domain `D` of Theorem 12. -/
structure IsHom {F E : Type u} [CompletePartialOrder F] [CompletePartialOrder E]
    [Binop F] [Binop E] (f : F → E) : Prop where
  /-- A homomorphism of continuous algebras is a continuous function. -/
  scottContinuous : ScottContinuous f
  /-- `f (s ⋓ t) = f s ⋓ f t`. -/
  map_op : ∀ s t : F, f (s ⋓ t) = f s ⋓ f t

section Consequences

variable {E : Type u} [CompletePartialOrder E] [Binop E]

/-- Under `T♯`, `⋓` is the binary **meet** for the domain order: `4♯` and
commutativity make `s ⋓ t` a lower bound, and idempotence makes it the greatest
one. -/
theorem op_le_right [IsUpper E] (s t : E) : s ⋓ t ≤ t := by
  rw [op_comm]; exact op_le_left t s

theorem le_op [IsUpper E] {e s t : E} (h₁ : e ≤ s) (h₂ : e ≤ t) : e ≤ s ⋓ t := by
  calc e = e ⋓ e := (op_idem e).symm
    _ ≤ s ⋓ t := op_mono h₁ h₂

/-- Under `T♭`, `⋓` is the binary **join** for the domain order. -/
theorem right_le_op [IsLower E] (s t : E) : t ≤ s ⋓ t := by
  rw [op_comm]; exact left_le_op t s

theorem op_le [IsLower E] {e s t : E} (h₁ : s ≤ e) (h₂ : t ≤ e) : s ⋓ t ≤ e := by
  calc s ⋓ t ≤ e ⋓ e := op_mono h₁ h₂
    _ = e := op_idem e

end Consequences

/-! ## 2. The algebraic order, and the fold `f x₁ ⋓ ⋯ ⋓ f xₙ` -/

/-- `E` re-ordered by the **algebraic order of `⋓`**: `a ≼ b` iff `a ⋓ b = b`.
Under the axioms of `T♮` this is a partial order with `⋓` as its join, which is
what makes `Finset.sup'` available as the fold. A type synonym, because `≼` is a
different relation from the domain order `⊑` already on `E`. -/
def AlgOrder (E : Type u) : Type u := E

/-- `E → AlgOrder E`, the identity read into the algebraic order. -/
def toAlg {E : Type u} (e : E) : AlgOrder E := e

/-- `AlgOrder E → E`, the identity read back. -/
def ofAlg {E : Type u} (a : AlgOrder E) : E := a

@[simp] theorem ofAlg_toAlg {E : Type u} (e : E) : ofAlg (toAlg e) = e := rfl

@[simp] theorem toAlg_ofAlg {E : Type u} (a : AlgOrder E) : toAlg (ofAlg a) = a := rfl

section AlgOrder

variable {E : Type u} [CompletePartialOrder E] [Binop E] [IsSemilattice E]

/-- Reflexivity is idempotence; transitivity is associativity. -/
instance instPreorderAlgOrder : Preorder (AlgOrder E) where
  le a b := ofAlg a ⋓ ofAlg b = ofAlg b
  le_refl a := op_idem (ofAlg a)
  le_trans a b c hab hbc := by
    show ofAlg a ⋓ ofAlg c = ofAlg c
    rw [← hbc, ← op_assoc, hab]

theorem algOrder_le_def {a b : AlgOrder E} : a ≤ b ↔ ofAlg a ⋓ ofAlg b = ofAlg b := Iff.rfl

/-- Antisymmetry: `a = b ⋓ a = a ⋓ b = b`. -/
instance instPartialOrderAlgOrder : PartialOrder (AlgOrder E) where
  le_antisymm a b hab hba := by
    show ofAlg a = ofAlg b
    rw [← hba, op_comm, hab]

/-- The algebraic order's join **is** `⋓`. All three obligations are one
application each of associativity, commutativity and idempotence. -/
instance instSemilatticeSupAlgOrder : SemilatticeSup (AlgOrder E) where
  sup a b := toAlg (ofAlg a ⋓ ofAlg b)
  le_sup_left a b := by
    show ofAlg a ⋓ (ofAlg a ⋓ ofAlg b) = ofAlg a ⋓ ofAlg b
    rw [← op_assoc, op_idem]
  le_sup_right a b := by
    show ofAlg b ⋓ (ofAlg a ⋓ ofAlg b) = ofAlg a ⋓ ofAlg b
    rw [op_comm (ofAlg a), ← op_assoc, op_idem]
  sup_le a b c hac hbc := by
    show (ofAlg a ⋓ ofAlg b) ⋓ ofAlg c = ofAlg c
    rw [op_assoc, hbc, hac]

@[simp] theorem ofAlg_sup (a b : AlgOrder E) : ofAlg (a ⊔ b) = ofAlg a ⋓ ofAlg b := rfl

end AlgOrder

section Fold

variable {K : Type u} {E : Type u} [CompletePartialOrder E] [Binop E]

section Semilattice

variable [IsSemilattice E]

/-- **The paper's `f(x₁) ⋓ ⋯ ⋓ f(xₙ)`**, over a finite non-empty set `u`.

Independence of the enumeration is Mathlib's `Finset.sup'` in the algebraic
order, not a fresh induction. `fold` does not depend on the proof `hu` — the
`Finset.Nonempty` argument is a `Prop`, so proof irrelevance makes two calls with
different proofs definitionally equal (`fold_proof_irrel`). -/
def fold (u : Finset K) (hu : u.Nonempty) (f : K → E) : E :=
  ofAlg (u.sup' hu fun k => toAlg (f k))

theorem fold_proof_irrel {u : Finset K} (h h' : u.Nonempty) (f : K → E) :
    fold u h f = fold u h' f := rfl

/-- Transport the fold along an equality of finite sets. The `Finset.Nonempty`
argument is dependent on the set, so `rw` on the set alone produces an ill-typed
motive; this lemma is what the convex case rewrites with instead. -/
theorem fold_congr {u v : Finset K} (h : u = v) (hu : u.Nonempty) (hv : v.Nonempty)
    (f : K → E) : fold u hu f = fold v hv f := by subst h; rfl

@[simp] theorem fold_singleton (k : K) (f : K → E) :
    fold {k} (Finset.singleton_nonempty k) f = f k := rfl

/-- The fold turns union into `⋓`; this is `Finset.sup'_union` read back through
`ofAlg`, and it is the equation the homomorphism property of `ext(f)` runs on. -/
theorem fold_union [DecidableEq K] {u v : Finset K} (hu : u.Nonempty) (hv : v.Nonempty)
    (f : K → E) :
    fold (u ∪ v) (hu.mono Finset.subset_union_left) f = fold u hu f ⋓ fold v hv f := by
  show ofAlg ((u ∪ v).sup' _ _) = _
  rw [Finset.sup'_union hu hv]
  rfl

/-- The fold over an image is the fold of the composite — `Finset.sup'_image`. -/
theorem fold_image [DecidableEq K] {u : Finset K} (hu : u.Nonempty) (φ : K → K)
    (f : K → E) :
    fold (u.image φ) (hu.image φ) f = fold u hu (f ∘ φ) := by
  show ofAlg ((u.image φ).sup' _ _) = _
  rw [Finset.sup'_image]
  rfl

/-- **The fold is monotone in its function argument, for the domain order `⊑`.**
This is not a `Finset.sup'` lemma — `sup'` knows only the algebraic order — so it
is an induction over the non-empty finite set, with `op_mono` at the step. -/
theorem fold_le_fold {u : Finset K} (hu : u.Nonempty) {f g : K → E}
    (h : ∀ k ∈ u, f k ≤ g k) : fold u hu f ≤ fold u hu g := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton k => exact h k (Finset.mem_singleton_self k)
  | cons k s hks hs ih =>
      have hstep : fold (Finset.cons k s hks) (Finset.cons_nonempty hks) f
          = f k ⋓ fold s hs f := by
        show ofAlg ((Finset.cons k s hks).sup' _ _) = _
        rw [Finset.sup'_cons (H := hs)]
        rfl
      have hstep' : fold (Finset.cons k s hks) (Finset.cons_nonempty hks) g
          = g k ⋓ fold s hs g := by
        show ofAlg ((Finset.cons k s hks).sup' _ _) = _
        rw [Finset.sup'_cons (H := hs)]
        rfl
      rw [hstep, hstep']
      exact op_mono (h k (Finset.mem_cons_self k s))
        (ih fun a ha => h a (Finset.mem_cons_of_mem ha))

/-- The step equation of the induction above, isolated for reuse. -/
theorem fold_cons {k : K} {s : Finset K} (hks : k ∉ s) (hs : s.Nonempty) (f : K → E) :
    fold (Finset.cons k s hks) (Finset.cons_nonempty hks) f = f k ⋓ fold s hs f := by
  show ofAlg ((Finset.cons k s hks).sup' _ _) = _
  rw [Finset.sup'_cons (H := hs)]
  rfl

/-! ### The fold under the strengthened theories

Under `T♭` the fold is the **least upper bound** of `f '' u` in the domain order,
and under `T♯` it is the **greatest lower bound**. Under `T♮` it is neither, which
is the whole difficulty of the convex case. -/

end Semilattice

variable {u : Finset K} {f : K → E}

section Lower

variable [IsLower E]

theorem le_fold_of_mem {k : K} (hk : k ∈ u) (hu : u.Nonempty) :
    f k ≤ fold u hu f := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton a => rw [Finset.mem_singleton] at hk; subst hk; exact le_rfl
  | cons a s has hs ih =>
      rw [fold_cons has hs]
      rcases Finset.mem_cons.mp hk with rfl | hk'
      · exact left_le_op _ _
      · exact le_trans (ih hk') (right_le_op _ _)

theorem fold_le_of_forall (hu : u.Nonempty) {e : E} (h : ∀ k ∈ u, f k ≤ e) :
    fold u hu f ≤ e := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton a => exact h a (Finset.mem_singleton_self a)
  | cons a s has hs ih =>
      rw [fold_cons has hs]
      exact op_le (h a (Finset.mem_cons_self a s))
        (ih fun b hb => h b (Finset.mem_cons_of_mem hb))

end Lower

section Upper

variable [IsUpper E]

theorem fold_le_of_mem {k : K} (hk : k ∈ u) (hu : u.Nonempty) :
    fold u hu f ≤ f k := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton a => rw [Finset.mem_singleton] at hk; subst hk; exact le_rfl
  | cons a s has hs ih =>
      rw [fold_cons has hs]
      rcases Finset.mem_cons.mp hk with rfl | hk'
      · exact op_le_left _ _
      · exact le_trans (op_le_right _ _) (ih hk')

theorem le_fold_of_forall (hu : u.Nonempty) {e : E} (h : ∀ k ∈ u, e ≤ f k) :
    e ≤ fold u hu f := by
  induction hu using Finset.Nonempty.cons_induction with
  | singleton a => exact h a (Finset.mem_singleton_self a)
  | cons a s has hs ih =>
      rw [fold_cons has hs]
      exact le_op (h a (Finset.mem_cons_self a s))
        (ih fun b hb => h b (Finset.mem_cons_of_mem hb))

end Upper

end Fold

/-! ## 3. The fold is monotone for each of the three pre-orders

The three orderings of §5.2, on finite non-empty sets of compacts, are

* `u ⊑♭ v` — the **Hoare** conjunct, `∀ a ∈ u, ∃ b ∈ v, a ⊑ b`;
* `u ⊑♯ v` — the **Smyth** conjunct, `∀ b ∈ v, ∃ a ∈ u, a ⊑ b`;
* `u ⊑♮ v` — **Egli–Milner**, both conjuncts.

Each of the three statements below is what makes the fold descend to the ideal
completion of that pre-order. The theory needed goes up as the ordering gets
weaker: `T♭` for one conjunct, `T♯` for the other, and `T♮` alone once both are
present. -/

section FoldMono

variable {K : Type u} [Preorder K] {E : Type u} [CompletePartialOrder E] [Binop E]
variable {u v : Finset K} {f : K → E}

section Hoare

variable [IsLower E]

/-- **Hoare.** One conjunct, and `T♭`: the fold is the join, so it is below
`fold v` as soon as every `f a` is, and each `f a` is below some `f b ≤ fold v`. -/
theorem fold_le_fold_of_hoare (hu : u.Nonempty) (hv : v.Nonempty)
    (hf : Monotone f) (h : ∀ a ∈ u, ∃ b ∈ v, a ≤ b) :
    fold u hu f ≤ fold v hv f := by
  refine fold_le_of_forall hu fun a ha => ?_
  obtain ⟨b, hb, hab⟩ := h a ha
  exact le_trans (hf hab) (le_fold_of_mem hb hv)

end Hoare

section Smyth

variable [IsUpper E]

/-- **Smyth.** The other conjunct, and `T♯`: the fold is the meet, so it suffices
that it lies below each `f b`, and `fold u ≤ f a ≤ f b` for the witness `a`. -/
theorem fold_le_fold_of_smyth (hu : u.Nonempty) (hv : v.Nonempty)
    (hf : Monotone f) (h : ∀ b ∈ v, ∃ a ∈ u, a ≤ b) :
    fold u hu f ≤ fold v hv f := by
  refine le_fold_of_forall hv fun b hb => ?_
  obtain ⟨a, ha, hab⟩ := h b hb
  exact le_trans (fold_le_of_mem ha hu) (hf hab)

end Smyth

section Convex

variable [IsSemilattice E]

/-- **Egli–Milner, under `T♮` alone.** Neither of the two arguments above is
available: without `4♯` or `4♭` the operation `⋓` has no relation at all to the
domain order beyond monotonicity. The proof is instead the following chain, in
which `φ` is a choice of Hoare witness and `ψ` a choice of Smyth witness:

    fold u f = fold u f ⋓ fold (ψ '' v) f       (ψ '' v ⊆ u, so the union is u)
             = fold u f ⋓ fold v (f ∘ ψ)        (fold over an image)
             ⊑ fold u (f ∘ φ) ⋓ fold v f        (f a ⊑ f (φ a), f (ψ b) ⊑ f b)
             = fold (φ '' u) f ⋓ fold v f
             = fold v f                         (φ '' u ⊆ v, so the union is v)

Idempotence is spent twice, in the two `union_eq` steps; associativity and
commutativity are spent inside `fold_union`; and monotonicity of `⋓` is spent in
the middle step. -/
theorem fold_le_fold_of_convex (hu : u.Nonempty) (hv : v.Nonempty)
    (hf : Monotone f) (h₁ : ∀ a ∈ u, ∃ b ∈ v, a ≤ b) (h₂ : ∀ b ∈ v, ∃ a ∈ u, a ≤ b) :
    fold u hu f ≤ fold v hv f := by
  classical
  haveI : Nonempty K := ⟨hu.choose⟩
  choose! φ hφmem hφle using h₁
  choose! ψ hψmem hψle using h₂
  -- `ψ '' v ⊆ u` and `φ '' u ⊆ v`, so the two unions collapse.
  have hψsub : v.image ψ ⊆ u := Finset.image_subset_iff.mpr hψmem
  have hφsub : u.image φ ⊆ v := Finset.image_subset_iff.mpr hφmem
  have hune : u ∪ v.image ψ = u := Finset.union_eq_left.mpr hψsub
  have hvne : u.image φ ∪ v = v := Finset.union_eq_right.mpr hφsub
  -- `fold u f = fold u f ⋓ fold v (f ∘ ψ)`, because `u ∪ ψ '' v = u`.
  have hleft : fold u hu f = fold u hu f ⋓ fold v hv (f ∘ ψ) := by
    rw [← fold_image hv ψ f, ← fold_union hu (hv.image ψ) f]
    exact (fold_congr hune _ hu f).symm
  -- `fold v f = fold u (f ∘ φ) ⋓ fold v f`, because `φ '' u ∪ v = v`.
  have hright : fold u hu (f ∘ φ) ⋓ fold v hv f = fold v hv f := by
    rw [← fold_image hu φ f, ← fold_union (hu.image φ) hv f]
    exact fold_congr hvne _ hv f
  rw [hleft, ← hright]
  refine op_mono ?_ ?_
  · exact fold_le_fold hu fun a ha => hf (hφle a ha)
  · exact fold_le_fold hv fun b hb => hf (hψle b hb)

end Convex

end FoldMono

/-! ## 4. The universal property of the ideal completion

The paper's *"This function has a unique continuous extension to all of `D♮`
given by `ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}"* is a statement about ideal
completions and nothing else: it mentions neither `⋓` nor the axioms. It is
proved here in that generality, for an arbitrary pre-order `A` with a least
element and an arbitrary cpo `E`.

`idealExtend g I = ⨆ (g '' I)` is the unique Scott-continuous map
`IdealCompletion A → E` sending each principal ideal `↓a` to `g a`, for any
monotone `g : A → E`. Theorem 12 then reduces to producing the right `g` — the
fold — and checking that it is a homomorphism. -/

section IdealExtension

open IdealCompletion

variable {A : Type u} [Preorder A] {E : Type u} [CompletePartialOrder E]
variable {g : A → E}

/-- The principal ideals of the members of `I` form a directed family. -/
theorem directedOn_principal_image (I : IdealCompletion A) :
    DirectedOn (· ≤ ·) ((principal : A → IdealCompletion A) '' (I : Set A)) := by
  rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
  obtain ⟨c, hc, hac, hbc⟩ := I.directed a ha b hb
  exact ⟨principal c, Set.mem_image_of_mem _ hc, principal_mono hac, principal_mono hbc⟩

/-- **Every ideal is the least upper bound of its principal ideals.** This is the
sentence "`ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}`" reading in the other direction, and
it is what forces uniqueness. -/
theorem isLUB_principal_image (I : IdealCompletion A) :
    IsLUB ((principal : A → IdealCompletion A) '' (I : Set A)) I := by
  refine ⟨?_, fun J hJ a ha => ?_⟩
  · rintro _ ⟨a, ha, rfl⟩
    exact principal_le_iff.mpr ha
  · exact principal_le_iff.mp (hJ (Set.mem_image_of_mem _ ha))

theorem directedOn_image_of_monotone (hg : Monotone g) (I : IdealCompletion A) :
    DirectedOn (· ≤ ·) (g '' (I : Set A)) := by
  rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
  obtain ⟨c, hc, hac, hbc⟩ := I.directed a ha b hb
  exact ⟨g c, Set.mem_image_of_mem _ hc, hg hac, hg hbc⟩

/-- **The extension of the paper's hint**: `ext(f)(s) = ⨆{ext(f)(û) | u ∈ s}`. -/
noncomputable def idealExtend (g : A → E) (I : IdealCompletion A) : E :=
  sSup (g '' (I : Set A))

theorem isLUB_idealExtend (hg : Monotone g) (I : IdealCompletion A) :
    IsLUB (g '' (I : Set A)) (idealExtend g I) :=
  (directedOn_image_of_monotone hg I).isLUB_sSup

/-- The extension **agrees with `g` on the principal ideals** — the paper's
`ext(f)(û) = f(x₁) ⋓ ⋯ ⋓ f(xₙ)`. -/
@[simp] theorem idealExtend_principal (hg : Monotone g) (a : A) :
    idealExtend g (principal a) = g a :=
  (isLUB_idealExtend hg (principal a)).unique
    ⟨by rintro _ ⟨b, hb, rfl⟩; exact hg hb, fun e he => he ⟨a, mem_principal_self a, rfl⟩⟩

theorem monotone_idealExtend (hg : Monotone g) : Monotone (idealExtend g) := by
  intro I J hIJ
  exact (isLUB_idealExtend hg I).2 fun _ ⟨a, ha, hae⟩ =>
    hae ▸ (isLUB_idealExtend hg J).1 ⟨a, hIJ ha, rfl⟩

variable [OrderBot A]

/-- **The extension is continuous.** The only fact used about a directed family of
ideals is that its least upper bound has the union as its underlying set, which is
`IdealCompletion.mem_sSup_iff`. -/
theorem scottContinuous_idealExtend (hg : Monotone g) :
    ScottContinuous (idealExtend g) := by
  intro S hne hd I hI
  have hIS : I = sSup S := hI.unique hd.isLUB_sSup
  refine ⟨?_, fun e he => (isLUB_idealExtend hg I).2 ?_⟩
  · rintro _ ⟨J, hJ, rfl⟩
    exact monotone_idealExtend hg (hI.1 hJ)
  · rintro _ ⟨a, ha, rfl⟩
    rw [hIS] at ha
    obtain ⟨J, hJ, haJ⟩ := (mem_sSup_iff hne hd).mp ha
    exact le_trans ((isLUB_idealExtend hg J).1 ⟨a, haJ, rfl⟩) (he ⟨J, hJ, rfl⟩)

omit [OrderBot A] in
/-- **Uniqueness.** A continuous map agreeing with `g` on every principal ideal is
`idealExtend g`: apply continuity to the directed family `{↓a | a ∈ I}`, whose
least upper bound is `I`. -/
theorem eq_idealExtend (hg : Monotone g) {h : IdealCompletion A → E}
    (hc : ScottContinuous h) (hp : ∀ a : A, h (principal a) = g a) :
    h = idealExtend g := by
  funext I
  have himg : h '' ((principal : A → IdealCompletion A) '' (I : Set A)) = g '' (I : Set A) := by
    ext e
    constructor
    · rintro ⟨_, ⟨a, ha, rfl⟩, rfl⟩
      exact ⟨a, ha, (hp a).symm⟩
    · rintro ⟨a, ha, rfl⟩
      exact ⟨principal a, ⟨a, ha, rfl⟩, hp a⟩
  have := hc (I.nonempty.image _) (directedOn_principal_image I) (isLUB_principal_image I)
  rw [himg] at this
  exact this.unique (isLUB_idealExtend hg I)

end IdealExtension

end ScottDomains.ContinuousAlgebra
