import ScottDomains.Domain
import Mathlib.Order.Ideal
import Mathlib.Order.Bounds.OrderIso

/-!
# Theorem 11: the ideal completion

Gunter & Scott, *Semantic Domains* (Handbook of Theoretical Computer Science
Vol. B, 1990), §5.2, quoted from the source PDF rather than paraphrased:

> **Definition:** An ideal over a pre-order `⟨A, ⊢⟩` is a subset `s ⊆ A` such that
> 1. if `u ⊆ s` is finite, then there is an `x ∈ s` such that `x ⊢ y` for each `y ∈ u`, and
> 2. if `x ∈ s` and `x ⊢ y`, then `y ∈ s`.
>
> In short, an ideal is a subset which is directed and downward closed. If `x ∈ A`
> for a pre-order `A`, then the set `↓x = {y ∈ A | x ⊢ y}` is an ideal called the
> **principal ideal** generated by `x`.

> **Theorem 11** Given a countable pre-order `⟨A, ⊢⟩`, let `D` be the poset consisting
> of the ideals over `A`, ordered by set inclusion. If there is an element `⊥ ∈ A`
> such that `x ⊢ ⊥` for each `x ∈ A`, then `D` is a domain and `K(D)` is the set of
> principal ideals over `A`.

## Orientation of `⊢`

The paper writes `a ⊢ b` for "`a` is larger than `b`" (its own sentence: *it is
conventional to think of the relation `a ⊢ b` as indicating that `a` is "larger"
than `b`*). Mathlib writes the same relation as `b ≤ a`. Every statement below
uses Mathlib's orientation, so the paper's `↓x = {y | x ⊢ y}` is `Set.Iic x`, and
the paper's `⊥` with `x ⊢ ⊥` for all `x` is Mathlib's `OrderBot`.

## What is reused and what is built

`Order.Ideal A` (`Mathlib/Order/Ideal.lean`) is *exactly* the paper's definition —
`LowerSet` plus `nonempty'` plus `directed'` — so it is reused wholesale, together
with its `SetLike` instance, its `principal`, its `OrderBot`, and the union lemma
`Order.isIdeal_sUnion_of_directedOn`. What Mathlib does not have is the
order-theoretic content of Theorem 11: `Order.Ideal A` carries a `CompleteLattice`
only when `A` is a `SemilatticeSup` with a bottom, and nothing identifies its
compact elements or proves it algebraic.

`IdealCompletion A` is therefore a type synonym for `Order.Ideal A` rather than a
new structure. The synonym is not decoration: declaring
`SupSet (Order.Ideal A)` at `[Preorder A] [OrderBot A]` would collide with
Mathlib's `CompleteLattice (Order.Ideal P)` instance whenever `A` happens to be a
`SemilatticeSup` with a bottom, and the two `sSup`s are not definitionally equal
— Mathlib's is built by closure under the finite joins a `SemilatticeSup`
supplies, this one by the intersection `genIdeal` behind a `dite`. Two non-defeq
`SupSet` instances on one type is a latent incoherence, so the synonym keeps them
apart.

## What `idealSup` branches on (r0032)

`SupSet` is total, so `idealSup` must answer on every family of ideals and some
case split is forced. It branches on **the ideal generated by the family being an
ideal** — `Order.IsIdeal (genIdeal S)`, the membership condition for the value the
constructor consumes — and not on any merely *sufficient* condition for it.

An earlier version branched on `Order.IsIdeal (⋃₀ S)`, the union being an ideal.
That is the condition under which the *union* is the least upper bound, and the
union is the least upper bound only on a **directed** family. On a merely
**bounded** family the least upper bound is the ideal generated by the union, so
the old guard failed and `sSup` returned `⊥` — not even an upper bound. That made
`BoundedComplete` false for every powerdomain, which the kernel confirmed in
r0031 with the witness `P N`: the compacts `{0}` and `{1}` are incomparable, the
pair of principal ideals `↓{{0}}`, `↓{{1}}` is bounded above by `↓{{0,1}}`, and
their union is not directed. `ScottHom`'s module docstring records the identical
defect and repair for the function space (r0006–r0011), and `Smash.lean`'s section
"What `smashSup` branches on (r0027)" for the smash product; this is the third
instance of the one class.

The repair is conservative: `coe_idealSup_of_isIdeal`, `mem_sSup_iff` and
`idealSup_empty` below are unchanged in statement, because
`genIdeal_eq_sUnion_of_isIdeal` proves the new guard's value equals the old one's
wherever the old guard held. `instCompletePartialOrder`'s `lubOfDirected` proof
therefore needed no change at all.

## Statements

* `thm11` — for a countable pre-order with a least element, `IdealCompletion A` is
  a `Domain` and `compacts (IdealCompletion A) = Set.range principal`.
* `thm11_converse` — every domain `D` is order-isomorphic to the ideal completion
  of its own basis `K(D)`, by an isomorphism that also preserves directed suprema
  (so it is an isomorphism of cpos, not merely of posets).
* `boundedComplete` — if bounded pairs of `A` have least upper bounds then
  `IdealCompletion A` is bounded complete, `sSup` included.
-/

namespace ScottDomains

universe u

/-- The **ideal completion** of a pre-order `A`: the poset of ideals over `A`
ordered by set inclusion (Gunter & Scott §5.2). A type synonym for
`Order.Ideal A`; see the module docstring for why it is not a bare abbreviation. -/
def IdealCompletion (A : Type u) [LE A] : Type u := Order.Ideal A

namespace IdealCompletion

variable {A : Type u}

/-! ### Transfer of the `Order.Ideal` interface -/

section LE

variable [LE A]

/-- The underlying `Order.Ideal`. -/
def toIdeal (I : IdealCompletion A) : Order.Ideal A := I

/-- Read an `Order.Ideal` as a point of the ideal completion. -/
def ofIdeal (I : Order.Ideal A) : IdealCompletion A := I

@[simp] theorem toIdeal_ofIdeal (I : Order.Ideal A) : toIdeal (ofIdeal I) = I := rfl

@[simp] theorem ofIdeal_toIdeal (I : IdealCompletion A) : ofIdeal (toIdeal I) = I := rfl

instance : SetLike (IdealCompletion A) A where
  coe I := (I.toIdeal : Set A)
  coe_injective _ _ h := SetLike.coe_injective (A := Order.Ideal A) h

/-- Inclusion of ideals, the paper's order on `D`. -/
instance : PartialOrder (IdealCompletion A) := .ofSetLike (IdealCompletion A) A

@[simp] theorem mem_toIdeal {a : A} {I : IdealCompletion A} : a ∈ I.toIdeal ↔ a ∈ I := Iff.rfl

@[simp] theorem mem_ofIdeal {a : A} {I : Order.Ideal A} : a ∈ ofIdeal I ↔ a ∈ I := Iff.rfl

@[ext] theorem ext {I J : IdealCompletion A} (h : ∀ a, a ∈ I ↔ a ∈ J) : I = J := SetLike.ext h

theorem le_iff_subset {I J : IdealCompletion A} : I ≤ J ↔ (I : Set A) ⊆ (J : Set A) := Iff.rfl

/-- Clause 2 of the paper's definition: an ideal is downward closed. -/
protected theorem lower (I : IdealCompletion A) : IsLowerSet (I : Set A) := I.toIdeal.lower

protected theorem nonempty (I : IdealCompletion A) : (I : Set A).Nonempty := I.toIdeal.nonempty

/-- Clause 1 of the paper's definition, in its binary form: an ideal is directed. -/
protected theorem directed (I : IdealCompletion A) :
    DirectedOn (· ≤ ·) (I : Set A) := I.toIdeal.directed

protected theorem isIdeal (I : IdealCompletion A) :
    Order.IsIdeal (I : Set A) := I.toIdeal.isIdeal

/-! ### The ideal generated by a family

The least upper bound of a family of ideals is not the union of the family but
the ideal *generated by* that union; the two coincide only when the family is
directed. `genIdeal` names the generated set as the intersection of every ideal
lying above the family — a comprehension, not a closure under finite joins,
because a bare pre-order has no finite joins to close under. Joins of *bounded*
pairs are all the construction ever needs, and they enter in `isIdeal_genIdeal`
below. -/

/-- The **ideal generated by a family of ideals** `S`: the intersection of every
ideal that lies above all of `S`. It is the least upper bound of `S` in the
poset of ideals whenever it is an ideal at all. -/
def genIdeal (S : Set (IdealCompletion A)) : Set A :=
  {c | ∀ K : IdealCompletion A, (∀ I ∈ S, I ≤ K) → c ∈ K}

theorem mem_genIdeal {S : Set (IdealCompletion A)} {c : A} :
    c ∈ genIdeal S ↔ ∀ K : IdealCompletion A, (∀ I ∈ S, I ≤ K) → c ∈ K := Iff.rfl

/-- `genIdeal S` is an upper bound of `S`: each member of the family lies in
every ideal above the family, hence in the intersection. -/
theorem subset_genIdeal {S : Set (IdealCompletion A)} {I : IdealCompletion A} (hI : I ∈ S) :
    (I : Set A) ⊆ genIdeal S := fun _ ha _ hK => hK I hI ha

/-- `genIdeal S` is the *least* upper bound: any ideal above the family is one of
the sets being intersected. -/
theorem genIdeal_subset {S : Set (IdealCompletion A)} {K : IdealCompletion A}
    (hK : ∀ I ∈ S, I ≤ K) : genIdeal S ⊆ (K : Set A) := fun _ hc => hc K hK

theorem sUnion_subset_genIdeal {S : Set (IdealCompletion A)} :
    ⋃₀ (SetLike.coe '' S) ⊆ genIdeal S := by
  rintro x ⟨_, ⟨I, hI, rfl⟩, hx⟩
  exact subset_genIdeal hI hx

/-- **The generated ideal agrees with the union exactly where the union is an
ideal.** This is what makes the r0032 repair of `idealSup` conservative: on a
nonempty directed family `isIdeal_sUnion` discharges the hypothesis, so the new
guard's value is the old guard's value and every lemma stated against `⋃₀`
survives verbatim. -/
theorem genIdeal_eq_sUnion_of_isIdeal {S : Set (IdealCompletion A)}
    (h : Order.IsIdeal (⋃₀ (SetLike.coe '' S))) :
    genIdeal S = ⋃₀ (SetLike.coe '' S) := by
  refine Set.Subset.antisymm ?_ sUnion_subset_genIdeal
  exact genIdeal_subset (K := ofIdeal h.toIdeal)
    fun I hI _ ha => ⟨(I : Set A), Set.mem_image_of_mem _ hI, ha⟩

end LE

/-! ### Principal ideals -/

section Preorder

variable [Preorder A]

/-- `↓a`, the principal ideal generated by `a`. -/
def principal (a : A) : IdealCompletion A := ofIdeal (Order.Ideal.principal a)

@[simp] theorem mem_principal {a b : A} : a ∈ principal b ↔ a ≤ b := Iff.rfl

theorem mem_principal_self (a : A) : a ∈ principal a := le_rfl

@[simp] theorem principal_le_iff {a : A} {I : IdealCompletion A} : principal a ≤ I ↔ a ∈ I :=
  ⟨fun h => h (mem_principal_self a), fun ha _ hb => I.lower hb ha⟩

theorem principal_mono {a b : A} (h : a ≤ b) : principal a ≤ principal b :=
  fun _ hx => le_trans hx h

end Preorder

/-! ### The cpo structure

`sSup` is total, so it must be defined on every set of ideals, while the ideal
generated by an arbitrary family need not be an ideal — in a bare pre-order a
pair of members of `genIdeal S` need not have an upper bound in it. The `dite`
therefore branches on `Order.IsIdeal (genIdeal …)` — exactly the proposition the
constructor consumes — and falls back to `⊥` otherwise. `lubOfDirected` then
holds on the nose for the empty set too: `genIdeal ∅ = ↓⊥`, so `sSup ∅ = ⊥`,
which is what `CompletePartialOrder` demands. -/

section Bot

variable [Preorder A] [OrderBot A]

/-- Every ideal contains `⊥` (the paper's `x ⊢ ⊥` for all `x`), so `↓⊥` is the
least ideal. -/
theorem bot_mem (I : IdealCompletion A) : (⊥ : A) ∈ I := Order.Ideal.bot_mem I.toIdeal

instance : OrderBot (IdealCompletion A) where
  bot := principal ⊥
  bot_le I _ ha := I.lower ha (bot_mem I)

@[simp] theorem bot_eq_principal : (⊥ : IdealCompletion A) = principal ⊥ := rfl

open Classical in
/-- The candidate least upper bound: the ideal **generated by** the family when
that generated set is an ideal, and `⊥` otherwise. See the module docstring for
why the guard is `Order.IsIdeal (genIdeal S)` and not `Order.IsIdeal (⋃₀ S)`. -/
noncomputable def idealSup (S : Set (IdealCompletion A)) : IdealCompletion A :=
  if h : Order.IsIdeal (genIdeal S) then ofIdeal h.toIdeal else ⊥

noncomputable instance : SupSet (IdealCompletion A) := ⟨idealSup⟩

theorem sSup_eq_idealSup (S : Set (IdealCompletion A)) : sSup S = idealSup S := rfl

/-- The defining equation of `idealSup` on the positive branch. -/
theorem coe_idealSup_of_isIdeal_genIdeal {S : Set (IdealCompletion A)}
    (h : Order.IsIdeal (genIdeal S)) : (idealSup S : Set A) = genIdeal S := by
  classical
  simp only [idealSup, dif_pos h]
  rfl

/-- **`idealSup` computes the least upper bound whenever its guard holds.** Upper
bound by `subset_genIdeal`, least by `genIdeal_subset` — the two halves of
`genIdeal` being the generated ideal. Everything else about bounded completeness
below is this lemma plus a proof that the guard holds. -/
theorem isLUB_idealSup_of_isIdeal_genIdeal {S : Set (IdealCompletion A)}
    (h : Order.IsIdeal (genIdeal S)) : IsLUB S (idealSup S) := by
  constructor
  · intro I hI a ha
    rw [← SetLike.mem_coe, coe_idealSup_of_isIdeal_genIdeal h]
    exact subset_genIdeal hI ha
  · intro K hK a ha
    rw [← SetLike.mem_coe, coe_idealSup_of_isIdeal_genIdeal h] at ha
    exact genIdeal_subset (fun _ hI => hK hI) ha

/-- Retained verbatim across the r0032 repair: where the union is an ideal it is
the generated ideal (`genIdeal_eq_sUnion_of_isIdeal`), so `idealSup` still
computes the union there. -/
theorem coe_idealSup_of_isIdeal {S : Set (IdealCompletion A)}
    (h : Order.IsIdeal (⋃₀ (SetLike.coe '' S))) :
    (idealSup S : Set A) = ⋃₀ (SetLike.coe '' S) := by
  have hg : Order.IsIdeal (genIdeal S) := by
    rw [genIdeal_eq_sUnion_of_isIdeal h]; exact h
  rw [coe_idealSup_of_isIdeal_genIdeal hg, genIdeal_eq_sUnion_of_isIdeal h]

omit [OrderBot A] in
/-- The union of a nonempty directed family of ideals is an ideal — the first
paragraph of the paper's proof, and `Order.isIdeal_sUnion_of_directedOn` verbatim
once the family is transported along `SetLike.coe`. -/
theorem isIdeal_sUnion {S : Set (IdealCompletion A)} (hne : S.Nonempty)
    (hd : DirectedOn (· ≤ ·) S) : Order.IsIdeal (⋃₀ (SetLike.coe '' S)) := by
  refine Order.isIdeal_sUnion_of_directedOn ?_ ?_ (hne.image _)
  · rintro _ ⟨I, _, rfl⟩
    exact I.isIdeal
  · rintro _ ⟨I, hI, rfl⟩ _ ⟨J, hJ, rfl⟩
    obtain ⟨K, hK, hIK, hJK⟩ := hd I hI J hJ
    exact ⟨(K : Set A), Set.mem_image_of_mem _ hK, hIK, hJK⟩

theorem mem_sSup_iff {S : Set (IdealCompletion A)} (hne : S.Nonempty)
    (hd : DirectedOn (· ≤ ·) S) {a : A} : a ∈ sSup S ↔ ∃ I ∈ S, a ∈ I := by
  rw [← SetLike.mem_coe, sSup_eq_idealSup, coe_idealSup_of_isIdeal (isIdeal_sUnion hne hd)]
  constructor
  · rintro ⟨_, ⟨I, hI, rfl⟩, ha⟩
    exact ⟨I, hI, ha⟩
  · rintro ⟨I, hI, ha⟩
    exact ⟨(I : Set A), Set.mem_image_of_mem _ hI, ha⟩

/-- The generated ideal of the empty family is `↓⊥`: every ideal is vacuously
above `∅`, and the intersection of all ideals is `↓⊥` because each contains `⊥`
and is downward closed. -/
theorem genIdeal_empty :
    genIdeal (∅ : Set (IdealCompletion A)) = ((⊥ : IdealCompletion A) : Set A) := by
  refine Set.Subset.antisymm (genIdeal_subset fun I hI => absurd hI (Set.notMem_empty I)) ?_
  intro a ha K _
  exact K.lower (show a ≤ (⊥ : A) from ha) (bot_mem K)

theorem isIdeal_genIdeal_empty :
    Order.IsIdeal (genIdeal (∅ : Set (IdealCompletion A))) := by
  rw [genIdeal_empty]
  exact (⊥ : IdealCompletion A).isIdeal

/-- Retained verbatim across the r0032 repair, by a different route: the old
guard failed on `∅` (the empty union is not an ideal) and the negative branch
gave `⊥`; the new guard *holds* on `∅` and the positive branch gives `↓⊥`, which
is `⊥`. -/
theorem idealSup_empty : idealSup (∅ : Set (IdealCompletion A)) = ⊥ := by
  apply SetLike.coe_injective
  rw [coe_idealSup_of_isIdeal_genIdeal isIdeal_genIdeal_empty, genIdeal_empty]

noncomputable instance : CompletePartialOrder (IdealCompletion A) :=
  { (inferInstance : PartialOrder (IdealCompletion A)),
    (inferInstance : SupSet (IdealCompletion A)),
    (inferInstance : OrderBot (IdealCompletion A)) with
    lubOfDirected := by
      intro S hd
      rcases S.eq_empty_or_nonempty with rfl | hne
      · rw [sSup_eq_idealSup, idealSup_empty]
        exact ⟨fun _ h => absurd h (Set.notMem_empty _), fun _ _ => bot_le⟩
      · refine ⟨fun I hI a ha => (mem_sSup_iff hne hd).mpr ⟨I, hI, ha⟩, fun J hJ a ha => ?_⟩
        obtain ⟨I, hI, ha⟩ := (mem_sSup_iff hne hd).mp ha
        exact hJ hI ha }

/-! ### Bounded completeness

The ideal completion inherits bounded completeness from the pre-order, and the
only input it consumes is least upper bounds of **bounded pairs** of `A` — no
finite joins, no transfinite construction. -/

/-- **`genIdeal S` is an ideal whenever `S` is bounded above and bounded pairs of
`A` have least upper bounds.**

Lower-closedness and non-emptiness are free. Directedness is the whole content,
and it is where boundedness is spent: two members `a, b` of `genIdeal S` lie in
the bounding ideal `J`, which is directed, so `{a, b}` is bounded in `A` and has
a least upper bound `c`; and `c` lies in every ideal `K` above `S`, since `K`
already bounds the pair by some `e ∈ K` and `c ≤ e`, so `c ∈ K` by downward
closure. -/
theorem isIdeal_genIdeal
    (hpair : ∀ a b : A, BddAbove ({a, b} : Set A) → ∃ c, IsLUB ({a, b} : Set A) c)
    {S : Set (IdealCompletion A)} (hS : BddAbove S) : Order.IsIdeal (genIdeal S) := by
  obtain ⟨J, hJ⟩ := hS
  have hmemJ : ∀ c ∈ genIdeal S, c ∈ J := fun _ hc => hc J fun _ hI => hJ hI
  refine ⟨?_, ⟨⊥, ?_⟩, ?_⟩
  · intro a b hba ha K hK
    exact K.lower hba (ha K hK)
  · intro K _
    exact bot_mem K
  · intro a ha b hb
    obtain ⟨d, hd, had, hbd⟩ := J.directed a (hmemJ a ha) b (hmemJ b hb)
    obtain ⟨c, hc⟩ := hpair a b ⟨d, by rintro x (rfl | rfl) <;> assumption⟩
    refine ⟨c, ?_, hc.1 (Set.mem_insert a {b}), hc.1 (Set.mem_insert_of_mem a rfl)⟩
    intro K hK
    obtain ⟨e, he, hae, hbe⟩ := K.directed a (ha K hK) b (hb K hK)
    exact K.lower (hc.2 (by rintro x (rfl | rfl) <;> assumption)) he

/-- **Every bounded family of ideals has a least upper bound, and `sSup`
computes it**, provided bounded pairs of the pre-order have least upper bounds.
Together with the `OrderBot` instance this is the paper's *bounded complete*
(§4.5) in the class-valued form `Domain.lean` states. -/
theorem boundedComplete
    (hpair : ∀ a b : A, BddAbove ({a, b} : Set A) → ∃ c, IsLUB ({a, b} : Set A) c) :
    BoundedComplete (IdealCompletion A) where
  isLUB_sSup_of_bddAbove _ hS := isLUB_idealSup_of_isIdeal_genIdeal (isIdeal_genIdeal hpair hS)

/-! ### `K(D)` is the set of principal ideals -/

/-- A principal ideal is compact: if `↓a ⊆ ⋃M` for `M` directed, then `a` lies in
some `x ∈ M`, and then `↓a ⊆ x`. -/
theorem isCompactElement_principal (a : A) :
    IsCompactElement (principal a : IdealCompletion A) := by
  intro S u hne hd hlub hle
  rw [hlub.unique hd.isLUB_sSup] at hle
  obtain ⟨I, hI, ha⟩ := (mem_sSup_iff hne hd).mp (hle (mem_principal_self a))
  exact ⟨I, hI, principal_le_iff.mpr ha⟩

omit [OrderBot A] in
/-- Conversely a compact ideal is principal: `I` is the least upper bound of the
directed family `{↓a | a ∈ I}`, so compactness places `I` below one of them. -/
theorem exists_eq_principal_of_isCompactElement {I : IdealCompletion A}
    (h : IsCompactElement I) : ∃ a ∈ I, I = principal a := by
  have hne : ((principal : A → IdealCompletion A) '' (I : Set A)).Nonempty := I.nonempty.image _
  have hd : DirectedOn (· ≤ ·) ((principal : A → IdealCompletion A) '' (I : Set A)) := by
    rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
    obtain ⟨c, hc, hac, hbc⟩ := I.directed a ha b hb
    exact ⟨principal c, Set.mem_image_of_mem _ hc, principal_mono hac, principal_mono hbc⟩
  have hlub : IsLUB ((principal : A → IdealCompletion A) '' (I : Set A)) I := by
    refine ⟨?_, fun J hJ a ha => ?_⟩
    · rintro _ ⟨a, ha, rfl⟩
      exact principal_le_iff.mpr ha
    · exact principal_le_iff.mp (hJ (Set.mem_image_of_mem _ ha))
  obtain ⟨J, hJ, hIJ⟩ := h _ I hne hd hlub le_rfl
  obtain ⟨a, ha, rfl⟩ := hJ
  exact ⟨a, ha, le_antisymm hIJ (principal_le_iff.mpr ha)⟩

theorem isCompactElement_iff_exists_eq_principal {I : IdealCompletion A} :
    IsCompactElement I ↔ ∃ a, I = principal a :=
  ⟨fun h => (exists_eq_principal_of_isCompactElement h).imp fun _ h => h.2,
   by rintro ⟨a, rfl⟩; exact isCompactElement_principal a⟩

/-- The second half of Theorem 11's conclusion: `K(D)` is the set of principal
ideals over `A`. -/
theorem compacts_eq_range_principal :
    compacts (IdealCompletion A) = Set.range (principal : A → IdealCompletion A) :=
  Set.ext fun _ => isCompactElement_iff_exists_eq_principal.trans
    ⟨fun ⟨a, ha⟩ => ⟨a, ha.symm⟩, fun ⟨a, ha⟩ => ⟨a, ha.symm⟩⟩

/-! ### Algebraicity, and Theorem 11 -/

/-- The ideal completion is algebraic, with the principal ideals as basis: the
principal ideals below `I` are `{↓a | a ∈ I}`, which is directed because `I` is,
and whose union is `I`. -/
instance : IsAlgebraic (IdealCompletion A) where
  directedOn_compactsBelow I J hJ K hK := by
    obtain ⟨a, ha⟩ := isCompactElement_iff_exists_eq_principal.mp hJ.1
    obtain ⟨b, hb⟩ := isCompactElement_iff_exists_eq_principal.mp hK.1
    subst ha; subst hb
    obtain ⟨c, hc, hac, hbc⟩ :=
      I.directed a (principal_le_iff.mp hJ.2) b (principal_le_iff.mp hK.2)
    exact ⟨principal c, ⟨isCompactElement_principal c, principal_le_iff.mpr hc⟩,
      principal_mono hac, principal_mono hbc⟩
  isLUB_compactsBelow I := by
    refine ⟨fun J hJ => hJ.2, fun J hJ a ha => ?_⟩
    exact principal_le_iff.mp
      (hJ ⟨isCompactElement_principal a, principal_le_iff.mpr ha⟩)

/-- The ideal completion of a **countable** pre-order with a least element is a
domain: its basis is the range of `principal`, and a countable type has a
countable range. -/
instance instDomain [Countable A] : Domain (IdealCompletion A) where
  countable_compacts := by
    rw [compacts_eq_range_principal]
    exact Set.countable_range _

end Bot

/-- **Theorem 11** (Gunter & Scott §5.2), forward half. Given a countable
pre-order `⟨A, ⊢⟩` with an element `⊥` satisfying `x ⊢ ⊥` for every `x`, the poset
`D` of ideals over `A` under inclusion is a domain, and `K(D)` is the set of
principal ideals over `A`.

The paper's `x ⊢ ⊥ for each x ∈ A` is `[OrderBot A]` here — the same statement
with the least element named rather than merely asserted to exist. -/
theorem thm11 (A : Type u) [Preorder A] [OrderBot A] [Countable A] :
    Domain (IdealCompletion A) ∧
      compacts (IdealCompletion A) = Set.range (principal : A → IdealCompletion A) :=
  ⟨inferInstance, compacts_eq_range_principal⟩

/-! ### The converse: every domain is an ideal completion

The pre-order to complete is `K(D)` itself, as a subtype of `D`. It is a poset,
not merely a pre-order, and it has a least element because `⊥` is compact
(`isCompactElement_bot`). -/

section Converse

variable {D : Type u} [CompletePartialOrder D]

/-- `K(D)` has a least element: `⊥` is compact. -/
instance : OrderBot ↥(compacts D) where
  bot := ⟨⊥, isCompactElement_bot⟩
  bot_le _ := bot_le

/-- `K(D)` is countable when `D` is a domain — this is exactly the countability
condition in the paper's definition of *domain*, and it is what makes the ideal
completion of `K(D)` a domain again. -/
instance [Domain D] : Countable ↥(compacts D) := Domain.countable_compacts.to_subtype

variable [IsAlgebraic D]

theorem isIdeal_compactsBelow (x : D) :
    Order.IsIdeal {k : ↥(compacts D) | (k : D) ≤ x} := by
  refine ⟨fun a b hba ha => le_trans hba ha, ⟨⊥, bot_le⟩, ?_⟩
  rintro ⟨a, ha⟩ hax ⟨b, hb⟩ hbx
  obtain ⟨c, ⟨hc, hcx⟩, hac, hbc⟩ :=
    IsAlgebraic.directedOn_compactsBelow x a ⟨ha, hax⟩ b ⟨hb, hbx⟩
  exact ⟨⟨c, hc⟩, hcx, hac, hbc⟩

/-- `x ↦ {k ∈ K(D) | k ⊑ x}`, the ideal of compact approximants. -/
def idealOfElem (x : D) : IdealCompletion ↥(compacts D) :=
  ofIdeal (isIdeal_compactsBelow x).toIdeal

@[simp] theorem mem_idealOfElem {x : D} {k : ↥(compacts D)} :
    k ∈ idealOfElem x ↔ (k : D) ≤ x := Iff.rfl

omit [IsAlgebraic D] in
/-- The compact elements listed by an ideal form a directed subset of `D`. -/
theorem directedOn_val_image (I : IdealCompletion ↥(compacts D)) :
    DirectedOn (· ≤ ·) ((Subtype.val : ↥(compacts D) → D) '' (I : Set ↥(compacts D))) := by
  rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
  obtain ⟨c, hc, hac, hbc⟩ := I.directed a ha b hb
  exact ⟨(c : D), Set.mem_image_of_mem _ hc, hac, hbc⟩

/-- `I ↦ ⨆ I`, the least upper bound in `D` of the compact elements in `I`. -/
noncomputable def elemOfIdeal (I : IdealCompletion ↥(compacts D)) : D :=
  sSup ((Subtype.val : ↥(compacts D) → D) '' (I : Set ↥(compacts D)))

omit [IsAlgebraic D] in
theorem isLUB_elemOfIdeal (I : IdealCompletion ↥(compacts D)) :
    IsLUB ((Subtype.val : ↥(compacts D) → D) '' (I : Set ↥(compacts D))) (elemOfIdeal I) :=
  (directedOn_val_image I).isLUB_sSup

theorem val_image_idealOfElem (x : D) :
    (Subtype.val : ↥(compacts D) → D) '' (idealOfElem x : Set ↥(compacts D)) =
      compactsBelow x := by
  ext y
  constructor
  · rintro ⟨⟨k, hk⟩, hkx, rfl⟩
    exact ⟨hk, hkx⟩
  · rintro ⟨hk, hkx⟩
    exact ⟨⟨y, hk⟩, hkx, rfl⟩

theorem elemOfIdeal_idealOfElem (x : D) : elemOfIdeal (idealOfElem x) = x := by
  rw [elemOfIdeal, val_image_idealOfElem]
  exact ((IsAlgebraic.directedOn_compactsBelow x).isLUB_sSup).unique
    (IsAlgebraic.isLUB_compactsBelow x)

theorem idealOfElem_elemOfIdeal (I : IdealCompletion ↥(compacts D)) :
    idealOfElem (elemOfIdeal I) = I := by
  ext k
  rw [mem_idealOfElem]
  constructor
  · intro hk
    obtain ⟨_, ⟨j, hj, rfl⟩, hkj⟩ :=
      k.2 _ (elemOfIdeal I) (I.nonempty.image _) (directedOn_val_image I)
        (isLUB_elemOfIdeal I) hk
    exact I.lower (show k ≤ j from hkj) hj
  · intro hk
    exact (isLUB_elemOfIdeal I).1 (Set.mem_image_of_mem _ hk)

theorem idealOfElem_le_iff {x y : D} : idealOfElem x ≤ idealOfElem y ↔ x ≤ y := by
  constructor
  · intro h
    refine (IsAlgebraic.isLUB_compactsBelow x).2 ?_
    rintro c ⟨hc, hcx⟩
    exact h (show (⟨c, hc⟩ : ↥(compacts D)) ∈ idealOfElem x from hcx)
  · intro h _ hk
    exact le_trans hk h

/-- The order isomorphism of Theorem 11's converse half: `D ≃o` the ideal
completion of `K(D)`, by `x ↦ {k ∈ K(D) | k ⊑ x}` with inverse `I ↦ ⨆ I`. -/
noncomputable def orderIsoIdealCompletionCompacts : D ≃o IdealCompletion ↥(compacts D) where
  toFun := idealOfElem
  invFun := elemOfIdeal
  left_inv := elemOfIdeal_idealOfElem
  right_inv := idealOfElem_elemOfIdeal
  map_rel_iff' := idealOfElem_le_iff

@[simp] theorem orderIsoIdealCompletionCompacts_apply (x : D) :
    orderIsoIdealCompletionCompacts x = idealOfElem x := rfl

end Converse

/-- An order isomorphism between cpos preserves directed suprema, hence is an
isomorphism of cpos and not merely of posets. The argument is that an `OrderIso`
carries least upper bounds to least upper bounds (`OrderIso.isLUB_image'`), and a
cpo's `sSup` is pinned down on directed sets by `IsLUB.unique`. -/
theorem _root_.OrderIso.map_sSup_of_directedOn {α β : Type*} [CompletePartialOrder α]
    [CompletePartialOrder β] (e : α ≃o β) {s : Set α} (hs : DirectedOn (· ≤ ·) s) :
    e (sSup s) = sSup (e '' s) := by
  have hd : DirectedOn (· ≤ ·) (e '' s) := by
    rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
    obtain ⟨c, hc, hac, hbc⟩ := hs a ha b hb
    exact ⟨e c, Set.mem_image_of_mem _ hc, e.monotone hac, e.monotone hbc⟩
  exact (e.isLUB_image'.mpr hs.isLUB_sSup).unique hd.isLUB_sSup

/-- **Theorem 11** (Gunter & Scott §5.2), converse half: *every domain arises as
the ideal completion of a countable pre-order*, namely of its own basis `K(D)`.

"Isomorphic" is spelled out in the three conjuncts. The map is
(1) an **order isomorphism** `D ≃o IdealCompletion ↥(compacts D)`, which
(2) preserves every directed supremum, so it is also an isomorphism of **cpos**,
and (3) its codomain is again a `Domain` — for which the countability half of
`Domain D` is exactly what is spent, since it is what makes the pre-order `K(D)`
countable. -/
theorem thm11_converse (D : Type u) [CompletePartialOrder D] [Domain D] :
    ∃ e : D ≃o IdealCompletion ↥(compacts D),
      (∀ s : Set D, DirectedOn (· ≤ ·) s → e (sSup s) = sSup (e '' s)) ∧
        Domain (IdealCompletion ↥(compacts D)) :=
  ⟨orderIsoIdealCompletionCompacts, fun _ hs =>
    orderIsoIdealCompletionCompacts.map_sSup_of_directedOn hs, inferInstance⟩

/-! ### The construction is nondegenerate

`IdealCompletion ℕ` is the cheapest witness that the basis is a *proper* part of
the order: the principal ideals `↓n = Iic n` are compact, and the ideal `ℕ` itself
— directed because `ℕ` is, and trivially downward closed — is not principal,
hence not compact. Without such a check, `instIsAlgebraic` could be satisfied by a
mistaken characterization of `K(D)` in which every element is compact. -/

/-- All of `ℕ`, as an ideal over `ℕ`: directed by `max`, downward closed
vacuously. -/
def univIdealNat : IdealCompletion ℕ :=
  ofIdeal ⟨⟨Set.univ, fun _ _ _ _ => trivial⟩, ⟨0, trivial⟩,
    fun a _ b _ => ⟨max a b, trivial, Nat.le_max_left a b, Nat.le_max_right a b⟩⟩

example : Domain (IdealCompletion ℕ) := inferInstance

example : IsCompactElement (principal 3 : IdealCompletion ℕ) := isCompactElement_principal 3

example : ¬ IsCompactElement univIdealNat := by
  intro h
  obtain ⟨a, -, ha⟩ := exists_eq_principal_of_isCompactElement h
  have hmem : a + 1 ∈ univIdealNat := trivial
  rw [ha, mem_principal] at hmem
  exact Nat.not_succ_le_self a hmem

end IdealCompletion

end ScottDomains

/- Axiom audit, by `#print axioms` (run at r0032, then removed so the build emits
no `info` lines). Every declaration depends only on the three standard axioms;
none depends on `sorryAx`.

  ScottDomains.IdealCompletion.genIdeal                           [propext, Quot.sound]
  ScottDomains.IdealCompletion.genIdeal_eq_sUnion_of_isIdeal      [propext, Quot.sound]
  ScottDomains.IdealCompletion.idealSup                           [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.coe_idealSup_of_isIdeal_genIdeal   [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.isLUB_idealSup_of_isIdeal_genIdeal [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.coe_idealSup_of_isIdeal            [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.idealSup_empty                     [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.mem_sSup_iff                       [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.isIdeal_genIdeal                   [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.boundedComplete                    [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.thm11                              [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.thm11_converse                     [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.compacts_eq_range_principal        [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.isCompactElement_iff_exists_eq_principal
                                                                  [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.instCompletePartialOrder           [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.instIsAlgebraic                    [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.instDomain                         [propext, Classical.choice, Quot.sound]
  ScottDomains.IdealCompletion.orderIsoIdealCompletionCompacts    [propext, Quot.sound]
  OrderIso.map_sSup_of_directedOn                                 [propext, Quot.sound]

`Classical.choice` enters only through `idealSup`'s `dite` on
`Order.IsIdeal (genIdeal …)`, which is not a decidable predicate; `genIdeal`
itself and its agreement with the union are choice-free, as is the converse
half. -/
