import ScottDomains.EquilogicalSpaces.EquLimits
import Mathlib.CategoryTheory.Limits.Constructions.LimitsOfProductsAndEqualizers

/-!
# Theorem 3.10, the cocompleteness half: `Equ` is cocomplete

> On to coproducts. The coproduct of topological spaces is just a disjoint union
> of the underlying sets with the topology on the union generated by the union of
> all the topologies. For equivalence relations, we have only to note that the
> union of equivalence relations on disjoint sets is indeed an equivalence
> relation. …
>
> Next, we discuss coequalizers. … On `|ℱ|` we form the least equivalence
> relation containing both `≡_ℱ` and the set of pairs `{ (f(x), g(x)) | x ∈ |ℰ| }`.
> Using the same topological space as `ℱ` does and this equivalence relation, we
> form the equilogical space `𝒢`. … Thus, `Equ` is a cocomplete category.

Two points where the paper's wording is doing real work.

**"the union of equivalence relations on disjoint sets"** — disjointness is what
makes it an equivalence relation, and it is why `coprodRel` below is phrased with
*equations* `p = ⟨j, x⟩` rather than with a transport along an index equality.
The equations let `rintro` substitute, and transitivity then needs only the
injectivity of `Sigma.mk`.

**"the least equivalence relation containing"** — that is `Relation.EqvGen`, and
the universal property of the coequalizer is proved by induction over it. Note
the coequalizer keeps `ℱ`'s topology unchanged: *no topology is placed on the
quotient*, which the paper flags as one reason `Equ` is not equivalent to `Set`.
-/

universe u

namespace ScottDomains.EquilogicalSpaces

open CategoryTheory CategoryTheory.Limits

/-! ## Blocked: coproducts

    The disjoint union needs `T0Space (Σ j, (A j).carrier)`, and **Mathlib has no
    such instance** — searched `Mathlib/Topology`. The fact is true: two points in
    different summands are separated because each summand is open, and two in the
    same summand by that summand's own `T₀`. But it has to be proved, and it is
    genuine content rather than plumbing, so it is recorded here rather than
    stubbed.

    Everything about the *relation* on a disjoint union is unproblematic and was
    written before the obstacle surfaced: phrase it with equations
    `p = ⟨j, x⟩` rather than a transport along an index equality, and `rintro`
    substitutes, leaving transitivity to `Sigma.mk` injectivity. That is what the
    paper's "the union of equivalence relations on **disjoint** sets is indeed an
    equivalence relation" is doing.

    With coproducts owed, `has_colimits_of_hasCoequalizers_and_coproducts` cannot
    be applied and Theorem 3.10's cocompleteness half stays open. -/

/-! ## Coequalizers -/

/-- The relation of the coequalizer: the least equivalence relation containing
    `≡_ℬ` together with the pairs `(f a, g a)`. -/
def coeqRel {A B : EquilogicalSpace.{u}} (f g : Equivariant A B) :
    B.carrier → B.carrier → Prop :=
  Relation.EqvGen (fun x y => B.Rel x y ∨ ∃ a, x = f.toFun a ∧ y = g.toFun a)

/-- The coequalizer object: **the same space as `ℬ`**, with the relation
    coarsened. No topology is placed on a quotient. -/
def EquilogicalSpace.coeqObj {A B : EquilogicalSpace.{u}} (f g : Equivariant A B) :
    EquilogicalSpace.{u} where
  carrier := B.carrier
  setoid := ⟨coeqRel f g, Relation.EqvGen.is_equivalence _⟩

namespace EquilogicalSpace

/-- The quotient map is the identity on points. -/
def coeqProj {A B : EquilogicalSpace.{u}} (f g : Equivariant A B) :
    Equivariant B (coeqObj f g) where
  toFun := id
  continuous_toFun := continuous_id
  equivariant := fun h => Relation.EqvGen.rel _ _ (Or.inl h)

/-- It coequalizes: `f a` is identified with `g a` by a generator, and then `g`'s
    equivariance moves along the relation in `ℬ`. -/
theorem coeqProj_coequalizes {A B : EquilogicalSpace.{u}} (f g : Equivariant A B) :
    Equivariant.MapEquiv (Equivariant.comp (coeqProj f g) f)
      (Equivariant.comp (coeqProj f g) g) := fun x _ h =>
  Relation.EqvGen.trans _ _ _
    (Relation.EqvGen.rel _ _ (Or.inr ⟨x, rfl, rfl⟩))
    (Relation.EqvGen.rel _ _ (Or.inl (g.equivariant h)))

/-- Any map coequalizing `f` and `g` factors, by induction over `EqvGen`. -/
def coeqDesc {A B T : EquilogicalSpace.{u}} {f g : Equivariant A B}
    (t : Equivariant B T)
    (ht : Equivariant.MapEquiv (Equivariant.comp t f) (Equivariant.comp t g)) :
    Equivariant (coeqObj f g) T where
  toFun := t.toFun
  continuous_toFun := t.continuous_toFun
  equivariant := by
    intro x y h
    induction h with
    | rel a b hab =>
      rcases hab with hb | ⟨c, rfl, rfl⟩
      · exact t.equivariant hb
      · exact ht c c (A.setoid.refl c)
    | refl a => exact T.setoid.refl _
    | symm a b _ ih => exact T.setoid.symm ih
    | trans a b c _ _ ih₁ ih₂ => exact T.setoid.trans ih₁ ih₂

end EquilogicalSpace

end ScottDomains.EquilogicalSpaces
