import ScottDomains.EquilogicalSpaces.EquLimits
import Mathlib.CategoryTheory.Limits.Constructions.LimitsOfProductsAndEqualizers

/-!
# Theorem 3.10, the cocompleteness half: `Equ` is cocomplete

> On to coproducts. The coproduct of topological spaces is just a disjoint union
> of the underlying sets with the topology on the union generated by the union of
> all the topologies. For equivalence relations, we have only to note that the
> union of equivalence relations on disjoint sets is indeed an equivalence
> relation. …
>
> Next, we discuss coequalizers. … On `|ℱ|` we form the least equivalence
> relation containing both `≡_ℱ` and the set of pairs `{ (f(x), g(x)) | x ∈ |ℰ| }`.
> Using the same topological space as `ℱ` does and this equivalence relation, we
> form the equilogical space `𝒢`. … Thus, `Equ` is a cocomplete category.

Two points where the paper's wording is doing real work.

**"the union of equivalence relations on disjoint sets"** — disjointness is what
makes it an equivalence relation, and it is why `coprodRel` below is phrased with
*equations* `p = ⟨j, x⟩` rather than with a transport along an index equality.
The equations let `rintro` substitute, and transitivity then needs only the
injectivity of `Sigma.mk`.

**"the least equivalence relation containing"** — that is `Relation.EqvGen`, and
the universal property of the coequalizer is proved by induction over it. Note
the coequalizer keeps `ℱ`'s topology unchanged: *no topology is placed on the
quotient*, which the paper flags as one reason `Equ` is not equivalent to `Set`.
-/

universe u

namespace ScottDomains.EquilogicalSpaces

open CategoryTheory CategoryTheory.Limits

/-! ## The disjoint union of `T₀` spaces is `T₀`

    Mathlib has no instance for this, so it is proved here. It is the one piece
    of actual topology the coproduct needs.

    Two points in *different* summands are separated by the summand itself,
    which is open; two in the *same* summand by that summand's own `T₀`, pulled
    across the fact that `Sigma.mk i` is an open map. -/

instance sigmaT0Space {J : Type u} (A : J → EquilogicalSpace.{u}) :
    T0Space (Σ j, (A j).carrier) := by
  rw [t0Space_iff_inseparable]
  have hsummand : ∀ k : J, IsOpen {p : Σ j, (A j).carrier | p.1 = k} := by
    intro k
    rw [isOpen_sigma_iff]
    intro l
    by_cases hlk : l = k
    · subst hlk; simp
    · simp [hlk]
  rintro ⟨i, x⟩ ⟨j, y⟩ h
  have hij : i = j :=
    ((inseparable_iff_forall_isOpen.mp h _ (hsummand i)).mp rfl).symm
  subst hij
  have hxy : x = y := by
    have : Inseparable x y := by
      rw [inseparable_iff_forall_isOpen]
      intro U hU
      have hUopen : IsOpen ((Sigma.mk i '' U : Set (Σ j, (A j).carrier))) := by
        exact @isOpenMap_sigmaMk J (fun k => (A k).carrier) _ i U hU
      constructor
      · intro hx
        obtain ⟨z, hz, hzeq⟩ :=
          (inseparable_iff_forall_isOpen.mp h _ hUopen).mp ⟨x, hx, rfl⟩
        cases hzeq; exact hz
      · intro hy
        obtain ⟨z, hz, hzeq⟩ :=
          (inseparable_iff_forall_isOpen.mp h _ hUopen).mpr ⟨y, hy, rfl⟩
        cases hzeq; exact hz
    exact this.eq
  exact congrArg (Sigma.mk i) hxy

/-! ## Coproducts -/

/-- The relation on a disjoint union: related exactly when the two points lie in
    the *same* summand and are related there.

    Phrased with **equations** `p = ⟨j, x⟩` rather than a transport along an
    index equality, so that `rintro` substitutes and transitivity needs only
    `Sigma.mk` injectivity. This is the paper's "the union of equivalence
    relations on *disjoint* sets is indeed an equivalence relation". -/
def coprodRel {J : Type u} (A : J → EquilogicalSpace.{u}) :
    (Σ j, (A j).carrier) → (Σ j, (A j).carrier) → Prop :=
  fun p q => ∃ (j : J) (x y : (A j).carrier), (A j).Rel x y ∧ p = ⟨j, x⟩ ∧ q = ⟨j, y⟩

theorem coprodRel_equivalence {J : Type u} (A : J → EquilogicalSpace.{u}) :
    Equivalence (coprodRel A) where
  refl p := ⟨p.1, p.2, p.2, (A p.1).setoid.refl p.2, rfl, rfl⟩
  symm := by
    rintro _ _ ⟨j, x, y, h, rfl, rfl⟩
    exact ⟨j, y, x, (A j).setoid.symm h, rfl, rfl⟩
  trans := by
    rintro _ _ _ ⟨j, x, y, h₁, rfl, rfl⟩ ⟨j', x', y', h₂, heq, rfl⟩
    cases heq
    exact ⟨j, x, y', (A j).setoid.trans h₁ h₂, rfl, rfl⟩

/-- The coproduct of a family of equilogical spaces. -/
@[reducible] def EquilogicalSpace.sigma {J : Type u} (A : J → EquilogicalSpace.{u}) :
    EquilogicalSpace.{u} where
  carrier := Σ j, (A j).carrier
  setoid := ⟨coprodRel A, coprodRel_equivalence A⟩

namespace EquilogicalSpace

/-- The injection of a summand. -/
def sigmaInj {J : Type u} (A : J → EquilogicalSpace.{u}) (j : J) :
    Equivariant (A j) (EquilogicalSpace.sigma A) where
  toFun := fun x => ⟨j, x⟩
  continuous_toFun := by
    exact @continuous_sigmaMk J (fun k => (A k).carrier) _ j
  equivariant := fun h => ⟨j, _, _, h, rfl, rfl⟩

/-- The map out of the coproduct determined by a family of maps. -/
def sigmaDesc {J : Type u} {T : EquilogicalSpace.{u}} {A : J → EquilogicalSpace.{u}}
    (f : ∀ j, Equivariant (A j) T) : Equivariant (EquilogicalSpace.sigma A) T where
  toFun := fun p => (f p.1).toFun p.2
  continuous_toFun := by
    exact (continuous_sigma (fun j => (f j).continuous_toFun) :
      Continuous fun p : (Σ j, (A j).carrier) => (f p.1).toFun p.2)
  equivariant := by
    rintro _ _ ⟨j, x, y, h, rfl, rfl⟩
    exact (f j).equivariant h

end EquilogicalSpace

/-! ## Coequalizers -/

/-- The relation of the coequalizer: the least equivalence relation containing
    `≡_ℬ` together with the pairs `(f a, g a)`. -/
def coeqRel {A B : EquilogicalSpace.{u}} (f g : Equivariant A B) :
    B.carrier → B.carrier → Prop :=
  Relation.EqvGen (fun x y => B.Rel x y ∨ ∃ a, x = f.toFun a ∧ y = g.toFun a)

/-- The coequalizer object: **the same space as `ℬ`**, with the relation
    coarsened. No topology is placed on a quotient. -/
def EquilogicalSpace.coeqObj {A B : EquilogicalSpace.{u}} (f g : Equivariant A B) :
    EquilogicalSpace.{u} where
  carrier := B.carrier
  setoid := ⟨coeqRel f g, Relation.EqvGen.is_equivalence _⟩

namespace EquilogicalSpace

/-- The quotient map is the identity on points. -/
def coeqProj {A B : EquilogicalSpace.{u}} (f g : Equivariant A B) :
    Equivariant B (coeqObj f g) where
  toFun := id
  continuous_toFun := continuous_id
  equivariant := fun h => Relation.EqvGen.rel _ _ (Or.inl h)

/-- It coequalizes: `f a` is identified with `g a` by a generator, and then `g`'s
    equivariance moves along the relation in `ℬ`. -/
theorem coeqProj_coequalizes {A B : EquilogicalSpace.{u}} (f g : Equivariant A B) :
    Equivariant.MapEquiv (Equivariant.comp (coeqProj f g) f)
      (Equivariant.comp (coeqProj f g) g) := fun x _ h =>
  Relation.EqvGen.trans _ _ _
    (Relation.EqvGen.rel _ _ (Or.inr ⟨x, rfl, rfl⟩))
    (Relation.EqvGen.rel _ _ (Or.inl (g.equivariant h)))

/-- Any map coequalizing `f` and `g` factors, by induction over `EqvGen`. -/
def coeqDesc {A B T : EquilogicalSpace.{u}} {f g : Equivariant A B}
    (t : Equivariant B T)
    (ht : Equivariant.MapEquiv (Equivariant.comp t f) (Equivariant.comp t g)) :
    Equivariant (coeqObj f g) T where
  toFun := t.toFun
  continuous_toFun := t.continuous_toFun
  equivariant := by
    intro x y h
    induction h with
    | rel a b hab =>
      rcases hab with hb | ⟨c, rfl, rfl⟩
      · exact t.equivariant hb
      · exact ht c c (A.setoid.refl c)
    | refl a => exact T.setoid.refl _
    | symm a b _ ih => exact T.setoid.symm ih
    | trans a b c _ _ ih₁ ih₂ => exact T.setoid.trans ih₁ ih₂

end EquilogicalSpace

/-! ## `Equ` is cocomplete -/

open EquilogicalSpace in
/-- The cofan on the coproduct. -/
def equCofan {J : Type u} (A : J → EquilogicalSpace.{u}) : Cofan A :=
  Cofan.mk (EquilogicalSpace.sigma A) (fun j => Quotient.mk _ (sigmaInj A j))

open EquilogicalSpace in
noncomputable def equCofanIsColimit {J : Type u} (A : J → EquilogicalSpace.{u}) :
    IsColimit (equCofan A) :=
  Cofan.IsColimit.mk _
    (fun s => Quotient.mk _ (sigmaDesc fun j => homOut (s.inj j)))
    (fun s j => homOut_spec (s.inj j))
    (fun s m hm => by
      revert hm
      refine Quotient.inductionOn m (fun m => ?_)
      intro hm
      refine Quotient.sound ?_
      rintro _ _ ⟨j, x, y, h, rfl, rfl⟩
      exact Quotient.exact ((hm j).trans (homOut_spec (s.inj j)).symm) x y h)

instance : HasCoproducts.{u} EquilogicalSpace.{u} :=
  hasCoproducts_of_colimit_cofans equCofan equCofanIsColimit

open EquilogicalSpace in
instance equHasColimitParallelPair {A B : EquilogicalSpace.{u}} (f g : A ⟶ B) :
    HasColimit (parallelPair f g) := by
  refine Quotient.inductionOn₂ f g (fun f g => HasColimit.mk ?_)
  refine
    { cocone := Cofork.ofπ (P := coeqObj f g) (Quotient.mk _ (coeqProj f g))
        (Quotient.sound (coeqProj_coequalizes f g))
      isColimit := Cofork.IsColimit.mk _
        (fun s => Quotient.mk _
          (coeqDesc (homOut (Cofork.π s))
            (Quotient.exact ((homOut_spec (Cofork.π s)).symm ▸ s.condition))))
        (fun s => homOut_spec (Cofork.π s))
        (fun s m hm => ?_) }
  revert hm
  refine Quotient.inductionOn m (fun m => ?_)
  intro hm
  refine Quotient.sound (fun x y hxy => ?_)
  -- The goal is over `coeqObj`'s relation, an `EqvGen`, not over `ℬ`'s. Use `m`'s
  -- own equivariance to move from `x` to `y`, then the hypothesis at the
  -- reflexive point `y` — where `coeqProj` is the identity.
  have key := Quotient.exact (hm.trans (homOut_spec (Cofork.π s)).symm)
  exact EquilogicalSpace.Rel.trans (m.equivariant hxy) (key y y (B.setoid.refl y))

instance : HasCoequalizers EquilogicalSpace.{u} :=
  hasCoequalizers_of_hasColimit_parallelPair _

/-- **Theorem 3.10, the cocompleteness half**: `Equ` is cocomplete. -/
instance equHasColimits : HasColimitsOfSize.{u, u} EquilogicalSpace.{u} :=
  has_colimits_of_hasCoequalizers_and_coproducts

end ScottDomains.EquilogicalSpaces
