#!/usr/bin/env bash
# r0044 / agent3 — generate the two driver Lean files for the Class 2 vacuity
# sweep by prepending a literal `import` block to a static body.
#
#   scripts/a3-gen.sh
#
# Why this exists: the package root `ScottDomains.lean` imports Mathlib only, so
# `import ScottDomains` loads none of the package's own declarations — which is
# exactly why `#lint only unusedArguments in ScottDomains` reported "0 errors in
# 0 declarations".  An import block naming every module of the package is needed,
# and it has to be literal (Lean has no glob import), so it is generated here
# from the file tree.  Regenerate after adding a module.
#
# Writes:
#   scripts/a3-vacuity.lean  = imports + scripts/a3-vacuity-body.lean
#   scripts/a3-delete.lean   = imports + scripts/a3-delete-body.lean
#   scripts/a3-lint.lean     = imports + `#lint only unusedArguments in ScottDomains`
set -eu

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
src="$root/ScottDomains"
out_v="$root/scripts/a3-vacuity.lean"
out_d="$root/scripts/a3-delete.lean"
out_l="$root/scripts/a3-lint.lean"

gen_imports() {
  echo "-- GENERATED by scripts/a3-gen.sh — do not edit; edit the body file instead."
  echo "import ScottDomains"
  find "$src/ScottDomains" -name '*.lean' \
    | sed -e "s|^$src/||" -e 's|\.lean$||' -e 's|/|.|g' -e 's|^|import |' \
    | LC_ALL=C sort
  echo "import Batteries.Tactic.Lint"
  echo
}

gen_imports >"$out_v"
cat "$root/scripts/a3-vacuity-body.lean" >>"$out_v"

gen_imports >"$out_d"
cat "$root/scripts/a3-delete-body.lean" >>"$out_d"

gen_imports >"$out_l"
{
  echo "/-! r0044 / agent3 — instrument 1: Batteries' own \`unusedArguments\` linter,"
  echo "run over every declaration of the package.  See scripts/a3-gen.sh. -/"
  echo "#lint only unusedArguments in ScottDomains"
} >>"$out_l"

echo "wrote $out_v ($(wc -l <"$out_v") lines)"
echo "wrote $out_d ($(wc -l <"$out_d") lines)"
echo "wrote $out_l ($(wc -l <"$out_l") lines)"
echo "modules imported: $(grep -c '^import ScottDomains\.' "$out_v")"
