#!/bin/zsh
# a5-gen-driver.sh — build a Lean driver that has the whole ScottDomains package
# in scope, from a body fragment.
#
# Why this exists: the package's root module `ScottDomains.lean` re-exports only
# the Mathlib foundations; it imports none of the development's own 100 modules.
# A driver that says `import ScottDomains` therefore presents an environment with
# zero ScottDomains declarations, and `#lint … in ScottDomains` reports
# "0 errors in 0 declarations" — a false pass, measured in
# logs/a5-lint-20260808-171155.agent5.log. So every r0044 instrument must import
# all 100 modules by name, and the list is derived from the file tree here (path
# under ScottDomains/ with `/`→`.` and `.lean` stripped) so it cannot drift.
#
# Usage: scripts/a5-gen-driver.sh <body-file> <out-file>
#   body-file  Lean source appended after the import block
#   out-file   generated driver; keep it outside ScottDomains/ScottDomains/ so
#              scripts/counts.sh and `lake build` never see it
set -e

root="${0:A:h}/.."
cd "$root"
root="$PWD"
pkg="$root/ScottDomains"

body="$1"
out="$2"
[[ -z "$body" || -z "$out" ]] && { print -u2 -- "usage: a5-gen-driver.sh <body-file> <out-file>"; exit 2 }

mods=(${(f)"$(cd $pkg && find ScottDomains -name '*.lean' | sed -e 's|/|.|g' -e 's|\.lean$||' | sort)"})

{
  print -- "-- GENERATED by scripts/a5-gen-driver.sh from $(basename $body); do not edit by hand."
  print -- "import Batteries.Tactic.Lint"
  for m in $mods; do print -- "import $m"; done
  print -- ""
  cat "$body"
} > "$out"

print -- "a5-gen-driver: ${#mods} modules + $(basename $body) -> $out"
