-- GENERATED by scripts/a5-gen-driver.sh from a5-body-lint.lean; do not edit by hand.
import Batteries.Tactic.Lint
import ScottDomains.Atomless
import ScottDomains.Audit.Bifinite
import ScottDomains.Audit.Foundations
import ScottDomains.Audit.Powerdomains
import ScottDomains.Audit.Projections
import ScottDomains.Audit.SectionSeven
import ScottDomains.Audit.Skeleton
import ScottDomains.Bifinite
import ScottDomains.BifiniteUniversal
import ScottDomains.Closure
import ScottDomains.ClosureProperties
import ScottDomains.ClosureProperties.Powerdomain
import ScottDomains.ClosureProperties.SeparatedSum
import ScottDomains.ClosureProperties.StrictFunction
import ScottDomains.CoalescedSum
import ScottDomains.Colimit
import ScottDomains.Combinator
import ScottDomains.CombinatorRep
import ScottDomains.CompactFunction
import ScottDomains.ComputableFunction
import ScottDomains.ContinuousAlgebra
import ScottDomains.ContinuousConstruction
import ScottDomains.Currying
import ScottDomains.Domain
import ScottDomains.Dyadic
import ScottDomains.Effective.FunctionSpace
import ScottDomains.Effective.Powerset
import ScottDomains.EffectivePresentation
import ScottDomains.ExistingTheories
import ScottDomains.FinitaryProjection
import ScottDomains.FinitaryProjectionEmbedding
import ScottDomains.FinitaryProjectionPoset
import ScottDomains.FixedPoint
import ScottDomains.Flat
import ScottDomains.FlatOmega
import ScottDomains.FlatPowerdomain
import ScottDomains.FlatSection6
import ScottDomains.FunctionSpaceCountable
import ScottDomains.FunctionSpaceDomain
import ScottDomains.IdealCompletion
import ScottDomains.Isomorphism.Copair
import ScottDomains.Isomorphism.Counterexample
import ScottDomains.Isomorphism.Distribute
import ScottDomains.Isomorphism.Lift
import ScottDomains.Isomorphism.Smash
import ScottDomains.Isomorphism.StrictCurry
import ScottDomains.Iwamura
import ScottDomains.JungBicomplete
import ScottDomains.JungCor136
import ScottDomains.JungFinite
import ScottDomains.JungNets
import ScottDomains.JungSFP
import ScottDomains.Kleene.Extension
import ScottDomains.Kleene.Factorial
import ScottDomains.Kleene.FixContinuous
import ScottDomains.Kleene.Grammar
import ScottDomains.Kleene.Graph
import ScottDomains.Kleene.Uniform
import ScottDomains.Lemma28AtU
import ScottDomains.LemThirty
import ScottDomains.Lift
import ScottDomains.MinimalUpperBounds
import ScottDomains.Morphism
import ScottDomains.NormalProjection
import ScottDomains.NormalSubposet
import ScottDomains.Powerdomain.BoundedComplete
import ScottDomains.PowerdomainCompacts
import ScottDomains.Powerdomain.Hoare
import ScottDomains.PowerdomainMap
import ScottDomains.PowerdomainMapRep
import ScottDomains.Powerdomain.Plotkin
import ScottDomains.Powerdomain.Smyth
import ScottDomains.Powerdomain.Universal
import ScottDomains.Powerset
import ScottDomains.PRep
import ScottDomains.PRepFun
import ScottDomains.PRepresentable
import ScottDomains.PRepSum
import ScottDomains.Product
import ScottDomains.Projection
import ScottDomains.PropertyM
import ScottDomains.RecursiveDomain
import ScottDomains.ScottHom
import ScottDomains.Section62
import ScottDomains.SFP
import ScottDomains.Skeleton.Lemma10
import ScottDomains.Skeleton.Lemma17
import ScottDomains.Skeleton.Recovered
import ScottDomains.Skeleton.Section6
import ScottDomains.Skeleton.Section6b
import ScottDomains.Skeleton.Sum
import ScottDomains.Smash
import ScottDomains.StepFunction
import ScottDomains.StrictHom
import ScottDomains.Theorem6
import ScottDomains.Thm18
import ScottDomains.UniformFixedPoint
import ScottDomains.UniversalDomain
import ScottDomains.Universality
import ScottDomains.WayBelow

/-!
Instrument 1 of the r0044 Class-2 vacuity sweep: Batteries' `unusedArguments`
environment linter, run over every declaration in the `ScottDomains` package.

The linter's test, from `Batteries/Tactic/Lint/Misc.lean:31`, is hypothesis
deletion done semantically. It opens the declaration's type with
`forallTelescope`, applies the stored value — for a `theorem`, the proof term —
to all the binders, appends the conclusion type and every binder's type and
let-value, and collects the free variables of that single expression. A binder
whose fvar does not occur is used neither in the proof, nor in the conclusion,
nor in any other hypothesis's type. That is a *proof* of term-level
removability, not a heuristic: the same term typechecks with the binder gone.

Two limits, both load-bearing for how the result may be read.

1. It measures **unused by the current proof**, not **unnecessary**. A hypothesis
   the proof does consume may still be removable by a different proof; this
   linter is blind to that class by construction.
2. It **exempts binders whose user name is internal**, which includes the
   `_`-prefixed convention (`!ldecl.userName.isInternal`, line 57). So `(_h : P)`
   is never reported however dead it is. The exemption makes the linter
   under-report, never over-report.

Run with: scripts/a5-lint.sh
-/

open Batteries.Tactic.Lint

#lint only unusedArguments in ScottDomains
