-- GENERATED by scripts/a5-r46-gen.sh — do not edit; edit a5-r46-diag-body.lean instead.
import ScottDomains
import ScottDomains.A2Lemma28
import ScottDomains.A3Thm29
import ScottDomains.A4PowerdomainRep
import ScottDomains.A5Thm137
import ScottDomains.Atomless
import ScottDomains.Audit.Bifinite
import ScottDomains.Audit.Foundations
import ScottDomains.Audit.Powerdomains
import ScottDomains.Audit.Projections
import ScottDomains.Audit.SectionSeven
import ScottDomains.Audit.Skeleton
import ScottDomains.Bifinite
import ScottDomains.BifiniteUniversal
import ScottDomains.Closure
import ScottDomains.ClosureProperties
import ScottDomains.ClosureProperties.Powerdomain
import ScottDomains.ClosureProperties.SeparatedSum
import ScottDomains.ClosureProperties.StrictFunction
import ScottDomains.CoalescedSum
import ScottDomains.Colimit
import ScottDomains.Combinator
import ScottDomains.CombinatorRep
import ScottDomains.CompactFunction
import ScottDomains.ComputableFunction
import ScottDomains.ContinuousAlgebra
import ScottDomains.ContinuousConstruction
import ScottDomains.Currying
import ScottDomains.Domain
import ScottDomains.Dyadic
import ScottDomains.Effective.A1FlatRecursive
import ScottDomains.Effective.FunctionSpace
import ScottDomains.Effective.Powerset
import ScottDomains.EffectivePresentation
import ScottDomains.ExistingTheories
import ScottDomains.FinitaryProjection
import ScottDomains.FinitaryProjectionEmbedding
import ScottDomains.FinitaryProjectionPoset
import ScottDomains.FixedPoint
import ScottDomains.Flat
import ScottDomains.FlatOmega
import ScottDomains.FlatPowerdomain
import ScottDomains.FlatSection6
import ScottDomains.FunctionSpaceCountable
import ScottDomains.FunctionSpaceDomain
import ScottDomains.IdealCompletion
import ScottDomains.Isomorphism.Copair
import ScottDomains.Isomorphism.Counterexample
import ScottDomains.Isomorphism.Distribute
import ScottDomains.Isomorphism.Lift
import ScottDomains.Isomorphism.Smash
import ScottDomains.Isomorphism.StrictCurry
import ScottDomains.Iwamura
import ScottDomains.JungBicomplete
import ScottDomains.JungCor136
import ScottDomains.JungFinite
import ScottDomains.JungNets
import ScottDomains.JungSFP
import ScottDomains.Kleene.Extension
import ScottDomains.Kleene.Factorial
import ScottDomains.Kleene.FixContinuous
import ScottDomains.Kleene.Grammar
import ScottDomains.Kleene.Graph
import ScottDomains.Kleene.Uniform
import ScottDomains.LemThirty
import ScottDomains.Lemma28AtU
import ScottDomains.Lift
import ScottDomains.MinimalUpperBounds
import ScottDomains.Morphism
import ScottDomains.NormalProjection
import ScottDomains.NormalSubposet
import ScottDomains.PRep
import ScottDomains.PRepFun
import ScottDomains.PRepSum
import ScottDomains.PRepresentable
import ScottDomains.Powerdomain.BoundedComplete
import ScottDomains.Powerdomain.Hoare
import ScottDomains.Powerdomain.Plotkin
import ScottDomains.Powerdomain.Smyth
import ScottDomains.Powerdomain.Universal
import ScottDomains.PowerdomainCompacts
import ScottDomains.PowerdomainMap
import ScottDomains.PowerdomainMapRep
import ScottDomains.Powerset
import ScottDomains.Product
import ScottDomains.Projection
import ScottDomains.PropertyM
import ScottDomains.RecursiveDomain
import ScottDomains.SFP
import ScottDomains.ScottHom
import ScottDomains.Section62
import ScottDomains.Skeleton.Lemma10
import ScottDomains.Skeleton.Lemma17
import ScottDomains.Skeleton.Recovered
import ScottDomains.Skeleton.Section6
import ScottDomains.Skeleton.Section6b
import ScottDomains.Skeleton.Sum
import ScottDomains.Smash
import ScottDomains.StepFunction
import ScottDomains.StrictHom
import ScottDomains.Theorem6
import ScottDomains.Thm18
import ScottDomains.UniformFixedPoint
import ScottDomains.UniversalDomain
import ScottDomains.Universality
import ScottDomains.WayBelow

/-! r0046 / agent5 — diagnostic for the dependency probe. Decides WHY
`ConstantInfo.value?` returned `none` for an imported theorem, and whether an
async-aware lookup recovers the proof term. -/

open Lean

def ctorName : ConstantInfo → String
  | .axiomInfo _  => "axiomInfo"
  | .defnInfo _   => "defnInfo"
  | .thmInfo _    => "thmInfo"
  | .opaqueInfo _ => "opaqueInfo"
  | .quotInfo _   => "quotInfo"
  | .inductInfo _ => "inductInfo"
  | .ctorInfo _   => "ctorInfo"
  | .recInfo _    => "recInfo"

#eval show CoreM Unit from do
  let env ← getEnv
  for n in [`ScottDomains.R45.Agent4.smythImageIso,
            `ScottDomains.R45.Agent4.nonempty_orderIso_range_of_section,
            `ScottDomains.Kleene.recoverAt] do
    match env.find? n with
    | none => IO.println s!"{n}: NOT FOUND"
    | some ci => IO.println s!"{n}: {ctorName ci}, value? = {ci.value?.isSome}"

-- The async-aware lookup: `getConstInfo` goes through `MonadEnv` and awaits.
#eval show CoreM Unit from do
  let ci ← getConstInfo `ScottDomains.R45.Agent4.smythImageIso
  IO.println s!"getConstInfo: {ctorName ci}, value? = {ci.value?.isSome}"

-- Direct theorem-value access, if `thmInfo` is what we have.
#eval show CoreM Unit from do
  let env ← getEnv
  match env.find? `ScottDomains.R45.Agent4.smythImageIso with
  | some (.thmInfo v) =>
      IO.println s!"thmInfo.value used constants: {v.value.getUsedConstants.size}"
  | some ci => IO.println s!"not a thmInfo: {ctorName ci}"
  | none => IO.println "not found"
