#!/usr/bin/env bash
# a5-r46-gen.sh — r0046 / agent5. Prepend a literal 100-module import block to a
# probe body, producing a probe that sees the WHOLE package environment.
#
#   scripts/a5-r46-gen.sh <body.lean> <out.lean>
#
# Why this exists, and why it is not optional. `ScottDomains.lean` (the package
# root) imports five Mathlib order files and NONE of the package's own 105
# modules, so `import ScottDomains` yields a **Mathlib-only** environment in
# which every `#check` on a package declaration reports "unknown identifier".
# Four agents across r0044-r0045 hit this and misread it as absence. Lean has no
# glob import, so the list must be literal, and generating it from the file tree
# makes the probe's coverage the package's coverage by construction.
#
# Same idea as `scripts/a3-gen.sh` (r0044/agent3) and `scripts/a4-mkprobe.sh`
# (r0044/agent4); rewritten here in bash and parameterized by body file.
#
# Work: O(#modules) path-to-module-name rewrites; span: one `find`.
set -eu
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
src="$root/ScottDomains"
body="$1"
out="$2"

{
  echo "-- GENERATED by scripts/a5-r46-gen.sh — do not edit; edit $(basename "$body") instead."
  echo "import ScottDomains"
  find "$src/ScottDomains" -name '*.lean' \
    | sed -e "s|^$src/||" -e 's|\.lean$||' -e 's|/|.|g' -e 's|^|import |' \
    | LC_ALL=C sort
  echo
} > "$out"
cat "$body" >> "$out"

echo "wrote $out ($(grep -c '^import ScottDomains\.' "$out") package modules imported)"
