-- GENERATED by scripts/a5-gen-driver.sh from a5-body-structures.lean; do not edit by hand.
import Batteries.Tactic.Lint
import ScottDomains.Atomless
import ScottDomains.Audit.Bifinite
import ScottDomains.Audit.Foundations
import ScottDomains.Audit.Powerdomains
import ScottDomains.Audit.Projections
import ScottDomains.Audit.SectionSeven
import ScottDomains.Audit.Skeleton
import ScottDomains.Bifinite
import ScottDomains.BifiniteUniversal
import ScottDomains.Closure
import ScottDomains.ClosureProperties
import ScottDomains.ClosureProperties.Powerdomain
import ScottDomains.ClosureProperties.SeparatedSum
import ScottDomains.ClosureProperties.StrictFunction
import ScottDomains.CoalescedSum
import ScottDomains.Colimit
import ScottDomains.Combinator
import ScottDomains.CombinatorRep
import ScottDomains.CompactFunction
import ScottDomains.ComputableFunction
import ScottDomains.ContinuousAlgebra
import ScottDomains.ContinuousConstruction
import ScottDomains.Currying
import ScottDomains.Domain
import ScottDomains.Dyadic
import ScottDomains.Effective.FunctionSpace
import ScottDomains.Effective.Powerset
import ScottDomains.EffectivePresentation
import ScottDomains.ExistingTheories
import ScottDomains.FinitaryProjection
import ScottDomains.FinitaryProjectionEmbedding
import ScottDomains.FinitaryProjectionPoset
import ScottDomains.FixedPoint
import ScottDomains.Flat
import ScottDomains.FlatOmega
import ScottDomains.FlatPowerdomain
import ScottDomains.FlatSection6
import ScottDomains.FunctionSpaceCountable
import ScottDomains.FunctionSpaceDomain
import ScottDomains.IdealCompletion
import ScottDomains.Isomorphism.Copair
import ScottDomains.Isomorphism.Counterexample
import ScottDomains.Isomorphism.Distribute
import ScottDomains.Isomorphism.Lift
import ScottDomains.Isomorphism.Smash
import ScottDomains.Isomorphism.StrictCurry
import ScottDomains.Iwamura
import ScottDomains.JungBicomplete
import ScottDomains.JungCor136
import ScottDomains.JungFinite
import ScottDomains.JungNets
import ScottDomains.JungSFP
import ScottDomains.Kleene.Extension
import ScottDomains.Kleene.Factorial
import ScottDomains.Kleene.FixContinuous
import ScottDomains.Kleene.Grammar
import ScottDomains.Kleene.Graph
import ScottDomains.Kleene.Uniform
import ScottDomains.Lemma28AtU
import ScottDomains.LemThirty
import ScottDomains.Lift
import ScottDomains.MinimalUpperBounds
import ScottDomains.Morphism
import ScottDomains.NormalProjection
import ScottDomains.NormalSubposet
import ScottDomains.Powerdomain.BoundedComplete
import ScottDomains.PowerdomainCompacts
import ScottDomains.Powerdomain.Hoare
import ScottDomains.PowerdomainMap
import ScottDomains.PowerdomainMapRep
import ScottDomains.Powerdomain.Plotkin
import ScottDomains.Powerdomain.Smyth
import ScottDomains.Powerdomain.Universal
import ScottDomains.Powerset
import ScottDomains.PRep
import ScottDomains.PRepFun
import ScottDomains.PRepresentable
import ScottDomains.PRepSum
import ScottDomains.Product
import ScottDomains.Projection
import ScottDomains.PropertyM
import ScottDomains.RecursiveDomain
import ScottDomains.ScottHom
import ScottDomains.Section62
import ScottDomains.SFP
import ScottDomains.Skeleton.Lemma10
import ScottDomains.Skeleton.Lemma17
import ScottDomains.Skeleton.Recovered
import ScottDomains.Skeleton.Section6
import ScottDomains.Skeleton.Section6b
import ScottDomains.Skeleton.Sum
import ScottDomains.Smash
import ScottDomains.StepFunction
import ScottDomains.StrictHom
import ScottDomains.Theorem6
import ScottDomains.Thm18
import ScottDomains.UniformFixedPoint
import ScottDomains.UniversalDomain
import ScottDomains.Universality
import ScottDomains.WayBelow

/-!
Instrument 3 of the r0044 Class-2 vacuity sweep: the structure census.

Enumerates, from the *built environment* rather than from source text, every
`structure` and `class` declared in the `ScottDomains` package, with its
parameter telescope and its field types. A structure that `Classical.dec` — or
any other free construction — inhabits for every type makes every theorem
quantifying over it uninformative; `EffectivePresentation` is the known case, and
its `decidableLE` / `decidableNormal` fields are what make it one. The field
types decide the question, and they must be read off the elaborated declaration,
not off the `structure` line.

Reading from the environment also answers a second question: how many structures
a column-0 `grep '^structure'` misses.

Run with: scripts/a5-lint.sh scripts/a5-structures.lean
-/

open Lean Elab Command Meta

-- Print every structure/class declared in a module whose name starts with
-- `ScottDomains`, with its parameters and its field types. A `/-- … -/` doc
-- comment cannot be attached to `run_cmd`, so this is a line comment.
run_cmd liftTermElabM do
  let env ← getEnv
  let mods := env.header.moduleNames
  let mut names : Array Name := #[]
  for (n, _) in env.constants.map₁.toList do
    if let some i := env.const2ModIdx[n]? then
      if (`ScottDomains).isPrefixOf mods[i]! then
        if isStructure env n then
          names := names.push n
  names := names.qsort (fun a b => a.toString < b.toString)
  IO.println s!"-- structures/classes in package ScottDomains: {names.size}"
  for n in names do
    let ci ← getConstInfo n
    let kind := if isClass env n then "class" else "structure"
    IO.println s!"\n### {kind} {n}"
    IO.println s!"    type: {← Meta.ppExpr ci.type}"
    for f in getStructureFields env n do
      let some proj := getProjFnForField? env n f | continue
      let pci ← getConstInfo proj
      IO.println s!"    field {f} : {← Meta.ppExpr pci.type}"
