#!/usr/bin/env python3
"""a7-gen-dump.py — generate the Lean file that dumps the environment's constants.

Why generated rather than hand-written: `import ScottDomains` does NOT give the
library. The root module `ScottDomains.lean` re-exports the Mathlib foundations
the development builds on and imports none of the 100 submodules; the lakefile
builds them via the `ScottDomains.+` glob, not via the root. A dump file that
imports only the root therefore sees Mathlib and none of our own declarations —
measured, 235431 constants and zero from our modules. So the dump file must
import all 100 modules explicitly, and that list has to be generated from the
tree to stay correct as modules are added.

Usage:
    a7-gen-dump.py <src-dir> <out.lean> <out.tsv>
"""

import os
import sys


def modules(src):
    """Module names for every .lean under src, e.g. Powerdomain/Smyth.lean ->
    ScottDomains.Powerdomain.Smyth."""
    found = []
    for dirpath, _dirs, files in os.walk(src):
        for f in sorted(files):
            if not f.endswith(".lean"):
                continue
            rel = os.path.relpath(os.path.join(dirpath, f), src)
            found.append("ScottDomains." + rel[: -len(".lean")].replace(os.sep, "."))
    return sorted(found)


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    src, out_lean, out_tsv = sys.argv[1:4]
    mods = modules(src)

    body = [
        "/-",
        "Generated by scripts/a7-gen-dump.py — do not edit.",
        "",
        "Dumps every constant in the elaborated environment as \"module<TAB>name\",",
        "the authoritative name universe for r0044's class-4 citation sweep.",
        "Structure and class projections, inductive constructors, and Mathlib names",
        "are all constants here; all three were r0043's documented false-positive",
        "sources, and taking the universe from the environment removes them by",
        "construction.",
        "",
        "This file lives outside the package on purpose: it is not a module of",
        "ScottDomains and must not change the build's 100-module / 1339-job counts.",
        "-/",
        "",
    ]
    # All of Mathlib, not just what we transitively import. Docs cite Mathlib
    # names from files this package does not import (measured: 15 such names,
    # e.g. `MeasureTheory.Measure.AbsolutelyContinuous`, `TopCat`, `LawfulFix`),
    # and each read as unresolved until the universe covered them.
    body += ["import Mathlib"]
    body += ["import %s" % m for m in mods]
    body += [
        "",
        "open Lean in",
        "run_cmd do",
        "  let env ← Lean.getEnv",
        "  let mut lines : Array String := #[]",
        "  for (n, _) in env.constants.toList do",
        "    let mod := match env.getModuleFor? n with",
        "      | some m => m.toString",
        "      | none   => \"<current>\"",
        "    lines := lines.push (mod ++ \"\\t\" ++ n.toString)",
        "  IO.FS.writeFile",
        "    %s" % repr(out_tsv).replace("'", '"'),
        "    (String.intercalate \"\\n\" lines.toList)",
        "",
    ]
    with open(out_lean, "w", encoding="utf-8") as fh:
        fh.write("\n".join(body))

    # The module list also goes out on its own. The environment dump names a
    # module only when some constant is declared in it, so a module that
    # declares nothing — `ScottDomains.ExistingTheories` is one — is invisible
    # there, and a citation of it read as a nonexistent declaration.
    with open(out_tsv + ".modules", "w", encoding="utf-8") as fh:
        fh.write("\n".join(mods) + "\n")
    print("a7-gen-dump: %d modules -> %s" % (len(mods), out_lean))


if __name__ == "__main__":
    main()
