import ScottDomains.Powerdomain.Hoare
import ScottDomains.Powerdomain.Smyth
import ScottDomains.Powerdomain.Plotkin

/-!
# Lemma 13: bounded completeness of the upper and lower powerdomains

Gunter & Scott, *Semantic Domains* (Handbook of Theoretical Computer Science
Vol. B, 1990), §4.5:

> **Lemma 13** If `D` is bounded complete then so are the powerdomains `D♯` and
> `D♭`.

and §4.5's definition of the predicate, quoted in `ScottDomains/Domain.lean`:

> A poset `A` is said to be **bounded complete** if `A` has a least element and
> every bounded subset of `A` has a least upper bound.

## Which of the paper's symbols each conjunct is

The plan for this round writes the two powerdomains `D]` and `D[`; those are an
ASCII rendering of the paper's `D♯` and `D♭`, the **upper (Smyth)** and **lower
(Hoare)** powerdomains of §5.2, quoted verbatim in `Powerdomain/Smyth.lean`. So

* `lemma_13_hoare` is the paper's `D♭` — `ScottDomains.Hoare.Powerdomain`;
* `lemma_13_smyth` is the paper's `D♯` — `ScottDomains.Smyth.Powerdomain`.

There is no `lem13_plotkin`. The paper's third powerdomain is `D♮`, the convex
(Plotkin) one, and Lemma 13 does not name it: the convex powerdomain does not
preserve bounded completeness, which is why §6 moves to bifinite domains before
treating it. This file therefore proves Lemma 13 for exactly the two conjuncts
the paper states, and registers the class-valued `BoundedComplete` instance for
each of them.

## The defect r0031 found here and r0032 repaired (history)

`BoundedComplete` is stated in `Domain.lean` against the **ambient `sSup`**:

    isLUB_sSup_of_bddAbove : ∀ s, BddAbove s → IsLUB s (sSup s)

so it asserts two things at once — that a bounded set has a least upper bound
(the paper's Lemma 13) and that `sSup` computes it. For every powerdomain the
ambient `sSup` is `IdealCompletion.idealSup`, and until r0032 its `dite`
branched on `Order.IsIdeal (⋃₀ …)`, returning `⊥` otherwise. That branch is
**not** the membership condition for the least upper bound: the least upper
bound of a family of ideals is the ideal *generated by* the union, and the union
itself is an ideal only when the family is **directed**, not merely bounded.

The consequence was measured, not asserted. r0031 proved the class-valued
statement false for all three powerdomains of `P N`, with one witness in each
case: the compact elements `{0}` and `{1}` of `P N` are incomparable, the pair
of principal ideals `↓{{0}}`, `↓{{1}}` is bounded above by `↓{{0,1}}`, and their
union is not directed — so the old `idealSup` returned `⊥`, which is not even an
upper bound. That was the third occurrence of the defect class that cost
`ScottHom` (r0006–r0011) and `Smash` (r0027) a repair.

r0032 repaired it in `IdealCompletion.lean`: `idealSup` now branches on
`Order.IsIdeal (genIdeal S)`, the generated ideal being an ideal, which is the
membership condition the constructor actually needs. The three refutations
`not_boundedComplete_hoare`, `_smyth`, `_plotkin` are false against the repaired
definition and were retired; the witness they used is kept below as a
nondegeneracy check that runs the other way — `not_isIdeal_sUnion_hoareWitness`
shows the *old* guard still fails on that family, while
`sSup_hoareWitness_ne_bot` and `isLUB_sSup_hoareWitness` show the repaired `sSup`
returns its genuine least upper bound.

The paper's Lemma 13 was true throughout and is proved here in the paper's own
words — `BddAbove S → ∃ I, IsLUB S I`. Together with the `OrderBot` instance
that `IdealCompletion` carries, that pair is exactly the quoted definition of
*bounded complete*, so `lemma_13_hoare` and `lemma_13_smyth` say what §4.5 says; after
the repair the class-valued form says it too.

## How the two conjuncts are proved

One construction serves both, and since r0032 it lives in the shared module:
`IdealCompletion.genIdeal S`, the intersection of every ideal above `S`, is an
ideal as soon as `S` is bounded and bounded *pairs* of the underlying pre-order
have least upper bounds (`IdealCompletion.isIdeal_genIdeal`); it is then the
least upper bound of `S` and the value `sSup` returns
(`IdealCompletion.boundedComplete`). No finite joins and no transfinite
construction are needed — only binary joins of **bounded** pairs.

That reduces each conjunct to a statement about the pre-order `Pf(K(D))`:

* **Hoare** (`hoare_exists_isLUB_pair`) — under `⊑♭` the join is the **union**,
  `u ∪ v`, and it exists unconditionally. Bounded completeness of `D` is never
  consumed, so `D♭` is bounded complete for every domain `D`; the hypothesis is
  kept because the paper states it.
* **Smyth** (`smyth_exists_isLUB_pair`) — under `⊑♯` the join of a **bounded**
  pair is `{a ⊔ b | a ∈ u, b ∈ v, {a,b} bounded}`, and here both halves of the
  hypothesis are spent: bounded completeness of `D` supplies `a ⊔ b`, and
  `isCompactElement_of_isLUB_pair` (`Domain.lean`) certifies that it is again
  compact, so the join is a point of `Pf(K(D))`. Boundedness of `{u, v}` is what
  makes the set non-empty, which the paper's `Pf` requires.

The Egli–Milner order admits no such join — `Plotkin.not_single_le_pair` already
shows `{a} ⊑ {a, b}` fails — which is the order-theoretic reason Lemma 13 names
only two of the three powerdomains.

## Statements

* `exists_isLUB_of_bddAbove_idealCompletion` — the general construction.
* `lemma_13_hoare`, `lemma_13_smyth` — Lemma 13, in the paper's wording.
* `instBoundedCompleteHoare`, `instBoundedCompleteSmyth` — the class-valued form,
  reinstated by the r0032 repair. There is no Plotkin instance: the Egli–Milner
  order supplies no join of a bounded pair, so `IdealCompletion.boundedComplete`
  has no input for `D♮` and the paper claims none.
* `not_isIdeal_sUnion_hoareWitness`, `isLUB_sSup_hoareWitness`,
  `sSup_hoareWitness_ne_bot` — the r0031 witness in `P N`, re-checked against the
  repaired `sSup`.
-/

namespace ScottDomains.PowerdomainBC

universe u

/-! ## Least upper bounds of bounded families of ideals

Everything in this section is about an arbitrary pre-order `A` with a least
element; the two powerdomains are instances of it. -/

section IdealCompletionGeneral

variable {A : Type u} [Preorder A] [OrderBot A]

omit [OrderBot A] in
/-- Membership in the union of a family of ideals, in terms of the family rather
than of its image under `SetLike.coe`. This is the body of
`IdealCompletion.mem_sSup_iff` with its directedness hypothesis stripped off —
that hypothesis is used there only to know the union is the supremum, not to
compute membership. Used below to show the union of the r0031 witness is not
directed, which is what the pre-r0032 `idealSup` branched on. -/
theorem mem_sUnion_coe_iff {S : Set (IdealCompletion A)} {x : A} :
    x ∈ ⋃₀ (SetLike.coe '' S) ↔ ∃ I ∈ S, x ∈ I := by
  constructor
  · rintro ⟨_, ⟨I, hI, rfl⟩, hx⟩
    exact ⟨I, hI, hx⟩
  · rintro ⟨I, hI, hx⟩
    exact ⟨(I : Set A), Set.mem_image_of_mem _ hI, hx⟩

/-- **Every bounded family of ideals has a least upper bound**, provided bounded
pairs of the underlying pre-order do — the paper's Lemma 13 in its English form,
`BddAbove S → ∃ I, IsLUB S I`. The other half of *bounded complete*, a least
element, is the `OrderBot` instance `IdealCompletion` already carries.

The witness is `IdealCompletion.genIdeal S`; since r0032 that is also the value
`sSup` returns, so `IdealCompletion.boundedComplete` strengthens this to the
class-valued form. This statement is kept because it is the paper's own
phrasing and consumes no `BoundedComplete` instance. -/
theorem exists_isLUB_of_bddAbove_idealCompletion
    (hpair : ∀ a b : A, BddAbove ({a, b} : Set A) → ∃ c, IsLUB ({a, b} : Set A) c)
    {S : Set (IdealCompletion A)} (hS : BddAbove S) : ∃ I : IdealCompletion A, IsLUB S I :=
  ⟨IdealCompletion.idealSup S,
    IdealCompletion.isLUB_idealSup_of_isIdeal_genIdeal
      (IdealCompletion.isIdeal_genIdeal hpair hS)⟩

end IdealCompletionGeneral

/-! ## `D♭`: the Hoare (lower) powerdomain

Under `⊑♭` the join is the union, and it needs no hypothesis at all: `u ∪ v` is
non-empty because `u` is, every element of `u` is below itself in `u ∪ v`, and an
upper bound of both `u` and `v` bounds each element of the union on the side it
came from. -/

section Hoare

open ScottDomains.Hoare

/-- The **union is the least upper bound** in `⟨Pf(A), ⊑♭⟩`, for *every* pair —
the Hoare pre-order is a join-semilattice, not merely a bounded-complete one.
This is the input `exists_isLUB_of_bddAbove_idealCompletion` consumes. -/
theorem hoare_exists_isLUB_pair {A : Type u} [Preorder A] (u v : Pf A) :
    ∃ c, IsLUB ({u, v} : Set (Pf A)) c := by
  classical
  obtain ⟨x₀, hx₀⟩ := u.toFinset_nonempty
  refine ⟨Pf.ofFinset (u.toFinset ∪ v.toFinset) ⟨x₀, Finset.mem_union_left _ hx₀⟩, ?_, ?_⟩
  · rintro w (rfl | rfl)
    · exact fun x hx => ⟨x, Finset.mem_union_left _ hx, le_rfl⟩
    · exact fun x hx => ⟨x, Finset.mem_union_right _ hx, le_rfl⟩
  · intro w hw x hx
    rcases Finset.mem_union.mp hx with h | h
    · exact hw (Set.mem_insert u {v}) x h
    · exact hw (Set.mem_insert_of_mem u rfl) x h

/-- **Lemma 13, the `D♭` conjunct** (Gunter & Scott §4.5): the lower powerdomain
of a bounded complete domain is bounded complete — every bounded subset of `D♭`
has a least upper bound, and `D♭` has a least element (its `OrderBot` instance).

`[BoundedComplete α]` is not consumed: `hoare_exists_isLUB_pair` supplies joins
for *every* pair of `Pf(K(D))`, so `D♭` is bounded complete for every domain `D`.
The hypothesis is retained because the paper states Lemma 13 that way; recording
that it is unused is the honest report of a strengthening, not a change of
statement. -/
theorem lemma_13_hoare (α : Type u) [CompletePartialOrder α] [Domain α] [BoundedComplete α]
    (S : Set (Hoare.Powerdomain α)) (hS : BddAbove S) : ∃ I, IsLUB S I :=
  exists_isLUB_of_bddAbove_idealCompletion (fun u v _ => hoare_exists_isLUB_pair u v) hS

/-- **Lemma 13's `D♭` conjunct in the class-valued form**, reinstated by the
r0032 repair of `idealSup`: not only does every bounded subset of `D♭` have a
least upper bound, the ambient `sSup` computes it.

`[BoundedComplete α]` is absent by design — `hoare_exists_isLUB_pair` supplies
joins for *every* pair of `Pf(K(D))`, so `D♭` is bounded complete for every
domain `D`. `[Domain α]` is present only because `Hoare.Powerdomain` takes it. -/
instance instBoundedCompleteHoare (α : Type u) [CompletePartialOrder α] [Domain α] :
    BoundedComplete (Hoare.Powerdomain α) :=
  IdealCompletion.boundedComplete fun u v _ => hoare_exists_isLUB_pair u v

end Hoare

/-! ## `D♯`: the Smyth (upper) powerdomain

Under `⊑♯` a join exists only for a **bounded** pair, and building it consumes
both halves of the paper's hypothesis on `D`: bounded completeness produces
`a ⊔ b` in `D`, and `isCompactElement_of_isLUB_pair` puts it back in `K(D)`. -/

section Smyth

open ScottDomains.Smyth

variable {D : Type u} [CompletePartialOrder D] [BoundedComplete D]

open Classical in
/-- The join of two compact elements of `D`, as a compact element: `a ⊔ b` when
the pair is bounded, and `⊥` otherwise. Total, so it can be mapped over a
`Finset`; the `⊥` branch is never reached below, because the product is filtered
by the same predicate the `dite` tests.

Compactness of the value is `isCompactElement_of_isLUB_pair` (`Domain.lean`),
which is stated for a bare `PartialOrder` with the least upper bound as a
hypothesis — exactly the shape bounded completeness hands it. -/
noncomputable def joinCompact (a b : ↥(compacts D)) : ↥(compacts D) :=
  if h : BddAbove ({(a : D), (b : D)} : Set D) then
    ⟨sSup ({(a : D), (b : D)} : Set D),
      isCompactElement_of_isLUB_pair a.2 b.2 (isLUB_sSup_of_bddAbove h)⟩
  else ⊥

theorem le_joinCompact_left {a b : ↥(compacts D)}
    (h : BddAbove ({(a : D), (b : D)} : Set D)) : a ≤ joinCompact a b := by
  classical
  rw [joinCompact, dif_pos h]
  exact (isLUB_sSup_of_bddAbove h).1 (Set.mem_insert _ _)

theorem le_joinCompact_right {a b : ↥(compacts D)}
    (h : BddAbove ({(a : D), (b : D)} : Set D)) : b ≤ joinCompact a b := by
  classical
  rw [joinCompact, dif_pos h]
  exact (isLUB_sSup_of_bddAbove h).1 (Set.mem_insert_of_mem _ rfl)

theorem joinCompact_le {a b c : ↥(compacts D)} (h : BddAbove ({(a : D), (b : D)} : Set D))
    (hac : a ≤ c) (hbc : b ≤ c) : joinCompact a b ≤ c := by
  classical
  rw [joinCompact, dif_pos h]
  exact (isLUB_sSup_of_bddAbove h).2 (by rintro x (rfl | rfl) <;> assumption)

open Classical in
/-- The candidate Smyth join of two finite sets of compacts: all the joins
`a ⊔ b` over pairs `a ∈ u`, `b ∈ v` that are bounded in `D`. Filtering by
boundedness is what keeps every member of the image a genuine join rather than
`joinCompact`'s `⊥` fallback. -/
noncomputable def smythJoin (u v : Finset ↥(compacts D)) : Finset ↥(compacts D) :=
  (Finset.filter (fun p : ↥(compacts D) × ↥(compacts D) =>
      BddAbove ({(p.1 : D), (p.2 : D)} : Set D)) (u ×ˢ v)).image
    (fun p => joinCompact p.1 p.2)

theorem mem_smythJoin {u v : Finset ↥(compacts D)} {c : ↥(compacts D)} :
    c ∈ smythJoin u v ↔ ∃ a ∈ u, ∃ b ∈ v,
      BddAbove ({(a : D), (b : D)} : Set D) ∧ c = joinCompact a b := by
  classical
  constructor
  · intro hc
    rw [smythJoin, Finset.mem_image] at hc
    obtain ⟨p, hp, hpc⟩ := hc
    rw [Finset.mem_filter, Finset.mem_product] at hp
    exact ⟨p.1, hp.1.1, p.2, hp.1.2, hp.2, hpc.symm⟩
  · rintro ⟨a, ha, b, hb, hbdd, rfl⟩
    rw [smythJoin, Finset.mem_image]
    refine ⟨(a, b), ?_, rfl⟩
    rw [Finset.mem_filter, Finset.mem_product]
    exact ⟨⟨ha, hb⟩, hbdd⟩

/-- **A bounded pair of `⟨Pf(K(D)), ⊑♯⟩` has a least upper bound**, namely
`smythJoin`. Boundedness is spent twice: once to know some pair `a ∈ u`, `b ∈ v`
is bounded in `D` — so the join set is non-empty, which the paper's `Pf`
requires — and once, for each element `c` of a competing upper bound, to bound
the pair it selects and place `a ⊔ b` below `c`. -/
theorem smyth_exists_isLUB_pair {u v : Basis D}
    (h : BddAbove ({u, v} : Set (Basis D))) : ∃ c, IsLUB ({u, v} : Set (Basis D)) c := by
  classical
  obtain ⟨w, hw⟩ := h
  have huw : u ≤ w := hw (Set.mem_insert _ _)
  have hvw : v ≤ w := hw (Set.mem_insert_of_mem _ rfl)
  -- Every element of an upper bound selects a bounded pair, hence a member of the join.
  have hsel : ∀ {z : Basis D}, u ≤ z → v ≤ z → ∀ c ∈ z.toFinset,
      ∃ e ∈ smythJoin u.toFinset v.toFinset, e ≤ c := by
    intro z huz hvz c hc
    obtain ⟨a, ha, hac⟩ := huz c hc
    obtain ⟨b, hb, hbc⟩ := hvz c hc
    have hbdd : BddAbove ({(a : D), (b : D)} : Set D) :=
      ⟨(c : D), by rintro x (rfl | rfl) <;> assumption⟩
    exact ⟨joinCompact a b, mem_smythJoin.mpr ⟨a, ha, b, hb, hbdd, rfl⟩,
      joinCompact_le hbdd hac hbc⟩
  obtain ⟨c₀, hc₀⟩ := w.nonempty'
  obtain ⟨e₀, he₀, -⟩ := hsel huw hvw c₀ hc₀
  refine ⟨⟨smythJoin u.toFinset v.toFinset, ⟨e₀, he₀⟩⟩, ?_, ?_⟩
  · rintro z (rfl | rfl)
    · intro c hc
      obtain ⟨a, ha, b, hb, hbdd, rfl⟩ := mem_smythJoin.mp hc
      exact ⟨a, ha, le_joinCompact_left hbdd⟩
    · intro c hc
      obtain ⟨a, ha, b, hb, hbdd, rfl⟩ := mem_smythJoin.mp hc
      exact ⟨b, hb, le_joinCompact_right hbdd⟩
  · intro z hz
    exact hsel (hz (Set.mem_insert _ _)) (hz (Set.mem_insert_of_mem _ rfl))

/-- **Lemma 13, the `D♯` conjunct** (Gunter & Scott §4.5): the upper powerdomain
of a bounded complete domain is bounded complete — every bounded subset of `D♯`
has a least upper bound, and `D♯` has a least element (its `OrderBot` instance).

Unlike the `D♭` conjunct, both hypotheses on `D` are consumed:
`[BoundedComplete α]` builds `a ⊔ b` and `[Domain α]` is what makes `Basis α` a
countable pre-order in the first place. -/
theorem lemma_13_smyth (α : Type u) [CompletePartialOrder α] [Domain α] [BoundedComplete α]
    (S : Set (Smyth.Powerdomain α)) (hS : BddAbove S) : ∃ I, IsLUB S I :=
  exists_isLUB_of_bddAbove_idealCompletion (fun _ _ h => smyth_exists_isLUB_pair h) hS

/-- **Lemma 13's `D♯` conjunct in the class-valued form**, reinstated by the
r0032 repair of `idealSup`. `[BoundedComplete α]` is genuinely consumed here, by
`smyth_exists_isLUB_pair`; `[Domain α]` is not needed, since `Smyth.Powerdomain`
does not take it and countability of `Basis α` is not used to build a join. -/
instance instBoundedCompleteSmyth (α : Type u) [CompletePartialOrder α] [BoundedComplete α] :
    BoundedComplete (Smyth.Powerdomain α) :=
  IdealCompletion.boundedComplete fun _ _ h => smyth_exists_isLUB_pair h

end Smyth

/-! ## The r0031 witness, re-checked against the repaired `sSup`

`P N` is the witness. Its compact elements are the finite subsets of `ℕ`
(`Powerset.lean`), so `{0}` and `{1}` are compact and incomparable while
`{0, 1}` is compact and above both.

Three statements are checked on it, and together they are the measurement that
the r0032 repair did what it claims. The family
`{↓{{0}}, ↓{{1}}} ⊆ D♭` over `P N` is bounded above by `↓{{0,1}}`
(`bddAbove_hoareWitness`) but its union is **not** an ideal
(`not_isIdeal_sUnion_hoareWitness`) — so the pre-r0032 guard fails on it and the
old `idealSup` returned `⊥`. Against the repaired definition
`isLUB_sSup_hoareWitness` gives `IsLUB` for the ambient `sSup`, and
`sSup_hoareWitness_ne_bot` records that the returned value is not the `⊥` the old
one gave. Without the last two, `instBoundedCompleteHoare` could be satisfied
vacuously by a `sSup` no bounded family ever reaches. -/

section Witness

/-- `{0}`, as a compact element of `P N`. -/
def k0 : ↥(compacts (Set ℕ)) := ⟨{0}, isCompactElement_iff_finite.mpr (Set.finite_singleton 0)⟩

/-- `{1}`, as a compact element of `P N`. -/
def k1 : ↥(compacts (Set ℕ)) := ⟨{1}, isCompactElement_iff_finite.mpr (Set.finite_singleton 1)⟩

/-- `{0, 1}`, as a compact element of `P N` — the bound the two others lack. -/
def k01 : ↥(compacts (Set ℕ)) :=
  ⟨{0, 1}, isCompactElement_iff_finite.mpr ((Set.finite_singleton 1).insert 0)⟩

theorem k0_le_k01 : k0 ≤ k01 := by
  intro x hx
  rw [show x = 0 from hx]
  exact Set.mem_insert 0 {1}

theorem k1_le_k01 : k1 ≤ k01 := by
  intro x hx
  rw [show x = 1 from hx]
  exact Set.mem_insert_of_mem 0 rfl

theorem not_k0_le_k1 : ¬ k0 ≤ k1 := by
  intro h
  have h0 : (0 : ℕ) ∈ ({1} : Set ℕ) := h (show (0 : ℕ) ∈ ({0} : Set ℕ) from rfl)
  exact absurd h0 (by simp)

theorem not_k1_le_k0 : ¬ k1 ≤ k0 := by
  intro h
  have h1 : (1 : ℕ) ∈ ({0} : Set ℕ) := h (show (1 : ℕ) ∈ ({1} : Set ℕ) from rfl)
  exact absurd h1 (by simp)

theorem not_k0_le_bot : ¬ k0 ≤ (⊥ : ↥(compacts (Set ℕ))) := by
  intro h
  have h0 : (0 : ℕ) ∈ (⊥ : Set ℕ) := h (show (0 : ℕ) ∈ ({0} : Set ℕ) from rfl)
  exact absurd h0 (by simp)

/-! ### The witness in `D♭`

Only the Hoare reading is carried forward. r0031 recorded the same defect in
`D♯` and `D♮` with the same compacts; nothing about the repair is specific to
the ordering, so one instance of the check suffices, and for `D♮` there is no
`BoundedComplete` instance to check against. -/

/-- The singleton `{k}` as a point of `⟨Pf(K(P N)), ⊑♭⟩`. -/
def hoarePt (k : ↥(compacts (Set ℕ))) : Hoare.Pf ↥(compacts (Set ℕ)) :=
  Hoare.Pf.ofFinset {k} (Finset.singleton_nonempty k)

theorem hoarePt_le_hoarePt {j k : ↥(compacts (Set ℕ))} (h : j ≤ k) : hoarePt j ≤ hoarePt k := by
  intro x hx
  rw [show x = j from Finset.mem_singleton.mp hx]
  exact ⟨k, Finset.mem_singleton_self k, h⟩

theorem not_hoarePt_k0_le_bot : ¬ hoarePt k0 ≤ (⊥ : Hoare.Pf ↥(compacts (Set ℕ))) := by
  intro h
  obtain ⟨y, hy, h0y⟩ := h k0 (Finset.mem_singleton_self k0)
  exact not_k0_le_bot (h0y.trans_eq (Hoare.Pf.mem_bot.mp hy))

/-- `↓{{0}}`, a point of `D♭` over `P N`. -/
abbrev p0 : Hoare.Powerdomain (Set ℕ) := IdealCompletion.principal (hoarePt k0)

/-- `↓{{1}}`. -/
abbrev p1 : Hoare.Powerdomain (Set ℕ) := IdealCompletion.principal (hoarePt k1)

/-- `↓{{0,1}}`, the bound. -/
abbrev p01 : Hoare.Powerdomain (Set ℕ) := IdealCompletion.principal (hoarePt k01)

/-- No point of `↓{{0}} ∪ ↓{{1}}` is above both `{{0}}` and `{{1}}`: it lies
below one of the two singletons and above the other, which forces `{0}` and
`{1}` to be comparable. -/
theorem not_upperBound_of_le_hoarePt {w : Hoare.Pf ↥(compacts (Set ℕ))}
    (hw : w ≤ hoarePt k0 ∨ w ≤ hoarePt k1) : ¬ (hoarePt k0 ≤ w ∧ hoarePt k1 ≤ w) := by
  rintro ⟨h0, h1⟩
  rcases hw with hw | hw
  · obtain ⟨y, hy, h1y⟩ := h1 k1 (Finset.mem_singleton_self k1)
    obtain ⟨z, hz, hyz⟩ := hw y hy
    exact not_k1_le_k0 (h1y.trans (hyz.trans_eq (Finset.mem_singleton.mp hz)))
  · obtain ⟨y, hy, h0y⟩ := h0 k0 (Finset.mem_singleton_self k0)
    obtain ⟨z, hz, hyz⟩ := hw y hy
    exact not_k0_le_k1 (h0y.trans (hyz.trans_eq (Finset.mem_singleton.mp hz)))

/-- The witness family is bounded above by `↓{{0,1}}`. -/
theorem bddAbove_hoareWitness :
    BddAbove ({p0, p1} : Set (Hoare.Powerdomain (Set ℕ))) := by
  refine ⟨p01, ?_⟩
  rintro _ (rfl | rfl)
  · exact IdealCompletion.principal_mono (hoarePt_le_hoarePt k0_le_k01)
  · exact IdealCompletion.principal_mono (hoarePt_le_hoarePt k1_le_k01)

/-- **The pre-r0032 guard fails on the witness.** The union of `↓{{0}}` and
`↓{{1}}` is not directed, hence not an ideal — so the old `idealSup`, whose
`dite` tested exactly this, took its negative branch and returned `⊥`. Kept as
the record of the defect that r0031 measured. -/
theorem not_isIdeal_sUnion_hoareWitness :
    ¬ Order.IsIdeal (⋃₀ (SetLike.coe '' ({p0, p1} : Set (Hoare.Powerdomain (Set ℕ))))) := by
  intro hI
  obtain ⟨w, hw, h0w, h1w⟩ :=
    hI.Directed (hoarePt k0)
        (mem_sUnion_coe_iff.mpr
          ⟨p0, Set.mem_insert _ _, IdealCompletion.mem_principal_self _⟩)
      (hoarePt k1)
        (mem_sUnion_coe_iff.mpr
          ⟨p1, Set.mem_insert_of_mem _ rfl, IdealCompletion.mem_principal_self _⟩)
  obtain ⟨I, hImem, hwI⟩ := mem_sUnion_coe_iff.mp hw
  rcases hImem with rfl | rfl
  · exact not_upperBound_of_le_hoarePt (Or.inl hwI) ⟨h0w, h1w⟩
  · exact not_upperBound_of_le_hoarePt (Or.inr hwI) ⟨h0w, h1w⟩

/-- **The repaired `sSup` computes the least upper bound of the witness.** This
is `instBoundedCompleteHoare` applied to the very family that refuted the class
in r0031. -/
theorem isLUB_sSup_hoareWitness :
    IsLUB ({p0, p1} : Set (Hoare.Powerdomain (Set ℕ)))
      (sSup ({p0, p1} : Set (Hoare.Powerdomain (Set ℕ)))) :=
  isLUB_sSup_of_bddAbove bddAbove_hoareWitness

/-- **And the value it returns is not `⊥`** — the answer the pre-r0032
`idealSup` gave. Were `sSup` of the witness `⊥`, then `↓{{0}} ≤ ⊥` would force
`{{0}} ⊑♭ {⊥}` and hence `{0} ⊆ ∅`. -/
theorem sSup_hoareWitness_ne_bot :
    sSup ({p0, p1} : Set (Hoare.Powerdomain (Set ℕ))) ≠ ⊥ := by
  intro h
  have hle := isLUB_sSup_hoareWitness.1 (Set.mem_insert _ _)
  rw [h] at hle
  exact not_hoarePt_k0_le_bot (IdealCompletion.principal_le_iff.mp hle)

end Witness

end ScottDomains.PowerdomainBC

/- Axiom audit, by `#print axioms` (run at r0032, then removed so the build emits
no `info` lines). No declaration depends on `sorryAx`.

  ScottDomains.PowerdomainBC.mem_sUnion_coe_iff             [no axioms]
  ScottDomains.PowerdomainBC.exists_isLUB_of_bddAbove_idealCompletion
                                                            [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.hoare_exists_isLUB_pair        [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.lemma_13_hoare                    [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.instBoundedCompleteHoare       [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.joinCompact                    [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.mem_smythJoin                  [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.smyth_exists_isLUB_pair        [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.lemma_13_smyth                    [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.instBoundedCompleteSmyth       [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.not_isIdeal_sUnion_hoareWitness
                                                            [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.isLUB_sSup_hoareWitness        [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.sSup_hoareWitness_ne_bot       [propext, Classical.choice, Quot.sound]

`mem_sUnion_coe_iff` is axiom-free: it is a pair of `rintro`/`exact` steps over
`Set.mem_sUnion` and `Set.mem_image`, with no choice, no quotient and no
propositional extensionality. Everywhere else `Classical.choice` arrives through
`IdealCompletion`'s `idealSup`, whose `dite` branches on the undecidable
`Order.IsIdeal (genIdeal …)`, through the `open Classical in` that gives
`Finset.filter` and `Finset.image` their `Decidable` instances in `smythJoin`,
and — in the witness section — through `Set.Countable.to_subtype` behind
`Domain (Set ℕ)`. -/
