import ScottDomains.Powerdomain.Hoare
import ScottDomains.Powerdomain.Smyth
import ScottDomains.Powerdomain.Plotkin

/-!
# Lemma 13: bounded completeness of the upper and lower powerdomains

Gunter & Scott, *Semantic Domains* (Handbook of Theoretical Computer Science
Vol. B, 1990), §4.5:

> **Lemma 13** If `D` is bounded complete then so are the powerdomains `D♯` and
> `D♭`.

and §4.5's definition of the predicate, quoted in `ScottDomains/Domain.lean`:

> A poset `A` is said to be **bounded complete** if `A` has a least element and
> every bounded subset of `A` has a least upper bound.

## Which of the paper's symbols each conjunct is

The plan for this round writes the two powerdomains `D]` and `D[`; those are an
ASCII rendering of the paper's `D♯` and `D♭`, the **upper (Smyth)** and **lower
(Hoare)** powerdomains of §5.2, quoted verbatim in `Powerdomain/Smyth.lean`. So

* `lem13_hoare` is the paper's `D♭` — `ScottDomains.Hoare.Powerdomain`;
* `lem13_smyth` is the paper's `D♯` — `ScottDomains.Smyth.Powerdomain`.

There is no `lem13_plotkin`. The paper's third powerdomain is `D♮`, the convex
(Plotkin) one, and Lemma 13 does not name it: the convex powerdomain does not
preserve bounded completeness, which is why §6 moves to bifinite domains before
treating it. This file therefore proves Lemma 13 for exactly the two conjuncts
the paper states, and adds the `sSup`-level refutation for all three (below).

## The defect this round found, and what it does to the statement

`BoundedComplete` is stated in `Domain.lean` against the **ambient `sSup`**:

    isLUB_sSup_of_bddAbove : ∀ s, BddAbove s → IsLUB s (sSup s)

so it asserts two things at once — that a bounded set has a least upper bound
(the paper's Lemma 13) and that `sSup` computes it. For every powerdomain the
ambient `sSup` is `IdealCompletion.idealSup`, whose `dite` branches on
`Order.IsIdeal (⋃₀ …)` and returns `⊥` otherwise. That branch is **not** the
membership condition for the least upper bound: the least upper bound of a
family of ideals is the ideal *generated by* the union, and the union itself is
an ideal only when the family is directed. `IdealCompletion.lean`'s own module
docstring records the discrepancy from the other side — *Mathlib's is the ideal
generated by the union, this one is the union itself and `⊥` elsewhere*.

The consequence is measured, not asserted:
`not_boundedComplete_hoare`, `not_boundedComplete_smyth` and
`not_boundedComplete_plotkin` **prove the class-valued statement false** for all
three powerdomains of `P N`. The witness is the same in each case: the two
compact elements `{0}` and `{1}` of `P N` are incomparable, the pair of
principal ideals `↓{{0}}` and `↓{{1}}` is bounded above by `↓{{0,1}}`, and their
union is not directed — so `idealSup` returns `⊥`, which is not even an upper
bound. This is the third occurrence of the defect class that cost `ScottHom`
(r0006–r0011) and `Smash` (r0027) a repair; the fix belongs in
`IdealCompletion.lean`, which this round does not own.

The paper's Lemma 13 is **true** and is proved here in the paper's own words —
`BddAbove S → ∃ I, IsLUB S I`. Together with the `OrderBot` instance that
`IdealCompletion` already carries, that pair is exactly the quoted definition of
*bounded complete*, so nothing is weakened: `lem13_hoare` and `lem13_smyth` say
what §4.5 says. What they do not say is that `idealSup` computes the witness,
because it does not.

## How the two conjuncts are proved

One construction serves both. For a family `S` of ideals over a pre-order `A`
bounded above by an ideal `J`, put

    genIdeal S = {c ∈ A | c belongs to every ideal that contains every member of S}

— the intersection of all ideals above `S`. It is a lower set and contains `⊥`
for free. Directedness is the only content, and it is where boundedness is
spent: two members `a, b` of `genIdeal S` lie in `J`, so `J`'s own directedness
bounds the pair `{a, b}` in `A`; if bounded pairs of `A` have least upper
bounds, the least upper bound `c` of `{a, b}` lies in every ideal `K` above `S`
(because `K` bounds `a` and `b` by some `e ∈ K`, so `c ≤ e`, so `c ∈ K` by
downward closure) and hence in `genIdeal S`. Being the least ideal containing
every member of `S`, it is their least upper bound. No finite joins and no
transfinite construction are needed — only binary joins of **bounded** pairs.

That reduces each conjunct to a statement about the pre-order `Pf(K(D))`:

* **Hoare** (`hoare_exists_isLUB_pair`) — under `⊑♭` the join is the **union**,
  `u ∪ v`, and it exists unconditionally. Bounded completeness of `D` is never
  consumed, so `D♭` is bounded complete for every domain `D`; the hypothesis is
  kept because the paper states it.
* **Smyth** (`smyth_exists_isLUB_pair`) — under `⊑♯` the join of a **bounded**
  pair is `{a ⊔ b | a ∈ u, b ∈ v, {a,b} bounded}`, and here both halves of the
  hypothesis are spent: bounded completeness of `D` supplies `a ⊔ b`, and
  `isCompactElement_of_isLUB_pair` (`Domain.lean`) certifies that it is again
  compact, so the join is a point of `Pf(K(D))`. Boundedness of `{u, v}` is what
  makes the set non-empty, which the paper's `Pf` requires.

The Egli–Milner order admits no such join — `Plotkin.not_single_le_pair` already
shows `{a} ⊑ {a, b}` fails — which is the order-theoretic reason Lemma 13 names
only two of the three powerdomains.

## Statements

* `exists_isLUB_of_bddAbove_idealCompletion` — the general construction.
* `lem13_hoare`, `lem13_smyth` — Lemma 13, in the paper's wording.
* `not_boundedComplete_hoare`, `not_boundedComplete_smyth`,
  `not_boundedComplete_plotkin` — the refutation of the class-valued form, with
  the witness in `P N`.
-/

namespace ScottDomains.PowerdomainBC

universe u

/-! ## Least upper bounds of bounded families of ideals

Everything in this section is about an arbitrary pre-order `A` with a least
element; the two powerdomains are instances of it. -/

section IdealCompletionGeneral

variable {A : Type u} [Preorder A] [OrderBot A]

omit [OrderBot A] in
/-- Membership in the union that `idealSup` inspects, in terms of the family
rather than of its image under `SetLike.coe`. This is the body of
`IdealCompletion.mem_sSup_iff` with its directedness hypothesis stripped off —
that hypothesis is used there only to know the union is the supremum, not to
compute membership. -/
theorem mem_sUnion_coe_iff {S : Set (IdealCompletion A)} {x : A} :
    x ∈ ⋃₀ (SetLike.coe '' S) ↔ ∃ I ∈ S, x ∈ I := by
  constructor
  · rintro ⟨_, ⟨I, hI, rfl⟩, hx⟩
    exact ⟨I, hI, hx⟩
  · rintro ⟨I, hI, hx⟩
    exact ⟨(I : Set A), Set.mem_image_of_mem _ hI, hx⟩

/-- The **ideal generated by a family of ideals**: the intersection of every
ideal that lies above all of them. Stated as a comprehension over ideals rather
than as a closure under finite joins, because in a bare pre-order there are no
finite joins to close under — only joins of *bounded* pairs, and those enter the
directedness proof (`isIdeal_genIdeal`) instead. -/
def genIdeal (S : Set (IdealCompletion A)) : Set A :=
  {c | ∀ K : IdealCompletion A, (∀ I ∈ S, I ≤ K) → c ∈ K}

/-- `genIdeal S` is an ideal, provided `S` is bounded above and bounded pairs of
`A` have least upper bounds.

Lower-closedness and non-emptiness are free. Directedness is the whole content:
two members of `genIdeal S` lie in the bounding ideal `J`, which is directed, so
the pair is bounded in `A` and has a least upper bound `c`; and `c` lies in every
ideal `K` above `S`, since `K` already bounds the pair by some `e ∈ K` and
`c ≤ e`. -/
theorem isIdeal_genIdeal
    (hpair : ∀ a b : A, BddAbove ({a, b} : Set A) → ∃ c, IsLUB ({a, b} : Set A) c)
    {S : Set (IdealCompletion A)} (hS : BddAbove S) : Order.IsIdeal (genIdeal S) := by
  obtain ⟨J, hJ⟩ := hS
  have hmemJ : ∀ c ∈ genIdeal S, c ∈ J := fun _ hc => hc J fun _ hI => hJ hI
  refine ⟨?_, ⟨⊥, ?_⟩, ?_⟩
  · intro a b hba ha K hK
    exact K.lower hba (ha K hK)
  · intro K _
    exact IdealCompletion.bot_mem K
  · intro a ha b hb
    obtain ⟨d, hd, had, hbd⟩ := J.directed a (hmemJ a ha) b (hmemJ b hb)
    obtain ⟨c, hc⟩ := hpair a b ⟨d, by rintro x (rfl | rfl) <;> assumption⟩
    refine ⟨c, ?_, hc.1 (Set.mem_insert a {b}), hc.1 (Set.mem_insert_of_mem a rfl)⟩
    intro K hK
    obtain ⟨e, he, hae, hbe⟩ := K.directed a (ha K hK) b (hb K hK)
    exact K.lower (hc.2 (by rintro x (rfl | rfl) <;> assumption)) he

/-- **Every bounded family of ideals has a least upper bound**, provided bounded
pairs of the underlying pre-order do. This is the poset half of the paper's
*bounded complete*; the other half, a least element, is the `OrderBot` instance
`IdealCompletion` already carries.

The witness is `genIdeal S`, which is an upper bound because each member of `S`
is contained in every ideal above `S`, and least because any upper bound is one
of the ideals being intersected. -/
theorem exists_isLUB_of_bddAbove_idealCompletion
    (hpair : ∀ a b : A, BddAbove ({a, b} : Set A) → ∃ c, IsLUB ({a, b} : Set A) c)
    {S : Set (IdealCompletion A)} (hS : BddAbove S) : ∃ I : IdealCompletion A, IsLUB S I := by
  refine ⟨IdealCompletion.ofIdeal (isIdeal_genIdeal hpair hS).toIdeal, ?_, ?_⟩
  · exact fun I hI _ ha K hK => hK I hI ha
  · exact fun K hK _ ha => ha K fun _ hI => hK hI

/-! ### Where `idealSup` returns the wrong value

`sSup` on an ideal completion is total, so it must answer on families whose
union is not an ideal, and there it answers `⊥`. On a *directed* family that
never happens; on a merely *bounded* family it happens as soon as the family is
not directed, and then `⊥` is not even an upper bound. -/

/-- If the union of the family is not directed then `sSup` is `⊥`, by the
negative branch of `idealSup`'s `dite`. -/
theorem sSup_eq_bot_of_not_directedOn {S : Set (IdealCompletion A)}
    (h : ¬ DirectedOn (· ≤ ·) (⋃₀ (SetLike.coe '' S))) : sSup S = ⊥ := by
  classical
  have hnot : ¬ Order.IsIdeal (⋃₀ (SetLike.coe '' S)) := fun hI => h hI.Directed
  rw [IdealCompletion.sSup_eq_idealSup]
  simp only [IdealCompletion.idealSup, dif_neg hnot]

/-- **The class-valued `BoundedComplete` fails on any ideal completion with an
incomparable bounded pair.**

The hypotheses name a pair `a, b` of the pre-order that (i) is bounded above by
`t`, (ii) has no upper bound inside `↓a ∪ ↓b`, and (iii) whose first component is
not below `⊥`. Then `{↓a, ↓b}` is bounded above by `↓t`, its union is not
directed, so `sSup` of it is `⊥` — and `↓a ≤ ⊥` would force `a ≤ ⊥`.

Note what is and is not shown: the family *does* have a least upper bound (it is
`genIdeal` of it, by `exists_isLUB_of_bddAbove_idealCompletion` whenever the
pre-order supplies bounded joins). What fails is that `sSup` computes it. -/
theorem not_boundedComplete_of_not_directed_pair {a b t : A} (hat : a ≤ t) (hbt : b ≤ t)
    (hnd : ∀ w : A, (w ≤ a ∨ w ≤ b) → ¬ (a ≤ w ∧ b ≤ w)) (hbot : ¬ a ≤ (⊥ : A)) :
    ¬ BoundedComplete (IdealCompletion A) := by
  intro hbc
  have hbdd : BddAbove ({IdealCompletion.principal a, IdealCompletion.principal b} :
      Set (IdealCompletion A)) := by
    refine ⟨IdealCompletion.principal t, ?_⟩
    rintro _ (rfl | rfl)
    · exact IdealCompletion.principal_mono hat
    · exact IdealCompletion.principal_mono hbt
  have hnotdir : ¬ DirectedOn (· ≤ ·) (⋃₀ (SetLike.coe ''
      ({IdealCompletion.principal a, IdealCompletion.principal b} :
        Set (IdealCompletion A)))) := by
    intro hd
    obtain ⟨w, hw, haw, hbw⟩ :=
      hd a (mem_sUnion_coe_iff.mpr
            ⟨_, Set.mem_insert _ _, IdealCompletion.mem_principal_self a⟩)
        b (mem_sUnion_coe_iff.mpr
            ⟨_, Set.mem_insert_of_mem _ rfl, IdealCompletion.mem_principal_self b⟩)
    obtain ⟨I, hI, hwI⟩ := mem_sUnion_coe_iff.mp hw
    rcases hI with rfl | rfl
    · exact hnd w (Or.inl hwI) ⟨haw, hbw⟩
    · exact hnd w (Or.inr hwI) ⟨haw, hbw⟩
  have hlub := hbc.isLUB_sSup_of_bddAbove _ hbdd
  rw [sSup_eq_bot_of_not_directedOn hnotdir] at hlub
  exact hbot (IdealCompletion.principal_le_iff.mp (hlub.1 (Set.mem_insert _ _)))

end IdealCompletionGeneral

/-! ## `D♭`: the Hoare (lower) powerdomain

Under `⊑♭` the join is the union, and it needs no hypothesis at all: `u ∪ v` is
non-empty because `u` is, every element of `u` is below itself in `u ∪ v`, and an
upper bound of both `u` and `v` bounds each element of the union on the side it
came from. -/

section Hoare

open ScottDomains.Hoare

/-- The **union is the least upper bound** in `⟨Pf(A), ⊑♭⟩`, for *every* pair —
the Hoare pre-order is a join-semilattice, not merely a bounded-complete one.
This is the input `exists_isLUB_of_bddAbove_idealCompletion` consumes. -/
theorem hoare_exists_isLUB_pair {A : Type u} [Preorder A] (u v : Pf A) :
    ∃ c, IsLUB ({u, v} : Set (Pf A)) c := by
  classical
  obtain ⟨x₀, hx₀⟩ := u.toFinset_nonempty
  refine ⟨Pf.ofFinset (u.toFinset ∪ v.toFinset) ⟨x₀, Finset.mem_union_left _ hx₀⟩, ?_, ?_⟩
  · rintro w (rfl | rfl)
    · exact fun x hx => ⟨x, Finset.mem_union_left _ hx, le_rfl⟩
    · exact fun x hx => ⟨x, Finset.mem_union_right _ hx, le_rfl⟩
  · intro w hw x hx
    rcases Finset.mem_union.mp hx with h | h
    · exact hw (Set.mem_insert u {v}) x h
    · exact hw (Set.mem_insert_of_mem u rfl) x h

/-- **Lemma 13, the `D♭` conjunct** (Gunter & Scott §4.5): the lower powerdomain
of a bounded complete domain is bounded complete — every bounded subset of `D♭`
has a least upper bound, and `D♭` has a least element (its `OrderBot` instance).

`[BoundedComplete α]` is not consumed: `hoare_exists_isLUB_pair` supplies joins
for *every* pair of `Pf(K(D))`, so `D♭` is bounded complete for every domain `D`.
The hypothesis is retained because the paper states Lemma 13 that way; recording
that it is unused is the honest report of a strengthening, not a change of
statement. -/
theorem lem13_hoare (α : Type u) [CompletePartialOrder α] [Domain α] [BoundedComplete α]
    (S : Set (Hoare.Powerdomain α)) (hS : BddAbove S) : ∃ I, IsLUB S I :=
  exists_isLUB_of_bddAbove_idealCompletion (fun u v _ => hoare_exists_isLUB_pair u v) hS

end Hoare

/-! ## `D♯`: the Smyth (upper) powerdomain

Under `⊑♯` a join exists only for a **bounded** pair, and building it consumes
both halves of the paper's hypothesis on `D`: bounded completeness produces
`a ⊔ b` in `D`, and `isCompactElement_of_isLUB_pair` puts it back in `K(D)`. -/

section Smyth

open ScottDomains.Smyth

variable {D : Type u} [CompletePartialOrder D] [BoundedComplete D]

open Classical in
/-- The join of two compact elements of `D`, as a compact element: `a ⊔ b` when
the pair is bounded, and `⊥` otherwise. Total, so it can be mapped over a
`Finset`; the `⊥` branch is never reached below, because the product is filtered
by the same predicate the `dite` tests.

Compactness of the value is `isCompactElement_of_isLUB_pair` (`Domain.lean`),
which is stated for a bare `PartialOrder` with the least upper bound as a
hypothesis — exactly the shape bounded completeness hands it. -/
noncomputable def joinCompact (a b : ↥(compacts D)) : ↥(compacts D) :=
  if h : BddAbove ({(a : D), (b : D)} : Set D) then
    ⟨sSup ({(a : D), (b : D)} : Set D),
      isCompactElement_of_isLUB_pair a.2 b.2 (isLUB_sSup_of_bddAbove h)⟩
  else ⊥

theorem le_joinCompact_left {a b : ↥(compacts D)}
    (h : BddAbove ({(a : D), (b : D)} : Set D)) : a ≤ joinCompact a b := by
  classical
  rw [joinCompact, dif_pos h]
  exact (isLUB_sSup_of_bddAbove h).1 (Set.mem_insert _ _)

theorem le_joinCompact_right {a b : ↥(compacts D)}
    (h : BddAbove ({(a : D), (b : D)} : Set D)) : b ≤ joinCompact a b := by
  classical
  rw [joinCompact, dif_pos h]
  exact (isLUB_sSup_of_bddAbove h).1 (Set.mem_insert_of_mem _ rfl)

theorem joinCompact_le {a b c : ↥(compacts D)} (h : BddAbove ({(a : D), (b : D)} : Set D))
    (hac : a ≤ c) (hbc : b ≤ c) : joinCompact a b ≤ c := by
  classical
  rw [joinCompact, dif_pos h]
  exact (isLUB_sSup_of_bddAbove h).2 (by rintro x (rfl | rfl) <;> assumption)

open Classical in
/-- The candidate Smyth join of two finite sets of compacts: all the joins
`a ⊔ b` over pairs `a ∈ u`, `b ∈ v` that are bounded in `D`. Filtering by
boundedness is what keeps every member of the image a genuine join rather than
`joinCompact`'s `⊥` fallback. -/
noncomputable def smythJoin (u v : Finset ↥(compacts D)) : Finset ↥(compacts D) :=
  (Finset.filter (fun p : ↥(compacts D) × ↥(compacts D) =>
      BddAbove ({(p.1 : D), (p.2 : D)} : Set D)) (u ×ˢ v)).image
    (fun p => joinCompact p.1 p.2)

theorem mem_smythJoin {u v : Finset ↥(compacts D)} {c : ↥(compacts D)} :
    c ∈ smythJoin u v ↔ ∃ a ∈ u, ∃ b ∈ v,
      BddAbove ({(a : D), (b : D)} : Set D) ∧ c = joinCompact a b := by
  classical
  constructor
  · intro hc
    rw [smythJoin, Finset.mem_image] at hc
    obtain ⟨p, hp, hpc⟩ := hc
    rw [Finset.mem_filter, Finset.mem_product] at hp
    exact ⟨p.1, hp.1.1, p.2, hp.1.2, hp.2, hpc.symm⟩
  · rintro ⟨a, ha, b, hb, hbdd, rfl⟩
    rw [smythJoin, Finset.mem_image]
    refine ⟨(a, b), ?_, rfl⟩
    rw [Finset.mem_filter, Finset.mem_product]
    exact ⟨⟨ha, hb⟩, hbdd⟩

/-- **A bounded pair of `⟨Pf(K(D)), ⊑♯⟩` has a least upper bound**, namely
`smythJoin`. Boundedness is spent twice: once to know some pair `a ∈ u`, `b ∈ v`
is bounded in `D` — so the join set is non-empty, which the paper's `Pf`
requires — and once, for each element `c` of a competing upper bound, to bound
the pair it selects and place `a ⊔ b` below `c`. -/
theorem smyth_exists_isLUB_pair {u v : Basis D}
    (h : BddAbove ({u, v} : Set (Basis D))) : ∃ c, IsLUB ({u, v} : Set (Basis D)) c := by
  classical
  obtain ⟨w, hw⟩ := h
  have huw : u ≤ w := hw (Set.mem_insert _ _)
  have hvw : v ≤ w := hw (Set.mem_insert_of_mem _ rfl)
  -- Every element of an upper bound selects a bounded pair, hence a member of the join.
  have hsel : ∀ {z : Basis D}, u ≤ z → v ≤ z → ∀ c ∈ z.toFinset,
      ∃ e ∈ smythJoin u.toFinset v.toFinset, e ≤ c := by
    intro z huz hvz c hc
    obtain ⟨a, ha, hac⟩ := huz c hc
    obtain ⟨b, hb, hbc⟩ := hvz c hc
    have hbdd : BddAbove ({(a : D), (b : D)} : Set D) :=
      ⟨(c : D), by rintro x (rfl | rfl) <;> assumption⟩
    exact ⟨joinCompact a b, mem_smythJoin.mpr ⟨a, ha, b, hb, hbdd, rfl⟩,
      joinCompact_le hbdd hac hbc⟩
  obtain ⟨c₀, hc₀⟩ := w.nonempty'
  obtain ⟨e₀, he₀, -⟩ := hsel huw hvw c₀ hc₀
  refine ⟨⟨smythJoin u.toFinset v.toFinset, ⟨e₀, he₀⟩⟩, ?_, ?_⟩
  · rintro z (rfl | rfl)
    · intro c hc
      obtain ⟨a, ha, b, hb, hbdd, rfl⟩ := mem_smythJoin.mp hc
      exact ⟨a, ha, le_joinCompact_left hbdd⟩
    · intro c hc
      obtain ⟨a, ha, b, hb, hbdd, rfl⟩ := mem_smythJoin.mp hc
      exact ⟨b, hb, le_joinCompact_right hbdd⟩
  · intro z hz
    exact hsel (hz (Set.mem_insert _ _)) (hz (Set.mem_insert_of_mem _ rfl))

/-- **Lemma 13, the `D♯` conjunct** (Gunter & Scott §4.5): the upper powerdomain
of a bounded complete domain is bounded complete — every bounded subset of `D♯`
has a least upper bound, and `D♯` has a least element (its `OrderBot` instance).

Unlike the `D♭` conjunct, both hypotheses on `D` are consumed:
`[BoundedComplete α]` builds `a ⊔ b` and `[Domain α]` is what makes `Basis α` a
countable pre-order in the first place. -/
theorem lem13_smyth (α : Type u) [CompletePartialOrder α] [Domain α] [BoundedComplete α]
    (S : Set (Smyth.Powerdomain α)) (hS : BddAbove S) : ∃ I, IsLUB S I :=
  exists_isLUB_of_bddAbove_idealCompletion (fun _ _ h => smyth_exists_isLUB_pair h) hS

end Smyth

/-! ## The refutation of the class-valued form

`P N` is the witness. Its compact elements are the finite subsets of `ℕ`
(`Powerset.lean`), so `{0}` and `{1}` are compact and incomparable while
`{0, 1}` is compact and above both — everything the general refutation asks
for. -/

section Refutation

/-- `{0}`, as a compact element of `P N`. -/
def k0 : ↥(compacts (Set ℕ)) := ⟨{0}, isCompactElement_iff_finite.mpr (Set.finite_singleton 0)⟩

/-- `{1}`, as a compact element of `P N`. -/
def k1 : ↥(compacts (Set ℕ)) := ⟨{1}, isCompactElement_iff_finite.mpr (Set.finite_singleton 1)⟩

/-- `{0, 1}`, as a compact element of `P N` — the bound the two others lack. -/
def k01 : ↥(compacts (Set ℕ)) :=
  ⟨{0, 1}, isCompactElement_iff_finite.mpr ((Set.finite_singleton 1).insert 0)⟩

theorem k0_le_k01 : k0 ≤ k01 := by
  intro x hx
  rw [show x = 0 from hx]
  exact Set.mem_insert 0 {1}

theorem k1_le_k01 : k1 ≤ k01 := by
  intro x hx
  rw [show x = 1 from hx]
  exact Set.mem_insert_of_mem 0 rfl

theorem not_k0_le_k1 : ¬ k0 ≤ k1 := by
  intro h
  have h0 : (0 : ℕ) ∈ ({1} : Set ℕ) := h (show (0 : ℕ) ∈ ({0} : Set ℕ) from rfl)
  exact absurd h0 (by simp)

theorem not_k1_le_k0 : ¬ k1 ≤ k0 := by
  intro h
  have h1 : (1 : ℕ) ∈ ({0} : Set ℕ) := h (show (1 : ℕ) ∈ ({1} : Set ℕ) from rfl)
  exact absurd h1 (by simp)

theorem not_k0_le_bot : ¬ k0 ≤ (⊥ : ↥(compacts (Set ℕ))) := by
  intro h
  have h0 : (0 : ℕ) ∈ (⊥ : Set ℕ) := h (show (0 : ℕ) ∈ ({0} : Set ℕ) from rfl)
  exact absurd h0 (by simp)

/-! ### `D♭` -/

/-- The singleton `{k}` as a point of `⟨Pf(K(P N)), ⊑♭⟩`. -/
def hoarePt (k : ↥(compacts (Set ℕ))) : Hoare.Pf ↥(compacts (Set ℕ)) :=
  Hoare.Pf.ofFinset {k} (Finset.singleton_nonempty k)

theorem hoarePt_le_hoarePt {j k : ↥(compacts (Set ℕ))} (h : j ≤ k) : hoarePt j ≤ hoarePt k := by
  intro x hx
  rw [show x = j from Finset.mem_singleton.mp hx]
  exact ⟨k, Finset.mem_singleton_self k, h⟩

/-- **`sSup` does not compute least upper bounds in `D♭`.** The bounded pair
`↓{{0}}`, `↓{{1}}` has a union that is not directed: an upper bound of both
inside `↓{{0}} ∪ ↓{{1}}` lies below one of the two singletons and above the
other, which forces `{0}` and `{1}` to be comparable.

The paper's Lemma 13 is unaffected — `lem13_hoare` proves it — and the least
upper bound of this very pair is `genIdeal` of it. What is refuted is
`Domain.lean`'s class, which additionally asserts that the ambient `sSup` is that
least upper bound. -/
theorem not_boundedComplete_hoare : ¬ BoundedComplete (Hoare.Powerdomain (Set ℕ)) := by
  refine not_boundedComplete_of_not_directed_pair (a := hoarePt k0) (b := hoarePt k1)
    (t := hoarePt k01) (hoarePt_le_hoarePt k0_le_k01) (hoarePt_le_hoarePt k1_le_k01) ?_ ?_
  · rintro w (hw | hw) ⟨h0, h1⟩
    · obtain ⟨y, hy, h1y⟩ := h1 k1 (Finset.mem_singleton_self k1)
      obtain ⟨z, hz, hyz⟩ := hw y hy
      exact not_k1_le_k0 (h1y.trans (hyz.trans_eq (Finset.mem_singleton.mp hz)))
    · obtain ⟨y, hy, h0y⟩ := h0 k0 (Finset.mem_singleton_self k0)
      obtain ⟨z, hz, hyz⟩ := hw y hy
      exact not_k0_le_k1 (h0y.trans (hyz.trans_eq (Finset.mem_singleton.mp hz)))
  · intro h
    obtain ⟨y, hy, h0y⟩ := h k0 (Finset.mem_singleton_self k0)
    exact not_k0_le_bot (h0y.trans_eq (Hoare.Pf.mem_bot.mp hy))

/-! ### `D♯` -/

theorem smythPt_le_smythPt {j k : ↥(compacts (Set ℕ))} (h : j ≤ k) :
    Smyth.Basis.singleton (D := Set ℕ) j ≤ Smyth.Basis.singleton k :=
  Smyth.Basis.singleton_le_singleton.mpr h

/-- **`sSup` does not compute least upper bounds in `D♯`.** Same witness as the
Hoare case, read through the upper ordering: an upper bound of `{{0}}` and
`{{1}}` inside the union of the two principal ideals has some element below
`{0}`, and every one of its elements is above `{1}`. -/
theorem not_boundedComplete_smyth : ¬ BoundedComplete (Smyth.Powerdomain (Set ℕ)) := by
  refine not_boundedComplete_of_not_directed_pair
    (a := Smyth.Basis.singleton (D := Set ℕ) k0) (b := Smyth.Basis.singleton (D := Set ℕ) k1)
    (t := Smyth.Basis.singleton (D := Set ℕ) k01)
    (smythPt_le_smythPt k0_le_k01) (smythPt_le_smythPt k1_le_k01) ?_ ?_
  · rintro w (hw | hw) ⟨h0, h1⟩
    · obtain ⟨y, hy, hyk0⟩ := hw k0 (Finset.mem_singleton_self k0)
      obtain ⟨z, hz, hzy⟩ := h1 y hy
      exact not_k1_le_k0 (((Finset.mem_singleton.mp hz) ▸ hzy).trans hyk0)
    · obtain ⟨y, hy, hyk1⟩ := hw k1 (Finset.mem_singleton_self k1)
      obtain ⟨z, hz, hzy⟩ := h0 y hy
      exact not_k0_le_k1 (((Finset.mem_singleton.mp hz) ▸ hzy).trans hyk1)
  · intro h
    obtain ⟨y, hy, hyb⟩ := h (⊥ : ↥(compacts (Set ℕ))) (Finset.mem_singleton_self _)
    exact not_k0_le_bot ((Finset.mem_singleton.mp hy) ▸ hyb)

/-! ### `D♮`

The convex powerdomain is not named by Lemma 13, and no positive statement about
it is claimed here. The `sSup` defect is nonetheless the same defect, so it is
recorded with the same witness. -/

theorem plotkinPt_le_plotkinPt {j k : ↥(compacts (Set ℕ))} (h : j ≤ k) :
    Plotkin.FinCompacts.single (D := Set ℕ) j ≤ Plotkin.FinCompacts.single k :=
  ⟨fun _ ha => ⟨k, rfl, (Plotkin.FinCompacts.mem_single.mp ha) ▸ h⟩,
   fun _ hb => ⟨j, rfl, (Plotkin.FinCompacts.mem_single.mp hb) ▸ h⟩⟩

/-- **`sSup` does not compute least upper bounds in `D♮` either.** The Hoare
conjunct of Egli–Milner alone already forces the contradiction, so the witness is
unchanged. Lemma 13 does not claim the convex powerdomain is bounded complete, so
this statement is a record of the `sSup` defect and not a refutation of the
paper. -/
theorem not_boundedComplete_plotkin : ¬ BoundedComplete (Plotkin.Powerdomain (Set ℕ)) := by
  refine not_boundedComplete_of_not_directed_pair
    (a := Plotkin.FinCompacts.single (D := Set ℕ) k0)
    (b := Plotkin.FinCompacts.single (D := Set ℕ) k1)
    (t := Plotkin.FinCompacts.single (D := Set ℕ) k01)
    (plotkinPt_le_plotkinPt k0_le_k01) (plotkinPt_le_plotkinPt k1_le_k01) ?_ ?_
  · rintro w (hw | hw) ⟨h0, h1⟩
    · obtain ⟨y, hy, h1y⟩ := h1.1 k1 rfl
      obtain ⟨z, hz, hyz⟩ := hw.1 y hy
      exact not_k1_le_k0 (h1y.trans (hyz.trans_eq (Plotkin.FinCompacts.mem_single.mp hz)))
    · obtain ⟨y, hy, h0y⟩ := h0.1 k0 rfl
      obtain ⟨z, hz, hyz⟩ := hw.1 y hy
      exact not_k0_le_k1 (h0y.trans (hyz.trans_eq (Plotkin.FinCompacts.mem_single.mp hz)))
  · intro h
    obtain ⟨y, hy, h0y⟩ := h.1 k0 rfl
    exact not_k0_le_bot (h0y.trans_eq (Plotkin.FinCompacts.mem_single.mp hy))

end Refutation

end ScottDomains.PowerdomainBC

/- Axiom audit, by `#print axioms` (run, then removed so the build emits no
`info` lines). No declaration depends on `sorryAx`.

  ScottDomains.PowerdomainBC.mem_sUnion_coe_iff          [no axioms]
  ScottDomains.PowerdomainBC.isIdeal_genIdeal            [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.exists_isLUB_of_bddAbove_idealCompletion
                                                         [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.sSup_eq_bot_of_not_directedOn
                                                         [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.not_boundedComplete_of_not_directed_pair
                                                         [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.hoare_exists_isLUB_pair     [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.lem13_hoare                 [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.joinCompact                 [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.mem_smythJoin               [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.smyth_exists_isLUB_pair     [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.lem13_smyth                 [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.not_boundedComplete_hoare   [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.not_boundedComplete_smyth   [propext, Classical.choice, Quot.sound]
  ScottDomains.PowerdomainBC.not_boundedComplete_plotkin [propext, Classical.choice, Quot.sound]

`mem_sUnion_coe_iff` is axiom-free: it is a pair of `rintro`/`exact` steps over
`Set.mem_sUnion` and `Set.mem_image`, with no choice, no quotient and no
propositional extensionality. Everywhere else `Classical.choice` arrives through
`IdealCompletion`'s `idealSup`, whose `dite` branches on the undecidable
`Order.IsIdeal`, through the `open Classical in` that gives `Finset.filter` and
`Finset.image` their `Decidable` instances in `smythJoin`, and — in the
refutations — through `Set.Countable.to_subtype` behind `Domain (Set ℕ)`. -/
