/-
  Interpreting the λ-Calculus in Domain-Valued Random Variables —
  the reflexive-dcpo model of the untyped λ-calculus (Section 4)

  Faithful to:
    R. Furber, R. Mardare, P. Panangaden, D. Scott,
    "Interpreting the λ-Calculus in Domain-Valued Random Variables",
    Logical Methods in Computer Science / preprint, 2021.

  Source text extracted from:
    DanaScottPapers/Furber-Mardare-Panangaden-Scott-2021-...-Random-Variables.txt

  Auto-generated faithful skeleton (core Lean 4 only; no Mathlib).

  The paper's overarching contribution is a Boolean-valued / random-variable
  interpretation of the untyped λ-calculus.  Most of it (A-valued setoids,
  the topos Mod₀(A), Boolean-valued set theory Vᴬ) is heavy sheaf and
  topos-theoretic machinery outside a core-Lean skeleton.  We transcribe the part
  that is self-contained and genuinely formalizable: Section 4's classical
  domain-theoretic model of the untyped λ-calculus in a *reflexive dcpo*.

  Transcribed items:
    * Definition 4.1  — reflexive dcpo (D, ·, lam), a retract [D→D] ◁ D.
    * Definition 4.2  — the language Λ(D, Var, K) as an inductive family.
    * Definition 4.5  — the equational theory λ as an inductive relation.
    * Definition 4.7  — the interpretation ⟦M⟧ρ of a term in D.
    * Barendregt 5.4.4 — soundness of the interpretation (target).
-/

namespace InterpretingLambda

/-! ## Definition 4.1 — Reflexive dcpo

    "A reflexive dcpo is a triple (D, fun, lam), where D is a dcpo with
     bottom and fun : D → [D→D], lam : [D→D] → D are Scott-continuous maps
     making [D→D] a retract of D, i.e. fun ∘ lam = id.  … equivalently a
     triple (D, ·, lam) … such that for each f and d, lam(f) · d = f(d)."

    We use the uncurried algebraic form (D, ·, lam).  The dcpo order and
    bottom are recorded for faithfulness; directed-completeness and Scott-
    continuity of `app`/`lam` are the standard side conditions (they are not
    needed to *define* the interpretation, only for the fixed-point theory).
    The load-bearing law is the retract equation, which yields β. -/
class ReflexiveDcpo (D : Type) where
  /-- The dcpo order ≤. -/
  le : D → D → Prop
  le_refl : ∀ d, le d d
  le_trans : ∀ {a b c}, le a b → le b c → le a c
  le_antisymm : ∀ {a b}, le a b → le b a → a = b
  /-- Bottom element ⊥ of the dcpo. -/
  bot : D
  bot_le : ∀ d, le bot d
  /-- Application `·` : the uncurried `fun`. -/
  app : D → D → D
  /-- `lam` : the section of `fun` picking a point of `D` for each map. -/
  lam : (D → D) → D
  /-- The retract law `fun ∘ lam = id`, uncurried as `lam(f) · d = f(d)`.
      This single equation is what makes β-reduction sound. -/
  retract : ∀ (f : D → D) (d : D), app (lam f) d = f d

/-- A reflexive dcpo is *extensional* iff additionally `lam ∘ fun = id`.
    In the uncurried presentation this says every point is the λ of its own
    application map. -/
def Extensional (D : Type) [R : ReflexiveDcpo D] : Prop :=
  ∀ d : D, R.lam (fun e => R.app d e) = d

/-! ## Definition 4.2 — the language Λ(D, Var, K)

    Variables are drawn from `Var`; we use `Nat`.  Constants are drawn from a
    set `K` (here an arbitrary type of constant symbols).  Pure λ-terms are
    `Term Empty` (the case K = ∅), matching Scott's `Λ(Var)`. -/
inductive Term (K : Type) where
  | var   : Nat → Term K
  | const : K → Term K
  | app   : Term K → Term K → Term K
  | lam   : Nat → Term K → Term K

/-- Pure λ-terms `Λ(Var)` — the constant-free fragment. -/
abbrev PureTerm := Term Empty

/-- Free variables of a term (`fv(M)`), defined as usual. -/
def fv {K : Type} : Term K → List Nat
  | .var x    => [x]
  | .const _  => []
  | .app M N  => fv M ++ fv N
  | .lam x M  => (fv M).filter (fun y => decide (y ≠ x))

/-- Naive (non-capture-avoiding) substitution `M[x := N]`.  Definition 4.5(i)
    requires *capture-avoiding* substitution; making that faithful needs an
    α-conversion discipline (bound variables renamed apart from `fv N`).
    We provide the naive version as a placeholder and flag the gap. -/
-- TODO: replace with capture-avoiding substitution (rename bound `y` off `fv N`).
def subst {K : Type} (x : Nat) (N : Term K) : Term K → Term K
  | .var y    => if y = x then N else .var y
  | .const k  => .const k
  | .app M P  => .app (subst x N M) (subst x N P)
  | .lam y M  => if y = x then .lam y M else .lam y (subst x N M)

/-! ## Definition 4.5 — the equational theory λ

    Sentences are equations `M = N`.  The theory λ is generated by β
    together with the equivalence- and congruence-rules.  We encode
    `λ ⊢ M = N` as an inductive relation `Eq`. -/
inductive Conv {K : Type} : Term K → Term K → Prop
  /-- (i) β: `(λx.M) N = M[x := N]`. -/
  | beta   (x : Nat) (M N : Term K) : Conv (.app (.lam x M) N) (subst x N M)
  /-- (ii) reflexivity. -/
  | refl   (M : Term K) : Conv M M
  /-- (iii) symmetry. -/
  | symm   {M N : Term K} : Conv M N → Conv N M
  /-- (iv) transitivity. -/
  | trans  {M N L : Term K} : Conv M N → Conv N L → Conv M L
  /-- (v) right congruence for application. -/
  | appL   {M N : Term K} (Z : Term K) : Conv M N → Conv (.app M Z) (.app N Z)
  /-- (vi) left congruence for application. -/
  | appR   {M N : Term K} (Z : Term K) : Conv M N → Conv (.app Z M) (.app Z N)
  /-- (vii) ξ: congruence under λ-abstraction. -/
  | xi     {M N : Term K} (x : Nat) : Conv M N → Conv (.lam x M) (.lam x N)

/-- `M ≡λ N` : the equation `M = N` is derivable in the theory λ. -/
scoped notation:50 M " ≡λ " N => Conv M N

/-! ## Definition 4.7 — the interpretation ⟦M⟧ρ

    A valuation ρ : Var → D (here total, `Nat → D`).  A choice of constants
    is a map `κ : K → D` giving each constant symbol its value in `D`.

        ⟦x⟧ρ    = ρ(x)
        ⟦k⟧ρ    = κ(k)
        ⟦M N⟧ρ  = ⟦M⟧ρ · ⟦N⟧ρ
        ⟦λx.M⟧ρ = lam (λ d. ⟦M⟧ρ(x := d)). -/

/-- `ρ(x := d)`: update the valuation `ρ` to send `x` to `d`. -/
def update {D : Type} (ρ : Nat → D) (x : Nat) (d : D) : Nat → D :=
  fun y => if y = x then d else ρ y

/-- Definition 4.7, the interpretation of a term in a reflexive dcpo `D`. -/
def interp {K D : Type} [R : ReflexiveDcpo D] (κ : K → D) :
    (Nat → D) → Term K → D
  | ρ, .var x    => ρ x
  | _, .const k  => κ k
  | ρ, .app M N  => R.app (interp κ ρ M) (interp κ ρ N)
  | ρ, .lam x M  => R.lam (fun d => interp κ (update ρ x d) M)

/-- The β-rule holds *semantically and unconditionally* in any reflexive
    dcpo: `⟦(λx.M) N⟧ρ = ⟦M⟧(ρ(x := ⟦N⟧ρ))`.  This is a direct application
    of the retract law and needs no substitution lemma. -/
theorem interp_beta {K D : Type} [R : ReflexiveDcpo D] (κ : K → D)
    (ρ : Nat → D) (x : Nat) (M N : Term K) :
    interp κ ρ (.app (.lam x M) N)
      = interp κ (update ρ x (interp κ ρ N)) M := by
  show R.app (R.lam (fun d => interp κ (update ρ x d) M)) (interp κ ρ N) = _
  rw [R.retract]

/-! ## Soundness (Barendregt, Theorem 5.4.4)

    "for all M, N ∈ Λ(D, Var), if λ ⊢ M = N then for all valuations ρ,
     ⟦M⟧ρ = ⟦N⟧ρ."

    The β-case reduces (via `interp_beta`) to the *substitution lemma*
    `⟦M[x := N]⟧ρ = ⟦M⟧(ρ(x := ⟦N⟧ρ))`, which holds only for capture-avoiding
    substitution.  Since `subst` above is the naive version, we state the
    theorem as a target rather than assert an unsound proof. -/
def soundness (K D : Type) [ReflexiveDcpo D] (κ : K → D) : Prop :=
  ∀ (M N : Term K), (M ≡λ N) → ∀ ρ : Nat → D, interp κ ρ M = interp κ ρ N

-- TODO: prove `soundness` once `subst` is made capture-avoiding and the
-- substitution lemma `⟦M[x:=N]⟧ρ = ⟦M⟧(ρ(x:=⟦N⟧ρ))` is established.  All
-- rules except `beta` follow by structural induction using `interp_beta`
-- and congruence of `interp`.

end InterpretingLambda
