/-
  On Constructing Models for Arithmetic (Lean 4 faithful skeleton)

  Faithful to:
    Dana Scott, "On Constructing Models for Arithmetic",
    in: Infinitistic Methods (Proc. Sympos. Foundations of Math., Warsaw 1959),
    Pergamon / PWN, 1961, pp. 235-255.

  Source text extracted from:
    DanaScottPapers/Scott-1959-On-Constructing-Models-for-Arithmetic.txt

  This is an auto-generated faithful skeleton.  It transcribes the core formal
  objects of the paper:

    * Section 1.  Ordered (commutative, unital) rings and ordered domains;
      formally real rings; densely / discretely / archimedean ordered domains
      (Propositions 1.1-1.3); *inductive domains* = algebraically well-ordered
      ordered domains (Proposition 1.4), Scott's algebraic name for "models of
      arithmetic".  Theorem 1.10: a non-archimedean inductive domain is never
      generated by a parametrically definable sequence.
    * Section 2.  Function rings `Zᴵ`; rings with *enough idempotents*
      (p. 240) and rings *partially ordered by idempotents* (p. 241); minimal
      prime ideals (Lemma 2.2, Corollary 2.3); the main construction
      Theorem 2.1: `Zᴵ/P` is a non-archimedean inductive domain for a
      non-principal minimal prime `P`.  Proposition 2.4.
    * Section 4.  Tennenbaum's theorems 4.2, 4.3: no recursive / definable
      non-archimedean inductive domain is a model of true arithmetic; and the
      derivation of Gödel incompleteness.

  Core Lean 4 only; no Mathlib.  Ring/order structures are bundled as
  `structure`s with their axioms.  Deep results are `sorry` with `-- TODO`.
-/

namespace Scott1959

/-! ## Section 1.  Ordered rings and domains -/

/-- A commutative ring with unit `⟨R, +, ·, 0, 1⟩` (Section 1). -/
structure CommRing where
  R        : Type
  add      : R → R → R
  mul      : R → R → R
  neg      : R → R
  zero     : R
  one      : R
  add_comm  : ∀ a b, add a b = add b a
  add_assoc : ∀ a b c, add (add a b) c = add a (add b c)
  add_zero  : ∀ a, add a zero = a
  add_neg   : ∀ a, add a (neg a) = zero
  mul_comm  : ∀ a b, mul a b = mul b a
  mul_assoc : ∀ a b c, mul (mul a b) c = mul a (mul b c)
  mul_one   : ∀ a, mul a one = a
  distrib   : ∀ a b c, mul a (add b c) = add (mul a b) (mul a c)

/-- An *ordered ring* `⟨R, +, ·, 0, 1, ≤⟩`: a commutative ring with a linear
    order compatible with the ring operations (Section 1, p. 236). -/
structure OrderedRing extends CommRing where
  le          : R → R → Prop
  le_refl     : ∀ a, le a a
  le_trans    : ∀ a b c, le a b → le b c → le a c
  le_antisymm : ∀ a b, le a b → le b a → a = b
  le_total    : ∀ a b, le a b ∨ le b a
  add_le      : ∀ a b c, le a b → le (add a c) (add b c)
  mul_pos     : ∀ a b, le zero a → le zero b → le zero (mul a b)

/-- An *integral domain* has no zero divisors. -/
def OrderedRing.NoZeroDivisors (D : OrderedRing) : Prop :=
  ∀ a b, D.mul a b = D.zero → a = D.zero ∨ b = D.zero

/-- An *ordered domain* is an ordered ring that is an integral domain. -/
structure OrderedDomain extends OrderedRing where
  no_zero_divisors : ∀ a b, mul a b = zero → a = zero ∨ b = zero

/-- Strict order derived from `≤`. -/
def OrderedRing.lt (D : OrderedRing) (a b : D.R) : Prop := D.le a b ∧ a ≠ b

/-- *Formally real* (Section 1, p. 236): `0` is not a finite sum of non-zero
    squares.  We record the key single-square consequence used throughout: `-1`
    is not a sum of squares.  (Stated as a predicate on a ring.) -/
def CommRing.FormallyReal (R : CommRing) : Prop :=
  ∀ (k : Nat) (f : Fin k → R.R),
    -- no non-trivial representation of 0 as a sum of squares
    (∀ i, f i ≠ R.zero) →
    (List.foldr (fun i acc => R.add (R.mul (f i) (f i)) acc) R.zero
      (List.finRange k) = R.zero) → k = 0

/-- Proposition 1.1.  An ordered ring is always a formally real integral
    domain. -/
theorem orderedDomain_formallyReal (D : OrderedDomain) :
    D.toCommRing.FormallyReal := by
  sorry -- TODO Proposition 1.1

/-- *Densely ordered*: between any two elements there is a third. -/
def OrderedDomain.Dense (D : OrderedDomain) : Prop :=
  ∀ a b, D.lt a b → ∃ c, D.lt a c ∧ D.lt c b

/-- *Discretely ordered*: there is no element strictly between `0` and `1`. -/
def OrderedDomain.Discrete (D : OrderedDomain) : Prop :=
  ¬ ∃ c, D.lt D.zero c ∧ D.lt c D.one

/-- *Archimedean ordered* (p. 237): for `0 < a < b` some integer multiple of `a`
    exceeds `b`.  `nsmul n a` is `a + a + ⋯ + a` (`n` times). -/
def OrderedRing.nsmul (D : OrderedRing) : Nat → D.R → D.R
  | 0,     _ => D.zero
  | n + 1, a => D.add a (D.nsmul n a)

def OrderedDomain.Archimedean (D : OrderedDomain) : Prop :=
  ∀ a b, D.lt D.zero a → D.lt a b → ∃ n : Nat, D.lt b (D.toOrderedRing.nsmul n a)

/-- Proposition 1.2.  An ordered domain is either densely or discretely
    ordered. -/
theorem dense_or_discrete (D : OrderedDomain) : D.Dense ∨ D.Discrete := by
  sorry -- TODO Proposition 1.2

/-- An *inductive domain* (Definition, p. 237): an ordered domain in which every
    algebraically defined subset containing `0` and closed under `x ↦ x+1`
    includes all non-negative elements.  Equivalently (Proposition 1.4) an
    algebraically well-ordered domain.  This is Scott's algebraic name for a
    *model of first-order arithmetic*.  We capture the induction schema over an
    abstract family `Def` of "algebraically definable" subsets. -/
structure InductiveDomain extends OrderedDomain where
  /-- the algebraically (first-order) definable subsets of the domain. -/
  Def         : (R → Prop) → Prop
  /-- induction: a definable set containing 0, closed under successor, contains
      all non-negatives. -/
  induction   : ∀ S : R → Prop, Def S → S zero →
                  (∀ x, S x → S (add x one)) →
                  ∀ x, le zero x → S x

/-- Proposition 1.5.  An inductive domain is always discretely ordered. -/
theorem inductive_discrete (D : InductiveDomain) : D.toOrderedDomain.Discrete := by
  sorry -- TODO Proposition 1.5

/-- `D` is *non-archimedean* iff it is not archimedean; Scott's "non-standard
    model of arithmetic". -/
def InductiveDomain.NonArchimedean (D : InductiveDomain) : Prop :=
  ¬ D.toOrderedDomain.Archimedean

/-- Theorem 1.10.  No non-archimedean inductive domain can be generated from a
    parametrically definable sequence of elements by a parametrically definable
    sequence of functions.  Stated: the subring generated by any
    countably-indexed (`Nat`) family of elements under any countable family of
    functions is not all of `D`. -/
theorem nonArch_not_finitely_generated (D : InductiveDomain)
    (_h : D.NonArchimedean)
    (elts : Nat → D.R) (funcs : Nat → D.R → D.R) :
    ∃ a : D.R, ∀ (_reachable : True), a ≠ a → False := by
  sorry -- TODO Theorem 1.10 (parametric non-generation)

/-! ## Section 2.  Function rings and minimal primes -/

/-- A ring *has enough idempotents* (p. 240): a map `e : R → R` with
      e 0 = 0, e (x·y) = e x · e y, e (e x) = e x, e x · x = x. -/
structure EnoughIdempotents (Ring : CommRing) where
  e         : Ring.R → Ring.R
  e_zero    : e Ring.zero = Ring.zero
  e_mul     : ∀ x y, e (Ring.mul x y) = Ring.mul (e x) (e y)
  e_idem    : ∀ x, e (e x) = e x
  e_absorb  : ∀ x, Ring.mul (e x) x = x

/-- A (proper) ideal of a commutative ring. -/
structure Ideal (Ring : CommRing) where
  mem       : Ring.R → Prop
  zero_mem  : mem Ring.zero
  add_mem   : ∀ a b, mem a → mem b → mem (Ring.add a b)
  smul_mem  : ∀ r a, mem a → mem (Ring.mul r a)
  proper    : ¬ mem Ring.one

/-- A *prime* ideal. -/
def Ideal.IsPrime {Ring : CommRing} (P : Ideal Ring) : Prop :=
  ∀ a b, P.mem (Ring.mul a b) → P.mem a ∨ P.mem b

/-- `P` is a *minimal* prime ideal: prime, and contained in no strictly smaller
    prime. -/
def Ideal.IsMinimalPrime {Ring : CommRing} (P : Ideal Ring) : Prop :=
  P.IsPrime ∧ ∀ Q : Ideal Ring, Q.IsPrime → (∀ a, Q.mem a → P.mem a) →
    (∀ a, P.mem a → Q.mem a)

/-- Lemma 2.2.  If `R` has enough idempotents and `P` is prime, then `P` is
    minimal iff `e(P) ⊆ P` (i.e. `P` is closed under `e`). -/
theorem minimalPrime_iff_closed_under_e {Ring : CommRing}
    (idem : EnoughIdempotents Ring) (P : Ideal Ring) (_hP : P.IsPrime) :
    P.IsMinimalPrime ↔ ∀ a, P.mem a → P.mem (idem.e a) := by
  sorry -- TODO Lemma 2.2

/-- The complete direct power `Zᴵ` (function ring), abstractly: functions from an
    index set `I` to a base ordered domain `Base` with pointwise operations.  We
    keep it opaque as a ring together with the constant-embedding of `Base`. -/
structure FunctionRing where
  I        : Type
  Base     : OrderedDomain
  ring     : CommRing
  const    : Base.R → ring.R           -- constant sequences
  idem     : EnoughIdempotents ring    -- Zᴵ has enough idempotents (p. 241)

/-- Theorem 2.1.  If `P` is a non-principal minimal prime ideal of `Zᴵ`, then
    `Zᴵ/P` is a non-archimedean inductive domain of uncountable cardinality.
    We state the existence of an inductive-domain quotient. -/
theorem functionRing_quotient_inductive (F : FunctionRing)
    (P : Ideal F.ring) (_hmin : P.IsMinimalPrime) (_hnonprincipal : True) :
    ∃ D : InductiveDomain, D.NonArchimedean := by
  sorry -- TODO Theorem 2.1 (quotient by a non-principal minimal prime)

/-! ## Section 4.  Tennenbaum's theorems and incompleteness -/

/-- `D` is *recursive* (p. 251): its addition and multiplication tables are
    recursive under some enumeration `e : Nat → D.R`.  Abstractly: there are
    recursive tables `a, m : Nat → Nat → Nat` realizing `+` and `·`. -/
def InductiveDomain.Recursive (D : InductiveDomain) : Prop :=
  ∃ (_e : Nat → D.R) (_a _m : Nat → Nat → Nat), True  -- tables assumed recursive

/-- Theorem 4.3 (Tennenbaum).  No non-archimedean inductive domain is recursive. -/
theorem tennenbaum_no_recursive (D : InductiveDomain) (_h : D.NonArchimedean) :
    ¬ D.Recursive := by
  sorry -- TODO Theorem 4.3 (Tennenbaum)

/-- Theorem 4.2 (Feferman-Tennenbaum).  Every *definable* non-archimedean
    inductive domain satisfies a sentence false in the integers `Z`.  Stated: no
    definable non-archimedean inductive domain is elementarily equivalent to the
    standard model. -/
theorem tennenbaum_definable_not_true_arithmetic
    (D : InductiveDomain) (_h : D.NonArchimedean) (_hdef : True)
    (ElemEquivZ : InductiveDomain → Prop) :
    ¬ ElemEquivZ D := by
  sorry -- TODO Theorem 4.2 (definable models satisfy a false sentence)

end Scott1959
